### PR TITLE
Fix various issues in new translation project wizard

### PR DESCRIPTION
**Pull request by ddaspit**
- deemphasize creating non-Scripture projects
- make "project name" page consistent with LF
- make width of "PT credentials" page consistent with rest of wizard

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/223)

### CODE REVIEW

**Comment by irahopkinson** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/angular-app/bellows/apps/translate/new-project/views/new-project-name.html, line 42 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/223#-LAa4E527JDJZTDFG77n:-LAa4E527JDJZTDFG77o:b1n16e2) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1ff975b9d2def1fc8bfe3be6e1d026056e3b8392/src/angular-app/bellows/apps/translate/new-project/views/new-project-name.html#L42)):*
> ```HTML
>                             <div class="input-group" data-ng-show="$ctrl.newProject.editProjectCode">
>                                 <input class="form-control" type="text" data-ng-model="$ctrl.newProject.projectCode" id="projectCode"
>                                        data-ng-trim="false" maxlength="50" required data-ng-blur="checkProjectCode()"
> ```

Shouldn't `ng-blur` still be `$ctrl.checkProjectCode()`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/223)*

**Comment by ddaspit** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/angular-app/bellows/apps/translate/new-project/views/new-project-name.html, line 42 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/223#-LAa4E527JDJZTDFG77n:-LAkL4HpBCgtaE839x9F:b-5npfi6) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1ff975b9d2def1fc8bfe3be6e1d026056e3b8392/src/angular-app/bellows/apps/translate/new-project/views/new-project-name.html#L42)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Shouldn't `ng-blur` still be `$ctrl.checkProjectCode()`?
</blockquote></details>

Good catch. I missed that one.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/223)*

**Comment by ddaspit** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/angular-app/bellows/apps/translate/new-project/views/new-project-name.html, line 42 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/223#-LAa4E527JDJZTDFG77n:-LAkMGfs4OMv-oUrIfYe:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1ff975b9d2def1fc8bfe3be6e1d026056e3b8392/src/angular-app/bellows/apps/translate/new-project/views/new-project-name.html#L42)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Good catch. I missed that one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/223)*

**Comment by irahopkinson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/223#-:-LAkO0RTCn2EaD8laK7W:bnfp4nl)*

**Pull request merged**
