### PR TITLE
migrate ldapi token to new env usage

### PR DESCRIPTION
**Pull request by longrunningprocess**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/913)

### CODE REVIEW

**Comment by longrunningprocess** [comment]
don't forget the following after PR is approved:

- [ ]  bump build-n-publish-images to appropriate commit
- [ ]  add ENV vars to k8s and redeploy

**Review by megahirt — APPROVED** [review]
:lgtm: Great!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/913#-:-MY-KGu14nN80qu6VKyU:bioon7n)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @longrunningprocess)

**Review by longrunningprocess — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/913)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @longrunningprocess)

**Review by longrunningprocess — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/913)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @longrunningprocess)

**Pull request merged**
