### PR TITLE
convert sound player to TypeScript

### PR DESCRIPTION
**Pull request by irahopkinson**
@Nateowami finally got to converting the sound player to TypeScript. Have a look and feel free to ask any questions. @megahirt Can you review?

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/211)

### CODE REVIEW

**Comment by megahirt** [comment]
I'll give @nateowami a chance to review before merging

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/211#-:-L95pL6v-5p58Au-ZgRJ:b-vz8u1)*

**Comment by irahopkinson** [comment]
Thanx. Yes, was all manually tested.

I use my IDE (PhpStorm) to compare files that have changed too much for git to still think they are the same file. I copy the contents of one file to the clipboard and use **View > Compare with Clipboard**.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/211#-:-L98b9klBw7QqnZ8jGwA:bpefjdt)*

**Comment by Nateowami** [comment]
Nice work. :lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/angular-app/bellows/shared/sound-player.component.html, line 9 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/211#-L9AtaSEELjQk5_Y6w4D:-L9AtaSEELjQk5_Y6w4E:bin2jmx) ([raw file](https://github.com/sillsdev/web-languageforge/blob/3676f9d8afda1f845908d8eddbf1bd7f2bb15645/src/angular-app/bellows/shared/sound-player.component.html#L9)):*
> ```HTML
>     </span>
>     
>     <input class="seek-slider ml-2" type="range" min="0" max="{{$ctrl.durationInSeconds()}}" value = 0 id="puiSoundplayerSlider">
> ```

The `value = 0` is a bit weird, though it is (evidently) valid HTML (or at least browsers treat it as such). The blame shows I slipped this in in f62a75a16009325b112f1e49634b53e3edb9a2df.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/211#-:-L9AsJj02OxKuLU9fbaq:bb4nfal)*

**Comment by irahopkinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/angular-app/bellows/shared/sound-player.component.html, line 9 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/211#-L9AtaSEELjQk5_Y6w4D:-L9DQ7r_Cn8-OzN8hsED:b9gmnan) ([raw file](https://github.com/sillsdev/web-languageforge/blob/3676f9d8afda1f845908d8eddbf1bd7f2bb15645/src/angular-app/bellows/shared/sound-player.component.html#L9)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The `value = 0` is a bit weird, though it is (evidently) valid HTML (or at least browsers treat it as such). The blame shows I slipped this in in f62a75a16009325b112f1e49634b53e3edb9a2df.
</blockquote></details>

I'll leave t since I'm not trying to change functionality and it might be important. Feel free to experiment.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/211)*

**Pull request merged**
