### PR TITLE
Chore/remove old files

### PR DESCRIPTION
**Pull request by megahirt**
This cherry-picks a few commits from a branch that I had from back in January that cleans up unused files in the repo.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/868)

### CODE REVIEW

**Review by longrunningprocess — APPROVED** [review]
well, this is AMAZING, thank you so much for cleaning all this up...I feel lighter already!  

I'm not sure how to best mark all those files as reviewed without going through each one, maybe you can show me a way to accomplish something like, "Ok, yeah, any of these files in this directory are ok to be deleted..."  I can't seem to find the right way to do that in Reviewable.

So, I'm not going through each of them ;-)  just trusting this is just some great housekeeping that will have no bearing on functionality or the tests.

> Reviewed 33 of 199 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/868#-:-MVWb5bY459dBFRS_O9h:b-p6nfrz)* status: 33 of 199 files reviewed, all discussions resolved (waiting on @megahirt)

**Review by longrunningprocess — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/868#-:-MVWbhiMBrzuEm_wTjdu:bnfp4nl)* status: 33 of 199 files reviewed, all discussions resolved (waiting on @megahirt)

**Comment by megahirt** [comment]
I feel lighter too!  You can click the purple "mark all as reviewed" as a
shortcut.

Kind regards,

Chris

**Review by longrunningprocess — COMMENTED** [review]
ah ok, I see the text under the MARK AS REVIEWED button but it's not clickable for me...is that a permission thing?



> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/868#-:-MVWhZ-f0nxW9LatkwKy:b-p0rnr)* status: 33 of 199 files reviewed, all discussions resolved (waiting on @megahirt)

**Comment by megahirt** [comment]
You should be able to click the purple button itself and all 186 will be
marked green 💚🍏

Kind regards,

Chris

**Review by longrunningprocess — COMMENTED** [review]
ok, gotcha!  thank you.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/868#-:-MVWl1mQ6s4cBst3gZXv:bxgrds1)* status: 33 of 199 files reviewed, all discussions resolved (waiting on @megahirt)

**Review by longrunningprocess — APPROVED** [review]
> Reviewed 166 of 199 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/868)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

**Review by longrunningprocess — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/868#-:-MVWpc4S3Xg_gk_rRBuv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

**Pull request merged**
