### PR TITLE
Try again to fix intermittent E2E failure

### PR DESCRIPTION
**Pull request by rmunn**
#932 didn't work; maybe this will.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/933)

### CODE REVIEW

**Comment by rmunn** [comment]
First E2E test run succeeded, but I'm going to run it about 4-5 times to give the intermittent bug more chances to trigger if this PR hasn't actually fixed it.

**Comment by rmunn** [comment]
Six test runs in a row succeeded, and a seventh is running now. If that runs, I'd call this PR a success.

**Comment by rmunn** [comment]
The seventh run failed, on the same test that this was designed to try to fix. So this PR didn't work.

**Comment by megahirt** [comment]
Some UI controls are just plain hard to test.  I suppose we should just discard the branch and this PR @rmunn ?

**Comment by rmunn** [comment]
Closing unmerged as this didn't work.

**Pull request closed without merging**
