### PR TITLE
Chore/parameterize website info

### PR DESCRIPTION
**Pull request by longrunningprocess**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/918)

### CODE REVIEW

**Comment by longrunningprocess** [comment]
- [ ] bump `build-n-publish-images` to `master` after merge
- [ ] wait for GHA to publish new images
- [ ] add `WEBSITE=qa.languageforge.org` to k8s and redeploy

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/918)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @longrunningprocess)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYM3z5a7SzYJ8uxEEkQ:-MYM3z5a7SzYJ8uxEEkR:bs3ihi6) (no related file):*
I went ahead and published this image to docker hub, added the ENV var to k8s and redeployed but the site is in an infinite loop of redirects now, maybe you guys can help me sort through the code to understand why it's not dropping out of the cycle.  Thanks.

---

**Review by megahirt — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/918)* status: all files reviewed, 1 unresolved discussion (waiting on @longrunningprocess)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYM3z5a7SzYJ8uxEEkQ:-MYN0ofS2SvZTYVH5DEz:bkyby6a) (no related file):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

I went ahead and published this image to docker hub, added the ENV var to k8s and redeployed but the site is in an infinite loop of redirects now, maybe you guys can help me sort through the code to understand why it's not dropping out of the cycle.  Thanks.
</blockquote></details>

Yes, early on in the development of the Website class we coded the ability to redirect, e.g. from www.languageforge.org to languageforge.org.  And also to redirect to HTTPS.  But neither of these I think are necessary anymore, so I would be happy to simply load up the Website object via a more direct `Website::get()` instead of the `getOrRedirect()`   Hopefully that will fix the redirect issue.  I don't think the Website class needs the ability to do `gethostname()` anymore.  We should simply called `get($hostname)` and make $hostname a required parameter.  Then feed $hostname in from the environment.

---

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/918)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @longrunningprocess)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYM3z5a7SzYJ8uxEEkQ:-MYQk3azDgQPRpebVTGN:b-m80ofd) (no related file):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

Yes, early on in the development of the Website class we coded the ability to redirect, e.g. from www.languageforge.org to languageforge.org.  And also to redirect to HTTPS.  But neither of these I think are necessary anymore, so I would be happy to simply load up the Website object via a more direct `Website::get()` instead of the `getOrRedirect()`   Hopefully that will fix the redirect issue.  I don't think the Website class needs the ability to do `gethostname()` anymore.  We should simply called `get($hostname)` and make $hostname a required parameter.  Then feed $hostname in from the environment.
</blockquote></details>

ok, that's helpful, thank you.  I'll do that.

---

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/918)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @megahirt)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYRGrIx2V6fWSXCN8iR:-MYRGrIy8-uOanF_5Prj:b-8jytrr) (no related file):*
I went ahead and got rid of what appear to be unused code, please double-check those changes @megahirt and make sure they're ok.  Thanks!

---

**Review by megahirt — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/918)* status: all files reviewed, 7 unresolved discussions (waiting on @longrunningprocess)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYRGrIx2V6fWSXCN8iR:-MYcj9BFBdEV2I7fqts2:biqaimk) (no related file):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

I went ahead and got rid of what appear to be unused code, please double-check those changes @megahirt and make sure they're ok.  Thanks!
</blockquote></details>

Great job!  You have tackled several things in this PR.  Great to see you digging into the PHP code some more.  Go ahead and fix up the last few things and we'll get this in.

---
___
*[src/index.php, line 94 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYcj3W-27KXk0nfXLmm:-MYcj3W-27KXk0nfXLmn:b-x76h4e) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5a4431e59b7db1c10877fe94e01e0ae18c4f404d/src/index.php#L94)):*
> ```PHP
> 
> global $WEBSITE;
> $WEBSITE = Website::get();
> ```

Let's make this `$WEBSITE = Website::get(ENV::requireEnv('WEBSITE'));`
___
*[src/Api/Library/Shared/Website.php, line 75 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYchoCu3nRUH5jy_HQk:-MYchoCu3nRUH5jy_HQl:b286vkj) ([raw file](https://github.com/sillsdev/web-languageforge/blob/13a72cca57c948f5042d63edb629e44380a7924b/src/Api/Library/Shared/Website.php#L75)):*
> ```PHP
>      * @return Website
>      */
>     public static function get($hostname = '')
> ```

my suggestion was to simply make $hostname a required parameter and fix up any calls to Website::get() so that they have to pass in the hostname from the environment.

So the signature would look like `public function get($hostname)`
___
*[src/Api/Library/Shared/Website.php, line 79 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYcistZBk64MP6WRUin:-MYcistZBk64MP6WRUio:bgmkeev) ([raw file](https://github.com/sillsdev/web-languageforge/blob/13a72cca57c948f5042d63edb629e44380a7924b/src/Api/Library/Shared/Website.php#L79)):*
> ```
>         if (!$hostname) {
>             $hostname = self::getHostname();
>         }
> ```

delete since $hostname should be a required parameter.
___
*[src/Api/Library/Shared/Website.php, line 89 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYcii6R7GdpwtDeeUYw:-MYcii6R7GdpwtDeeUYx:bo5licr) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5a4431e59b7db1c10877fe94e01e0ae18c4f404d/src/Api/Library/Shared/Website.php#L89)):*
> ```PHP
>     private static function getHostname()
>     {
>         return Env::requireEnv('WEBSITE');
> ```

move this into index.php and call `Website::get(ENV::requireEnv('WEBSITE'));`
___
*[src/Api/Library/Shared/WebsiteInstances.php, line 3 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYcichJEfR-EFDJdpIr:-MYcichJEfR-EFDJdpIs:by3d5nj) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5a4431e59b7db1c10877fe94e01e0ae18c4f404d/src/Api/Library/Shared/WebsiteInstances.php#L3)):*
> ```PHP
> <?php
> 
> // This file is generated by a gulp task from WebsiteInstances.ejs and WebsiteInstances.json. Do not directly modify!
> ```

delete comment.
___
*[src/Api/Library/Shared/WebsiteInstances.php, line 59 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYciUmn-IXA14_JvxLG:-MYciUmn-IXA14_JvxLH:bvml02f) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5a4431e59b7db1c10877fe94e01e0ae18c4f404d/src/Api/Library/Shared/WebsiteInstances.php#L59)):*
> ```PHP
>      * @return array
>      */
>     public static function getRedirects() {
> ```

We should be able to delete this whole static method since we aren't supporting redirects anymore.
___
*[src/angular-app/bellows/core/website-instances.generated-data.ts, line 3 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYciKjS50TfR28vdskQ:-MYciKjS50TfR28vdskR:b-v55duw) ([raw file](https://github.com/sillsdev/web-languageforge/blob/65b9283b890f9d16be161c3521502a4a17ea7df9/src/angular-app/bellows/core/website-instances.generated-data.ts#L3)):*
> ```XML
> // This file is generated by a gulp task from website-instances.ejs and WebsiteInstances.json. Do not directly modify!
> 
> export const websiteInstances = {
> ```

probably best to rename this file to website-instances.ts (drop the generated-data)  then fix up where it is referenced.

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/918)* status: all files reviewed, 7 unresolved discussions (waiting on @longrunningprocess and @megahirt)

___
*[src/index.php, line 94 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYcj3W-27KXk0nfXLmm:-MYe5Vwk4E0zEnUlr4uR:b4ru967) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5a4431e59b7db1c10877fe94e01e0ae18c4f404d/src/index.php#L94)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

Let's make this `$WEBSITE = Website::get(ENV::requireEnv('WEBSITE'));`
</blockquote></details>

I really like that idea but when I did it this way last week, it required duplicating this Env code in `Base.php` as well.  I went with a less code approach but will do it in both if you prefer that over leaving the `getHostName` approach.

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/918)* status: 7 of 11 files reviewed, 6 unresolved discussions (waiting on @megahirt)

___
*[src/index.php, line 94 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYcj3W-27KXk0nfXLmm:-MYf_mVn--ISYYpMtYVh:b-evbibt) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5a4431e59b7db1c10877fe94e01e0ae18c4f404d/src/index.php#L94)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

I really like that idea but when I did it this way last week, it required duplicating this Env code in `Base.php` as well.  I went with a less code approach but will do it in both if you prefer that over leaving the `getHostName` approach.
</blockquote></details>

based on our Slack conversation, I'm going to leave this be for now.
___
*[src/Api/Library/Shared/Website.php, line 75 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYchoCu3nRUH5jy_HQk:-MYf_qtf6iG_hfK91Zpu:buj74fu) ([raw file](https://github.com/sillsdev/web-languageforge/blob/13a72cca57c948f5042d63edb629e44380a7924b/src/Api/Library/Shared/Website.php#L75)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

my suggestion was to simply make $hostname a required parameter and fix up any calls to Website::get() so that they have to pass in the hostname from the environment.

So the signature would look like `public function get($hostname)`
</blockquote></details>

see earlier discussion
___
*[src/Api/Library/Shared/Website.php, line 79 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYcistZBk64MP6WRUin:-MYf_y8L4G0WaP5CCEfv:bn4o3yo) ([raw file](https://github.com/sillsdev/web-languageforge/blob/13a72cca57c948f5042d63edb629e44380a7924b/src/Api/Library/Shared/Website.php#L79)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

> ```
>         if (!$hostname) {
>             $hostname = self::getHostname();
>         }
> ```

delete since $hostname should be a required parameter.
</blockquote></details>

see earlier discussion
___
*[src/Api/Library/Shared/Website.php, line 89 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYcii6R7GdpwtDeeUYw:-MYfa15G-qHK2Y4SmJLd:buj74fu) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5a4431e59b7db1c10877fe94e01e0ae18c4f404d/src/Api/Library/Shared/Website.php#L89)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

move this into index.php and call `Website::get(ENV::requireEnv('WEBSITE'));`
</blockquote></details>

see earlier discussion
___
*[src/Api/Library/Shared/WebsiteInstances.php, line 3 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYcichJEfR-EFDJdpIr:-MYfepDrEedoIJ8XRkfg:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5a4431e59b7db1c10877fe94e01e0ae18c4f404d/src/Api/Library/Shared/WebsiteInstances.php#L3)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

delete comment.
</blockquote></details>

Done.
___
*[src/Api/Library/Shared/WebsiteInstances.php, line 59 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYciUmn-IXA14_JvxLG:-MYff1Kq5-z2ByrB66K2:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5a4431e59b7db1c10877fe94e01e0ae18c4f404d/src/Api/Library/Shared/WebsiteInstances.php#L59)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

We should be able to delete this whole static method since we aren't supporting redirects anymore.
</blockquote></details>

Done.
___
*[src/angular-app/bellows/core/website-instances.generated-data.ts, line 3 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-MYciKjS50TfR28vdskQ:-MYff25WDVUz4dhwC6It:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/65b9283b890f9d16be161c3521502a4a17ea7df9/src/angular-app/bellows/core/website-instances.generated-data.ts#L3)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

probably best to rename this file to website-instances.ts (drop the generated-data)  then fix up where it is referenced.
</blockquote></details>

Done.

**Review by megahirt — APPROVED** [review]
:lgtm: excellent work - thank you!

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/918#-:-MYim04aEPLLlc2qRBSi:bmug0bl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @longrunningprocess)

**Pull request merged**
