### PR TITLE
Fix white space on mobile

### LINKED ISSUE #1151: bug:  Objects are colliding upon scrolling (PWA on Windows)
**Describe the bug**
When I open an entry in the Chrome PWA for Windows 10 and scroll down, the top paragraph of the entry loses its background, causing text to appear on top of other text and GUI elements. Also, the comment buttons are appearing on top of the Activity Feed button. I have tried reopening the PWA, but the problem persists. 

**To Reproduce**
1. Open an entry using Chrome PWA for Windows 10
2. Scroll down
3. Observe the text on top of other text

**Expected behavior**
When scrolling, the top paragraph should keep a white background, so that the paragraph is easy to read and so that it doesn't collide with other elements of the page. The comments buttons should disappear behind the gray bar on which the Activity Feed button is found. 

**Screenshots**
image

image

delete

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 92.0.4515.159 (Official Build) (64-bit) PWA 

**Mobile (please complete the following information): _problem not observed_**
 - Device: Samsung
 - OS: Android 10
 - Browser Chrome PWA

**Android App in Google Play**
For Mobile, are you using the Language Forge Android app in the Google Play store?  No

### PR DESCRIPTION
**Pull request by palmtreefrb**
## Description

Added css styles and FitTextDirective directive class to enable textarea auto sizing on the editor page. 

Fixes #1151, #1144, #1111

### Type of Change

Check all that apply:

- Bug fix (non-breaking change which fixes an issue)

## Screenshots

Screenshot from 2021-09-08 20-15-38

Please describe the manual tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A Load editor page, no white space
- [ ] Test B Reduce page size, no white space

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have reviewed the title/description of this PR which will be used as the squashed PR commit message
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by alex-larkin** [comment]
Awesome!

**Comment by palmtreefrb** [comment]
Linked several issues that are related. Ready for review.
[https://github.com/sillsdev/web-languageforge/issues/1151](https://github.com/sillsdev/web-languageforge/issues/1151)
[https://github.com/sillsdev/web-languageforge/issues/1144](https://github.com/sillsdev/web-languageforge/issues/1144)
[https://github.com/sillsdev/web-languageforge/issues/1111](https://github.com/sillsdev/web-languageforge/issues/1111)

**Comment by palmtreefrb** [comment]
Peek 2021-09-14 09-37

**Comment by palmtreefrb** [comment]
All e2e tests passed locally...
Screenshot from 2021-09-14 15-04-25

**Review by longrunningprocess — CHANGES_REQUESTED** [review]
it's a bummer we have to use hardcoded values (it's going to make things brittle), are we sure `296` and `568` won't need to be changed at any other breakpoints?

Looks like it works, thanks for attaching the animated demo.

Some of the template fields need to be updated before merging.

**Comment by palmtreefrb** [comment]
Yeah, the calc vh with hard coded values was not my first attempt at managing the dynamic resizing of the textarea and the resizing scrolling containers. But it does respect the breakpoints.

**Comment by longrunningprocess** [comment]
> Yeah, the calc vh with hard coded values was not my first attempt and choice at managing the dynamic resizing of the textarea and the resizing scrolling containers. But it does respect the breakpoints.

understood...mind getting the PR template fields in order so I can approve?

**Comment by megahirt** [comment]
> 
> understood...mind getting the PR template fields in order so I can approve?
> 

@palmtreefrb the only thing preventing this from getting approval (and merged) is the PR description.  It is really important to have good documentation around our changes, and the PR is where this happens.  Thanks for taking the time to fill this out.

**Review by megahirt — APPROVED** [review]

**Comment by megahirt** [comment]
Back on [Sept 7 I commented that this PR should target staging](https://github.com/sillsdev/web-languageforge/issues/1111#issuecomment-913946716) and not develop.  Unfortunately, there are several other changes that snuck into this PR that are not related to stabilizing staging with the white space fix.

Today we are onsite with the team using Language Forge and this fix has been getting in the way for them.  In order to attempt to get just the mobile fix to them, I will merge this PR, and then @rmunn or I will extract just the fix from the commit and apply that to staging.

**Pull request merged**
