### PR TITLE
update deployment Makefile with production website

### LINKED ISSUE #1107: update deploy prod makefile with languageforge.org domain
The makefile needs to be updated with the languageforge.org domain name and then the site needs to be redeployed.

### PR DESCRIPTION
**Pull request by megahirt**
change beta.languageforge.org to languageforge.org in the Makefile

TODO:

- [ ] merge this PR
- [ ] merge #1104 (deployable secrets)
- [ ] merge #1103 (staging into master)
- [ ] tag new version on master
- [ ] wait for new images to be built
- [ ] TC deploy new version
- [ ] verify that website is still functioning with new changes

fixes #1107

### CODE REVIEW

**Review by longrunningprocess — APPROVED** [review]

**Review by longrunningprocess — APPROVED** [review]
we need to make sure and get the trust token commits in here as well.

**Comment by megahirt** [comment]
kicked off another unit test run on TC since the build failed due to dockerhub network fail

**Comment by longrunningprocess** [comment]
> kicked off another unit test run on TC since the build failed due to dockerhub network fail

thanks, looks like that did the job

**Comment by megahirt** [comment]
> we need to make sure and get the trust token commits in here as well.

Trust token commit is already in master and staging.  Are you referring to something else?

**Comment by longrunningprocess** [comment]
I guess I just need to talk it out then.  I'm still trying to reconcile all this in my head... Eventually stuff needs to make it's way back down into `develop` and I just don't have it clear in my mind when that's going to occur yet

**Comment by longrunningprocess** [comment]
just a point of clarification, I did approve already in the hopes you'd begin executing on the task list above.

**Pull request merged**
