### PR TITLE
Fix forgot password and BS4ify reset password page

### PR DESCRIPTION
**Pull request by Nateowami**
Fix up forgot password page and port reset password page to Bootstrap 4.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/73)

### CODE REVIEW

**Comment by darcywong00** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/angular-app/bellows/apps/public/reset_password/bootstrap4/reset_password.html, line 63 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73#-KcMXO1NTCz0NTgvET5d:-KcMXO1NTCz0NTgvET5e:b-2yxqp) ([raw file](https://github.com/sillsdev/web-languageforge/blob/77132a5b1b0d05a09e8379be23474d80e9ae74fe/src/angular-app/bellows/apps/public/reset_password/bootstrap4/reset_password.html#L63)):*
> ```HTML
>                                 <i class="fa fa-spinner fa-spin"></i>
>                             </span>
>                             Change Password
> ```

The button for "Reset Password" is "Reset Password"

---

*[src/Site/Controller/App.php, line 288 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73#-KcMXz14RG6JRsp96lKp:-KcMXz15tvDME7Cs5TGG:b-vkrd70) ([raw file](https://github.com/sillsdev/web-languageforge/blob/77132a5b1b0d05a09e8379be23474d80e9ae74fe/src/Site/Controller/App.php#L288)):*
> ```PHP
>                 "siteadmin",
>                 "usermanagement",
>                 "reset_password"
> ```

"reset_password" and all the other Bellows apps really belong in $sharedAppsInBootstrap4 above.  You don't need to change here cause I'll be doing that on another commit

---

*[src/Site/views/languageforge/container/languageforgeBootstrap4.html.twig, line 116 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73#-KcMVrbSxDPF9SSBqCQi:-KcMVrbSxDPF9SSBqCQj:b-9c0ben) ([raw file](https://github.com/sillsdev/web-languageforge/blob/77132a5b1b0d05a09e8379be23474d80e9ae74fe/src/Site/views/languageforge/container/languageforgeBootstrap4.html.twig#L116)):*
> ```Twig
>                 </div>
>             </div>
>             <div class="row">
> ```

The [bootstrap 2 Twig template](https://github.com/sillsdev/web-languageforge/blob/master/src/Site/views/languageforge/container/languageforge.html.twig) put the version div above the copyright div

---

*[src/Site/views/languageforge/theme/default/cssBootstrap4/languageforge_default.css, line 0 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73#-KcMWdlFgCZjtva8GaEL:-KcMWdlFgCZjtva8GaEM:b-1tthuf) ([raw file](https://github.com/sillsdev/web-languageforge/blob/77132a5b1b0d05a09e8379be23474d80e9ae74fe/src/Site/views/languageforge/theme/default/cssBootstrap4/languageforge_default.css#L0)):*
For now, can you comment out the `cleanCSS()` calls in gulp and regenerate the css files?  This will allow us to diff these in-work files

---

*[test/app/bellows/pages/resetPasswordPage.js, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73#-KcMZFPxyWptFpGlpXlx:-KcMZFPxyWptFpGlpXly:be9jxuh) ([raw file](https://github.com/sillsdev/web-languageforge/blob/77132a5b1b0d05a09e8379be23474d80e9ae74fe/test/app/bellows/pages/resetPasswordPage.js#L13)):*
> ```JavaScript
>   this.passwordInput = element(by.model('record.password'));
>   this.confirmPasswordInput = element(by.model('confirmPassword'));
>   this.resetButton = element(by.partialButtonText('Change Password'));
> ```

'Reset Password'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73)*

**Comment by Nateowami** [comment]
@darcywong00 I've fixed those issues and pushed.

**Comment by darcywong00** [comment]
Reviewed 7 of 14 files at r1, 9 of 10 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73)*

**Comment by darcywong00** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73#-:-KcMmCHMJhxPBWfsijjK:bnfp4nl)*

**Comment by darcywong00** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73)*

**Comment by megahirt** [comment]
:lgtm:

---

Reviewed 6 of 14 files at r1, 8 of 10 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/Site/Controller/App.php, line 288 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73#-KcMXz14RG6JRsp96lKp:-KcQRXYhw6plRykc3dKh:b-36242o) ([raw file](https://github.com/sillsdev/web-languageforge/blob/77132a5b1b0d05a09e8379be23474d80e9ae74fe/src/Site/Controller/App.php#L288)):*
<details><summary><i>Previously, darcywong00 (Darcy Wong) wrote…</i></summary><blockquote>

"reset_password" and all the other Bellows apps really belong in $sharedAppsInBootstrap4 above.  You don't need to change here cause I'll be doing that on another commit
</blockquote></details>

however we don't yet have a BS4 frame for scriptureforge, so they can't be shared "yet".  But I'm still fine with putting them there since it's unlikely we'll ship a SF master anytime soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73#-:-KcQS-okcMLRWIMjhO7m:bnfp4nl)*

**Comment by darcywong00** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/angular-app/bellows/apps/public/reset_password/bootstrap4/reset_password.html, line 63 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73#-KcMXO1NTCz0NTgvET5d:-KcQV2FQ-cDRYES9gskP:b32w0x) ([raw file](https://github.com/sillsdev/web-languageforge/blob/77132a5b1b0d05a09e8379be23474d80e9ae74fe/src/angular-app/bellows/apps/public/reset_password/bootstrap4/reset_password.html#L63)):*
<details><summary><i>Previously, darcywong00 (Darcy Wong) wrote…</i></summary><blockquote>

The button for "Reset Password" is "Reset Password"
</blockquote></details>

OK

---

*[src/Site/views/languageforge/container/languageforgeBootstrap4.html.twig, line 116 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73#-KcMVrbSxDPF9SSBqCQi:-KcQV7I8DH8nGLGUiVwD:b32w0x) ([raw file](https://github.com/sillsdev/web-languageforge/blob/77132a5b1b0d05a09e8379be23474d80e9ae74fe/src/Site/views/languageforge/container/languageforgeBootstrap4.html.twig#L116)):*
<details><summary><i>Previously, darcywong00 (Darcy Wong) wrote…</i></summary><blockquote>

The [bootstrap 2 Twig template](https://github.com/sillsdev/web-languageforge/blob/master/src/Site/views/languageforge/container/languageforge.html.twig) put the version div above the copyright div
</blockquote></details>

OK

---

*[src/Site/views/languageforge/theme/default/cssBootstrap4/languageforge_default.css, line  at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73#-KcMWdlFgCZjtva8GaEL:-KcQVAF3izDHskMT2_br:b32w0x) ([raw file](https://github.com/sillsdev/web-languageforge/blob/77132a5b1b0d05a09e8379be23474d80e9ae74fe/src/Site/views/languageforge/theme/default/cssBootstrap4/languageforge_default.css#L)):*
<details><summary><i>Previously, darcywong00 (Darcy Wong) wrote…</i></summary><blockquote>

For now, can you comment out the `cleanCSS()` calls in gulp and regenerate the css files?  This will allow us to diff these in-work files
</blockquote></details>

OK

---

*[test/app/bellows/pages/resetPasswordPage.js, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73#-KcMZFPxyWptFpGlpXlx:-KcQVBP6R-ATKq9e75vQ:b32w0x) ([raw file](https://github.com/sillsdev/web-languageforge/blob/77132a5b1b0d05a09e8379be23474d80e9ae74fe/test/app/bellows/pages/resetPasswordPage.js#L13)):*
<details><summary><i>Previously, darcywong00 (Darcy Wong) wrote…</i></summary><blockquote>

'Reset Password'
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/73)*

**Pull request merged**
