### PR TITLE
migrate remember me env var usage

### PR DESCRIPTION
**Pull request by longrunningprocess**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/910)

### CODE REVIEW

**Comment by longrunningprocess** [comment]
don't forget the following after PR is approved:

- [ ]  bump build-n-publish-images to appropriate commit
- [ ]  add ENV vars to k8s and redeploy

**Review by megahirt — APPROVED** [review]
:lgtm: Great!

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/910#-:-MY-GL6v3ug0PiYkMiF_:bioon7n)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @longrunningprocess)

**Review by longrunningprocess — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/910#-:-MY6j1PM2LC-VoccqBNP:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @megahirt)

**Review by longrunningprocess — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/910)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @longrunningprocess)

**Pull request merged**
