### PR TITLE
Google OAuth login

### PR DESCRIPTION
**Pull request by rmunn**
This adds a "Log in with Google" button to our login screen, and implements the necessary PHP backend code to make it work.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/169)

### CODE REVIEW

**Comment by megahirt** [comment]
Robin, in general this is good work.  This is also a lot of code to review for a single PR.  Next time please break it up into more frequent PRs in the future as this represents several weeks worth of work and is hard to review as a giant PR.

Can you also please describe the user experience of the different paths and what users expect, perhaps also with a few screenshots so I can visualize it?

My assumption is that all PHP Unit tests and E2E tests are passing on your branch (since I don't have that info in this PR)

I haven't finished reviewing but I'll publish what I've seen so far.

---

Reviewed 8 of 12 files at r1, 1 of 5 files at r2, 11 of 14 files at r3.
Review status: 20 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/angular-app/bellows/apps/public/link_oauth_account/helps/en/page/link_oauth_account.md, line 1 at r3](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-Kz3DjqiK7cCrAr02IYN:-Kz3DjqiK7cCrAr02IYO:b-wpwlgk) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4771208f7fdd7772f0a62c348442b46fac2269ad/src/angular-app/bellows/apps/public/link_oauth_account/helps/en/page/link_oauth_account.md#L1)):*
> ```Markdown
> # Help Topic #
> ```

Unfortunately I've abandoned the MD help page idea, so this placeholder can be deleted.

---

*[src/Api/Library/Shared/WebsiteInstances.php, line 31 at r3](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-Kz3ECv0Khx7-2F73nXR:-Kz3ECv0Khx7-2F73nXS:b-l0qveu) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4771208f7fdd7772f0a62c348442b46fac2269ad/src/Api/Library/Shared/WebsiteInstances.php#L31)):*
> ```PHP
>         $sites['scriptureforge.local'] = $w;
> 
>         // Google OAuth wants your domain to end in .org or .com or a "real" top-level domain. So for OAuth testing:
> ```

Can you just use scriptureforge.org with a temporary host entry on your local machine to point scriptureforge.org to localhost?  If so, let's not create another Website definition because this just complicates things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-:-Kz3ErMes4BIjxTrMW6F:b2pvjpw)*

**Comment by rmunn** [comment]
The refactoring to a separate base class is complete, and this is ready to review and merge. Once it's merged into master, it should be immediately testable on dev.scriptureforge.org since the required client IDs and secrets are now passed into Gulp as environment variables. To test it yourself before it's merged into master, look up the configuration parameters in the "Scripture Forge (master)" build on TeamCity. Copy the GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET values (and, if desired, the PARATEXT_CLIENT_ID and PARATEXT_API_KEY values as well) into the following command line:

`GOOGLE_CLIENT_ID=abc GOOGLE_CLIENT_SECRET=xyz gulp build --buildNumber 123 --applicationName scriptureforge`

Run that from the root directory of the web-scriptureforge (or web-languageforge) repo, then restart Apache (`sudo service apache2 restart`). Then edit `/etc/hosts` and add an entry for `scriptureforge.org` that points to 127.0.0.1. Now go to `https://scriptureforge.org` and you should have a working "Log in with Google" button in the login page of your local installation.

---

Review status: 12 of 29 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-:-KzXUeEbKpnOAnKfgKHG:bm3jwmj)*

**Comment by megahirt** [comment]
Reviewed 1 of 12 files at r1, 1 of 14 files at r3, 1 of 2 files at r4, 16 of 17 files at r5.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[gulpfile.js, line 921 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaKODTTjvKyN0cfD4d:-KzaKODTTjvKyN0cfD4e:brdjnmg) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/gulpfile.js#L921)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>
>      type: 'string' })
>     .option('paratextClientId', {
>       demand: false,
>       default: paratextClientId,
>       type: 'string' })
>     .option('paratextApiToken', {
>       demand: false,
>       default: paratextApiToken,
</details>

We can comment these lines out because it's unclear if we'll use these variables in this way.  It's up to Damien's design, we can let him uncomment if he needs it

---

*[gulpfile.js, line 954 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaKbMSsFP2-evbGuQJ:-KzaKbMSsFP2-evbGuQK:bf1pge) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/gulpfile.js#L954)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>       /(define\('PARATEXT_CLIENT_ID', ').*;$/m,
>       '$1' + params.paratextClientId + '\');'))
>     .pipe(replace(
>       /(define\('PARATEXT_API_TOKEN', ').*;$/m,
>       '$1' + params.paratextAp
</details>

Can comment out paratext parameters until Damien wants them in with this method

---

*[src/index.php, line 240 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaK8u9Y2F7hRo6TQgv:-KzaK8u9Y2F7hRo6TQgw:bu2mewz) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/index.php#L240)):*
> ```PHP
> 
> $app->get('/oauthcallback/google', 'Site\OAuth\GoogleOAuth::oauthCallback');
> $app->get('/oauthcallback/paratext', 'Site\OAuth\ParatextOAuth::oauthCallback');
> ```

we can comment out the route for Paratext for now since that is not implemented.

---

*[src/angular-app/bellows/apps/public/link_oauth_account/bootstrap4/link_oauth_account.html, line 9 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaVX6jidApTD_mOPvW:-KzaVX6jidApTD_mOPvX:b-yjiw72) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/angular-app/bellows/apps/public/link_oauth_account/bootstrap4/link_oauth_account.html#L9)):*
> ```HTML
>         <hr>
>         <div style="display: flex; justify-content: space-between">
>             <a href="/auth/login" class="btn btn-success">Yes</a>
> ```

We can fix this up later, but I'm not sure it's useful to make a statement with colors (green vs red) that having an existing account is somehow better or not.  Probably should be the same color, regular button style.

This instead be something like: "Do you already have an account on {% website.name %} or on our sister site, e.g. Language Forge / Scripture Forge ?"

We can continue to refine the wording, but it needs to be site agnostic and take into account the fact that they may not have a SF account, but already have a LF account.  And those need to still match (because it's the same person).  It's even more complicated with the fact that we have a few custom domains now outside of scriptureforge and languageforge, e.g. jamaicanpsalms and waaqiwhatever

---

*[src/Site/Handler/AuthenticationSuccessHandler.php, line 36 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaXkCZMnCCmzWsIJ0O:-KzaXkCZMnCCmzWsIJ0P:bxuurk9) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/Site/Handler/AuthenticationSuccessHandler.php#L36)):*
> ```PHP
>      * @return mixed
>      */
>     public function hasOAuthId(SessionInterface $session)  // TODO: Move to the OAuthProvider base class, along with the next two functions
> ```

go ahead and move to the OAuthProvider base class, as you suggested

---

*[src/Site/Handler/AuthenticationSuccessHandler.php, line 63 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaZMebNqlJ9ZmlYAdL:-KzaZMebNqlJ9ZmlYAdM:b-ruh5yv) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/Site/Handler/AuthenticationSuccessHandler.php#L63)):*
> ```PHP
>     }
> 
>     public function addOAuthIdToUserModel(SessionInterface $session, UserModel $user)
> ```

looks like the base class already had a method with this name.  Which one are you using?  This one or the base class?  There should only be one.

---

*[src/Site/OAuth/OAuthBase.php, line 122 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaapawA86JaPTfBpjP:-KzaapawA86JaPTfBpjQ:b-ies697) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/Site/OAuth/OAuthBase.php#L122)):*
> ```PHP
>      * Do not call write() in this function; that's the job of the calling code.
>      */
>     public function addOAuthIdToUserModel(UserModel $user, string $oauthTokenId)
> ```

method also exists in AuthenticationSuccessHandler

---

*[src/Site/OAuth/SelectAccountAuthorizationParametersTrait.php, line 8 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzablW6SXrC4U_zV_4K:-KzablW6SXrC4U_zV_4L:b-2cf3aw) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/Site/OAuth/SelectAccountAuthorizationParametersTrait.php#L8)):*
> ```PHP
>  * Use this trait in any OAuthProviders you create, so that you don't have to duplicate this code repeatedly
>  */
> trait SelectAccountAuthorizationParametersTrait
> ```

Not having used traits before, how is this different than just keeping the functionality on the base class?  What does this buy us?  I read that traits are used to group common functionality between classes that don't share a base class, in languages like PHP that don't do multiple inheritance.  I guess I'm not seeing why this method can't just be in the base class itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169)*

**Comment by megahirt** [comment]
I had a few comments, and I'm hoping that they are still relevant given that you've worked on this since I first saw the code.  Looks good to me after addressing comments.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-:-Kzadfy4_IPrgUZfZE6-:bkfrugz)*

**Comment by rmunn** [comment]
Review status: 26 of 34 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/angular-app/bellows/apps/public/link_oauth_account/bootstrap4/link_oauth_account.html, line 9 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaVX6jidApTD_mOPvW:-KzbZvsxu9ubBedLmkRf:b-17nqnx) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/angular-app/bellows/apps/public/link_oauth_account/bootstrap4/link_oauth_account.html#L9)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

We can fix this up later, but I'm not sure it's useful to make a statement with colors (green vs red) that having an existing account is somehow better or not.  Probably should be the same color, regular button style.

This instead be something like: "Do you already have an account on {% website.name %} or on our sister site, e.g. Language Forge / Scripture Forge ?"

We can continue to refine the wording, but it needs to be site agnostic and take into account the fact that they may not have a SF account, but already have a LF account.  And those need to still match (because it's the same person).  It's even more complicated with the fact that we have a few custom domains now outside of scriptureforge and languageforge, e.g. jamaicanpsalms and waaqiwhatever
</blockquote></details>

I do want to make a statement that having an existing account is the better choice, so that anyone who *does* have an existing account will be led to pick that one. (That's also why I placed that choice first). But after looking at it, I agree that red is a bit harsh for the "No" choice: people will think that red means "Cancel" or something. How about green for "Yes", and normal button color (cyan-ish) for the "No"?

Also, I see I left a `style="..."` attribute in there. That should be turned into a class and moved over to the .scss file. As for the wording, custom domains do start to complicate things. I'll make it more generic, but won't wait on the wording to be finalized before I deploy: that would be a classic case of making the perfect the enemy of the good.

---

*[src/Site/Handler/AuthenticationSuccessHandler.php, line 63 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaZMebNqlJ9ZmlYAdL:-Kzb_i5Wfg-Kx9qikx90:bcgua1f) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/Site/Handler/AuthenticationSuccessHandler.php#L63)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

looks like the base class already had a method with this name.  Which one are you using?  This one or the base class?  There should only be one.
</blockquote></details>

The base class method is the one I intend to keep. The duplication happened because as I was moving functions over to the base class, I forgot that this one was still here. I'll just delete this function rather than rename it, because it should no longer be needed.

---

*[src/Site/OAuth/SelectAccountAuthorizationParametersTrait.php, line 8 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzablW6SXrC4U_zV_4K:-Kzba6MAEOgDFnstW8k0:b-b3vp0t) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/Site/OAuth/SelectAccountAuthorizationParametersTrait.php#L8)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

Not having used traits before, how is this different than just keeping the functionality on the base class?  What does this buy us?  I read that traits are used to group common functionality between classes that don't share a base class, in languages like PHP that don't do multiple inheritance.  I guess I'm not seeing why this method can't just be in the base class itself.
</blockquote></details>

I figured I would end up re-implementing this function in the Facebook OAuth code once we write it, and I wanted a way to inherit a single function without inheriting a class. PHP traits seem designed to do that. But when there's just the one Google OAuth flow at the moment, we're not gaining anything from having this in a trait, and it does cost a little bit in readability and discoverability. So I can move it back into the Google OAuth code and stop having it as a trait — unless we plan to implement "Log in with Facebook" right away.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169)*

**Comment by rmunn** [comment]
Review status: 21 of 35 files reviewed at latest revision, 10 unresolved discussions.

---

*[gulpfile.js, line 921 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaKODTTjvKyN0cfD4d:-KzbhNTj1N2H8x1GB4dv:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/gulpfile.js#L921)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

>      type: 'string' })
>     .option('paratextClientId', {
>       demand: false,
>       default: paratextClientId,
>       type: 'string' })
>     .option('paratextApiToken', {
>       demand: false,
>       default: paratextApiToken,

We can comment these lines out because it's unclear if we'll use these variables in this way.  It's up to Damien's design, we can let him uncomment if he needs it
</blockquote></details>

Done.

---

*[gulpfile.js, line 954 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaKbMSsFP2-evbGuQJ:-KzbhODIOGoz2Yjs3gCT:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/gulpfile.js#L954)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

>       /(define\('PARATEXT_CLIENT_ID', ').*;$/m,
>       '$1' + params.paratextClientId + '\');'))
>     .pipe(replace(
>       /(define\('PARATEXT_API_TOKEN', ').*;$/m,
>       '$1' + params.paratextAp

Can comment out paratext parameters until Damien wants them in with this method
</blockquote></details>

Done.

---

*[src/index.php, line 240 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaK8u9Y2F7hRo6TQgv:-KzbhntbFq-ld2sV9o-V:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/index.php#L240)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

we can comment out the route for Paratext for now since that is not implemented.
</blockquote></details>

Done.

---

*[src/angular-app/bellows/apps/public/link_oauth_account/bootstrap4/link_oauth_account.html, line 9 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaVX6jidApTD_mOPvW:-KzbyKg7OsiugMXogTQ5:b3hzwfm) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/angular-app/bellows/apps/public/link_oauth_account/bootstrap4/link_oauth_account.html#L9)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

I do want to make a statement that having an existing account is the better choice, so that anyone who *does* have an existing account will be led to pick that one. (That's also why I placed that choice first). But after looking at it, I agree that red is a bit harsh for the "No" choice: people will think that red means "Cancel" or something. How about green for "Yes", and normal button color (cyan-ish) for the "No"?

Also, I see I left a `style="..."` attribute in there. That should be turned into a class and moved over to the .scss file. As for the wording, custom domains do start to complicate things. I'll make it more generic, but won't wait on the wording to be finalized before I deploy: that would be a classic case of making the perfect the enemy of the good.
</blockquote></details>

Done. Ira said something about us *not* wanting to claim that SF and LF are sister sites, so I've made the text only say"Do you have an account on {{ website_name }}?" to keep it as simple as possible.

---

*[src/Site/Handler/AuthenticationSuccessHandler.php, line 36 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaXkCZMnCCmzWsIJ0O:-Kzbwxr9POqoGRFa90dh:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/Site/Handler/AuthenticationSuccessHandler.php#L36)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

go ahead and move to the OAuthProvider base class, as you suggested
</blockquote></details>

Done.

---

*[src/Site/Handler/AuthenticationSuccessHandler.php, line 63 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaZMebNqlJ9ZmlYAdL:-KzbwzAPLgAIdODXoN06:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/Site/Handler/AuthenticationSuccessHandler.php#L63)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

The base class method is the one I intend to keep. The duplication happened because as I was moving functions over to the base class, I forgot that this one was still here. I'll just delete this function rather than rename it, because it should no longer be needed.
</blockquote></details>

Done.

---

*[src/Site/OAuth/OAuthBase.php, line 122 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzaapawA86JaPTfBpjP:-KzbyBNXewydTkFQR5cL:b-i64wx6) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/Site/OAuth/OAuthBase.php#L122)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

method also exists in AuthenticationSuccessHandler
</blockquote></details>

Done. (By removing the duplicate in AuthenticationSuccessHandler).

---

*[src/Site/OAuth/SelectAccountAuthorizationParametersTrait.php, line 8 at r5](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-KzablW6SXrC4U_zV_4K:-KzbyjHukJ6FbZg-NCPg:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/79b9b16800ec8e9cdeb63a82c464df6902246853/src/Site/OAuth/SelectAccountAuthorizationParametersTrait.php#L8)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

I figured I would end up re-implementing this function in the Facebook OAuth code once we write it, and I wanted a way to inherit a single function without inheriting a class. PHP traits seem designed to do that. But when there's just the one Google OAuth flow at the moment, we're not gaining anything from having this in a trait, and it does cost a little bit in readability and discoverability. So I can move it back into the Google OAuth code and stop having it as a trait — unless we plan to implement "Log in with Facebook" right away.
</blockquote></details>

Done.

---

*[src/angular-app/bellows/apps/public/link_oauth_account/helps/en/page/link_oauth_account.md, line 1 at r3](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-Kz3DjqiK7cCrAr02IYN:-KzbyFl7zDx2pOQJZLCb:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4771208f7fdd7772f0a62c348442b46fac2269ad/src/angular-app/bellows/apps/public/link_oauth_account/helps/en/page/link_oauth_account.md#L1)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

Unfortunately I've abandoned the MD help page idea, so this placeholder can be deleted.
</blockquote></details>

Done.

---

*[src/Api/Library/Shared/WebsiteInstances.php, line 31 at r3](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-Kz3ECv0Khx7-2F73nXR:-KzbyGmCNxImFYcPMxn9:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4771208f7fdd7772f0a62c348442b46fac2269ad/src/Api/Library/Shared/WebsiteInstances.php#L31)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

Can you just use scriptureforge.org with a temporary host entry on your local machine to point scriptureforge.org to localhost?  If so, let's not create another Website definition because this just complicates things.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169)*

**Comment by rmunn** [comment]
I believe I've addressed all of Chris's comments with the latest change, so I'll go ahead and merge into master, and start the process of testing on dev.scriptureforge.org.

---

Review status: 21 of 35 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/169#-:-Kzc4R6rV7y8PpbFqfmd:bwlwwg9)*

**Pull request merged**
