### PR TITLE
Fix Homepage issues (SF-80, SF-82)

### PR DESCRIPTION
**Pull request by jasonleenaylor**
* Add Footer to viewport
* Improve small screen design & usability

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/423)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
Probably not, I'll remove it and all the associated nonsense.

**Comment by jasonleenaylor** [comment]
___
*[src/SIL.XForge.Scripture/Views/Shared/_Layout.cshtml, line 35 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/423#-LQN5epcDGp-i_78j7WN:-LQZdUS4918_PUBK985F:b-xftc7e) ([raw file](https://github.com/sillsdev/web-languageforge/blob/643492e3aec4d39eb5e19d8bed5852c4c386b500/src/SIL.XForge.Scripture/Views/Shared/_Layout.cshtml#L35)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> <a href="/terms_and_conditions">terms and conditions</a>
> ```
Where does this link go?
</blockquote></details>

Well, no-where at the moment. I guess I could snag the old content.

**Comment by jasonleenaylor** [comment]
___
*[src/SIL.XForge.Scripture/wwwroot/js/headershadow.js, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/423#-LQN54VB7BrCB6RMxiS2:-LQZdqRt-UoTbGIQzfXO:b-14n2j2) ([raw file](https://github.com/sillsdev/web-languageforge/blob/643492e3aec4d39eb5e19d8bed5852c4c386b500/src/SIL.XForge.Scripture/wwwroot/js/headershadow.js#L4)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> $(
> ```
Does this mean we are using JQuery? I would like to actively avoid using JQuery in this version.
</blockquote></details>

Good to know. Removed.

**Comment by jasonleenaylor** [comment]
___
*[src/SIL.XForge.Scripture/wwwroot/js/headershadow.js, line 1 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/423#-LQLE96r9VJwJaAYIZgv:-LQZdnCN9C1VmkYy9fBH:bm6g9ac) ([raw file](https://github.com/sillsdev/web-languageforge/blob/643492e3aec4d39eb5e19d8bed5852c4c386b500/src/SIL.XForge.Scripture/wwwroot/js/headershadow.js#L1)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

this needs to be throttled
</blockquote></details>

Thoroughly throttled.

**Comment by jasonleenaylor** [comment]
___
*[src/SIL.XForge.Scripture/Views/Shared/_Layout.cshtml, line 35 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/423#-LQN5epcDGp-i_78j7WN:-LQ_IiSb6McwKEFSJFPy:b-oxkgiv) ([raw file](https://github.com/sillsdev/web-languageforge/blob/643492e3aec4d39eb5e19d8bed5852c4c386b500/src/SIL.XForge.Scripture/Views/Shared/_Layout.cshtml#L35)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Well, no-where at the moment. I guess I could snag the old content.
</blockquote></details>

Decided to put the terms_and_conditions in https://jira.sil.org/browse/SF-87

**Comment by irahopkinson** [comment]
@jasonleenaylor feel free to rebase and merge this.

**Pull request merged**
