### PR TITLE
New LF Header Layout

### PR DESCRIPTION
**Pull request by nigel-wells**
Relates to https://trello.com/c/E0WVx3WN

Covers a new layout to the header area for desktop and mobile.

Most apps have been updated for setting the breadcrumbs and new page name

Settings can now be set per app or view

image

image

There are a couple of E2E tests failing but they also fail for me in `master` so I assume this is ok.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241)

### CODE REVIEW

**Comment by irahopkinson** [comment]
This looks really good, nice job. And well done hunting down the double API call; is there an open issue for that? I have a few suggestions and questions.

I also wonder if the *My Projects* and *user* dropdowns should be swapped?

---

Reviewed 41 of 41 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/angular-app/bellows/apps/changepassword/change-password-app.module.ts, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTb5CC-xWX7gMC6f_U:-LBTb5CC-xWX7gMC6f_V:bmfkouy) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/changepassword/change-password-app.module.ts#L10)):*
> ```
> 'sgw.ui.breadcrumb'
> ```
Since this is in TS, use `BreadcrumbModule` instead and `import {BreadcrumbModule} from '../../core/breadcrumbs/breadcrumb.module';` above.

---

*[src/angular-app/bellows/apps/projects/projects-app.module.ts, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTcjfb0AmmP3l_x_rU:-LBTcjfb0AmmP3l_x_rV:bmfkouy) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/projects/projects-app.module.ts#L10)):*
> ```
> 'sgw.ui.breadcrumb'
> ```
Since this is in TS, use `BreadcrumbModule` instead and `import {BreadcrumbModule} from '../../core/breadcrumbs/breadcrumb.module';` above.

---

*[src/angular-app/bellows/apps/siteadmin/site-admin-app.module.ts, line 12 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTcsgh2R8jQoaXzuRj:-LBTcsgh2R8jQoaXzuRk:bmfkouy) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/siteadmin/site-admin-app.module.ts#L12)):*
> ```
> 'sgw.ui.breadcrumb'
> ```
Since this is in TS, use `BreadcrumbModule` instead and `import {BreadcrumbModule} from '../../core/breadcrumbs/breadcrumb.module';` above.

---

*[src/angular-app/bellows/apps/siteadmin/site-admin.component.html, line 13 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTd5Br0SJohJTKGEQh:-LBTd5Br0SJohJTKGEQi:bq4898z) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/siteadmin/site-admin.component.html#L13)):*
> ```HTML
>         </uib-tab>
>     </uib-tabset>
> </div>
> ```

Files should have one blank line at end.

---

*[src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts, line 12 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTdbCu9vzzCgICyMI1:-LBTdbCu9vzzCgICyMI2:bmfkouy) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts#L12)):*
> ```
> 'sgw.ui.breadcrumb'
> ```
Since this is in TS, use `BreadcrumbModule` instead and `import {BreadcrumbModule} from '../../core/breadcrumbs/breadcrumb.module';` above.

---

*[src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts, line 12 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTeAqg26jPjPHTwGca:-LBTeAqg26jPjPHTwGcb:b-bnjsls) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts#L12)):*
> ```
> 'lexiconCoreModule'
> ```
This is a shared app therefore it cannot be dependent on the lexicon app. Perhaps you need to move something from lexicon core to bellows core?

---

*[src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts, line 13 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTdzBqDJxDjTjVbVEc:-LBTdzBqDJxDjTjVbVEd:b-j0qvqj) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts#L13)):*
> ```
> 'pascalprecht.translate'
> ```
We are meant to be removing this not adding it back in! Please remove this and related additions below.

---

*[src/angular-app/bellows/apps/userprofile/user-profile-app.component.ts, line 3 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTeio-2AOXB3uyPZwe:-LBTeio-2AOXB3uyPZwf:bgc15ii) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/userprofile/user-profile-app.component.ts#L3)):*
> ```XML
> import * as angular from 'angular';
> 
> import { UserService } from '../../core/api/user.service';
> ```

Style: Sorry for the confusion here, we are going back to *not* have spaces here. Some files haven't been updated yet. Please remove them whenever you see them.

---

*[src/angular-app/bellows/apps/userprofile/user-profile-app.module.ts, line 9 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTf8VW011mHYSKQTgs:-LBTf8VW011mHYSKQTgt:bmfkouy) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/userprofile/user-profile-app.module.ts#L9)):*
> ```
> 'sgw.ui.breadcrumb'
> ```
Since this is in TS, use `BreadcrumbModule` instead and `import {BreadcrumbModule} from '../../core/breadcrumbs/breadcrumb.module';` above.

---

*[src/angular-app/bellows/core/core.module.ts, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTfIJI0_wpDStk0akC:-LBTfIJI0_wpDStk0akD:b-iig2o8) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/core/core.module.ts#L10)):*
> ```XML
> import {UserRestApiService} from './api/user-rest-api.service';
> import {UserService} from './api/user.service';
> import { ApplicationHeaderService } from './application-header.service';
> ```

Style: Remove leading and trailing spaces inside {} braces.

---

*[src/angular-app/languageforge/lexicon/core/lexicon-project.service.ts, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTfhOMCAJUidxSZWa7:-LBTfhOMCAJUidxSZWa8:b-hlduno) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/languageforge/lexicon/core/lexicon-project.service.ts#L4)):*
> ```XML
> 
> import { ApiService, JsonRpcCallback } from '../../../bellows/core/api/api.service';
> import { ApplicationHeaderService, HeaderSetting } from '../../../bellows/core/application-header.service';
> ```

Style: Remove leading and trailing spaces in {{} braces.

---

*[src/angular-app/languageforge/lexicon/core/lexicon-project.service.ts, line 24 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTfoBD1dUpB6cl3xIE:-LBTfoBD1dUpB6cl3xIF:bozv2kc) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/languageforge/lexicon/core/lexicon-project.service.ts#L24)):*
> ```XML
> 
>   setBreadcrumbs(view: string, label: string, forceRefresh: boolean = false): void {
>     this.$q.all([this.sessionService.getSession()]).then(([session]) => {
> ```

I'm confused by this line change. It removes `forceRefresh` functionality and employs `$q.all` unnecessarily. What am I missing?

---

*[src/Site/views/languageforge/container/languageforge.html.twig, line 95 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTgtSKBzLfLQN-Qr0y:-LBTgtSKBzLfLQN-Qr0z:bfxy87p) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b583f86663bb3a0a4f415a27e63f81cc42c6bac3/src/Site/views/languageforge/container/languageforge.html.twig#L95)):*
> ```Twig
>                         <div class="dropdown-menu dropdown-menu-right" uib-dropdown-menu aria-labelledby="myProjectDropdown">
>                             {% verbatim %}
>                             <div data-ng-switch="$ctrl.projectTypesBySite().length" data-ng-show="$ctrl.rights.canCreateProject">
> ```

I don't see how it works if you remove all these `$ctrl.` items that attach it to the navbar controller?

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-:-LBTi-he-67DRjy7r93B:b9ho37w)*

**Comment by megahirt** [comment]
I don't have time to review all this code in detail at this moment but I'm happy to rubber stamp it given Ira's review.  Thanks Nigel for your work getting this in.  Are we ready to merge?

One other side note regarding the header.  We are going to want to bolt in the UI Language picker.  It's currently absolutely positioned in the bottom right but we want to integrate it into the header.  I'm thinking another drop down next to the Help button.  thoughts?  This would be a separate task of course.

---

Reviewed 36 of 41 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-:-LBTtCNu-80z9bZuqvAg:b74ks4y)*

**Comment by megahirt** [comment]
Ira, please merge this PR when you are satisfied.

---

Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-:-LBTu7VkDju-jafMb3Bb:b-16cns4)*

**Comment by irahopkinson** [comment]
Swapping those was just my initial reaction. It works either way really. Given most websites I think the interface language picker should go top-right (with country flag icons if possible). If the interface is in a language you don't know you need to find this control really easily.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/angular-app/bellows/apps/changepassword/change-password-app.module.ts, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTb5CC-xWX7gMC6f_U:-LBU-0eXBzBdlB_BoUYH:b-7av3av) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/changepassword/change-password-app.module.ts#L10)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

> import {BreadcrumbModule} from '../../core/breadcrumbs/breadcrumb.module';
The name of the module in `breadcrumb.module` is `sgw.ui.breadcrumb`. I believe you reference that module name rather than the exported variable. I also tried what you suggested but it could no longer find the breadcrumb module.
</blockquote></details>

I changed this file to
```
import * as angular from 'angular';

import {BreadcrumbModule} from '../../core/breadcrumbs/breadcrumb.module';
import {CoreModule} from '../../core/core.module';
import {NoticeModule} from '../../core/notice/notice.module';
import {PuiUtilityModule} from '../../shared/utils/pui-utils.module';
import {ChangePasswordAppComponent} from './change-password-app.component';

export const ChangePasswordAppModule = angular
  .module('changepassword', ['ui.bootstrap', 'ui.validate', 'zxcvbn', CoreModule,
    NoticeModule, PuiUtilityModule, BreadcrumbModule
  ])
  .component('changePasswordApp', ChangePasswordAppComponent)
  .name;
```
and it works for me.

---

*[src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts, line 12 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTeAqg26jPjPHTwGca:-LBTzTXuE4kaZUVgZdRH:b-gg73hd) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts#L12)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Ah yes, keep forgetting about SF being linked up to some of these. What I was trying to do was keep the settings app and breadcrumb consistent. Previously the settings drop down disappeared and a back button was shown - but it looked quite funny with the button just floating up there. Do we happen to have a generic project module that could be used in instances like this which can then reference off the relevant projects when needed i.e. a SF project vs a LF project? I could just put the breadcrumb back in the same way it worked before but the settings would drop off which would feel a bit odd seeming you used the settings to get here in the first place. Perhaps user management should be removed from that dropdown and put under the main user dropdown in the top right?
</blockquote></details>

I think leave it for now. As it turns out SF doesn't use this *User Management* app and this component should be moved into the lexicon.

---

*[src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts, line 13 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTdzBqDJxDjTjVbVEc:-LBTxY2h2yiIuQMgtLoh:b-2l26sg) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts#L13)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Ah, what is the preferred method to do this? What I found is the user management app didn't appear to translate any code where the HTML `data-translate`attribute was present. As this is used for settings I needed a way to do this. I could just note use the attribute and just output the label directly if that is preferred?
</blockquote></details>

Yes output the label directly so you can remove all `data-translate` attributes.

---

*[src/Site/views/languageforge/container/languageforge.html.twig, line 95 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTgtSKBzLfLQN-Qr0y:-LBTyRTuCEshOJYB144P:bxtm8fq) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b583f86663bb3a0a4f415a27e63f81cc42c6bac3/src/Site/views/languageforge/container/languageforge.html.twig#L95)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Not sure I completely follow what you're referring to with this line of code you've commented on - perhaps you meant further down on line 85? I guess I could use `verbatim` but `$ctrl.header.pageName` works without messing up the twig interpreter. Happy to follow your lead
</blockquote></details>

Look at the original diff. You have changed `$ctrl.projectTypesBySite().length` to `projectTypesBySite().length` and `$ctrl.rights.canCreateProject` to `rights.canCreateProject` etc removing all the leading `$ctrl.` (7 removed). That's why the *Start or Join a New Project* never shows up in the *My Projects*. Try creating a new project without this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-:-LBTuyWp2s6Efsf9T5c2:b-3rot0x)*

**Comment by irahopkinson** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/angular-app/languageforge/lexicon/settings/configuration/configuration.component.html, line 3 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBU0zgH1G5e1tozw9Cg:-LBU0zgH1G5e1tozw9Ch:b6fa0me) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d3f783e8c835eeb2c18bf249401e70c4fab16949/src/angular-app/languageforge/lexicon/settings/configuration/configuration.component.html#L3)):*
> ```
> Apply</button>
> ```
For me the *Apply* button is sitting on the right where it should be but the tab contents are squished to the left to leave space for it. Is it like that for you?

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241)*

**Comment by irahopkinson** [comment]
Reviewed 1 of 5 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241)*

**Comment by irahopkinson** [comment]
Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241)*

**Comment by nigel-wells** [comment]
Could go top right but you start to run out of room on mobile devices. As the footer is also fixed it could be placed down there easily without too much issue trying to find it. I also wouldn't recommend using flags either - big discussion around this in the UX area. Simple argument: Country != Language. Some countries have multiple languages. Whose flag do you have for English- sure it should be the NZ flag ;) 

---

Review status: 34 of 41 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/angular-app/bellows/apps/changepassword/change-password-app.module.ts, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTb5CC-xWX7gMC6f_U:-LBU2xJE8lGGam-xgf5u:b242j54) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/changepassword/change-password-app.module.ts#L10)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I changed this file to
```
import * as angular from 'angular';

import {BreadcrumbModule} from '../../core/breadcrumbs/breadcrumb.module';
import {CoreModule} from '../../core/core.module';
import {NoticeModule} from '../../core/notice/notice.module';
import {PuiUtilityModule} from '../../shared/utils/pui-utils.module';
import {ChangePasswordAppComponent} from './change-password-app.component';

export const ChangePasswordAppModule = angular
  .module('changepassword', ['ui.bootstrap', 'ui.validate', 'zxcvbn', CoreModule,
    NoticeModule, PuiUtilityModule, BreadcrumbModule
  ])
  .component('changePasswordApp', ChangePasswordAppComponent)
  .name;
```
and it works for me.
</blockquote></details>

Duh, sorry I didn't remove the quotes around `BreadcrumbModule`! Working now.

---

*[src/angular-app/bellows/apps/projects/projects-app.module.ts, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTcjfb0AmmP3l_x_rU:-LBU33cV8pU9p-iiGz-s:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/projects/projects-app.module.ts#L10)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

As above
</blockquote></details>

Done.

---

*[src/angular-app/bellows/apps/siteadmin/site-admin-app.module.ts, line 12 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTcsgh2R8jQoaXzuRj:-LBU3M0BEfyVdnNHSrkK:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/siteadmin/site-admin-app.module.ts#L12)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

As above
</blockquote></details>

Done.

---

*[src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts, line 12 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTdbCu9vzzCgICyMI1:-LBU3fnRBi2Fh0Ucsz0A:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts#L12)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

As above
</blockquote></details>

Done.

---

*[src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts, line 13 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTdzBqDJxDjTjVbVEc:-LBU8J_g-xtF4s2yNAfT:b-i8yx7t) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts#L13)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yes output the label directly so you can remove all `data-translate` attributes.
</blockquote></details>

Done. I have reverted most of this file back to what I found in `master`.

---

*[src/angular-app/bellows/apps/userprofile/user-profile-app.module.ts, line 9 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTf8VW011mHYSKQTgs:-LBU4Nwd23RlnrLlt_-U:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b3de4e65cd4008450e1651696228566cd5c74ac9/src/angular-app/bellows/apps/userprofile/user-profile-app.module.ts#L9)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

As above
</blockquote></details>

Done.

---

*[src/angular-app/languageforge/lexicon/settings/configuration/configuration.component.html, line 3 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBU0zgH1G5e1tozw9Cg:-LBU5wo14Skyn2yc70Qi:besatv5) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d3f783e8c835eeb2c18bf249401e70c4fab16949/src/angular-app/languageforge/lexicon/settings/configuration/configuration.component.html#L3)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> Apply</button>
> ```
For me the *Apply* button is sitting on the right where it should be but the tab contents are squished to the left to leave space for it. Is it like that for you?
</blockquote></details>

Have placed the button in its own row now that it can't sit alongside the page title

---

*[src/Site/views/languageforge/container/languageforge.html.twig, line 95 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-LBTgtSKBzLfLQN-Qr0y:-LBU57YP7m0undgqkMq4:b-qgp36t) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b583f86663bb3a0a4f415a27e63f81cc42c6bac3/src/Site/views/languageforge/container/languageforge.html.twig#L95)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Look at the original diff. You have changed `$ctrl.projectTypesBySite().length` to `projectTypesBySite().length` and `$ctrl.rights.canCreateProject` to `rights.canCreateProject` etc removing all the leading `$ctrl.` (7 removed). That's why the *Start or Join a New Project* never shows up in the *My Projects*. Try creating a new project without this.
</blockquote></details>

Ah right. This is a case of me initially starting the project way back at the start of Feb and having the project put on hold - lots of changes during that time. I've added them back in and the link is showing back up as you would expect.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-:-LBU28rw9JzSjp47vG8u:b-utd1uy)*

**Comment by megahirt** [comment]
Yes the NZ flag should represent English world-wide!  Good point about the flags.  I know it's getting tight in the header.  could the language picker be present in the header for the  tablet/desktop version but in mobile it's tucked into the hamburger menu?

---

Review status: 34 of 41 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-:-LBU9a061FbAZy0f2uPx:b-iya0ns)*

**Comment by megahirt** [comment]
:lgtm:

---

Review status: 34 of 41 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-:-LBUA1ak0l0kF5WHO-ap:bnfp4nl)*

**Comment by megahirt** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241)*

**Comment by irahopkinson** [comment]
Reviewed 7 of 7 files at r3.
Review status: 40 of 41 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241)*

**Comment by irahopkinson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-:-LBUGOEH2y2CpSwwUdro:bnfp4nl)*

**Comment by irahopkinson** [comment]
Just did a final run of E2E and it looks like the CSS for typeahead may have been affected by your changes. Its failing in the Bellows **project** spec at **can list two projects of which the user is a member**. Go to **User Management**, click **Add Member**, type a member name to add. The results `div` should be directly below the input but is half hidden in the header so E2E can't click on it. Can you fix this ? Then we are good to merge.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-:-LBUPNRz97u-jRbVkVks:bdein0q)*

**Comment by nigel-wells** [comment]
Chris, yes that will work for the language selector to place it in the hamburger menu for mobile and always visible for other devices.

I've pushed through style change for the typeahead component. Now just the 3 failed E2E which I get in master as well.

---

Review status: 41 of 42 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-:-LBXZ0Zm3BRSeQyraWey:b-9chm3w)*

**Comment by irahopkinson** [comment]
:lgtm: E2E all passing for me.

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/241#-:-LBXrWWLByeccNA1dGoB:b-732k06)*

**Pull request merged**
