### PR TITLE
Fixed the empty entries bug

### PR DESCRIPTION
**Pull request by feliks-montez**
# Overview
On some computers, upon loading the entries in a project, the entries list returned blank. See the following screenshot of the issue:
empty_entries_bug

# Technical Details
There was a race condition between `lexProjectService.users()` and `loadEditorData()` within `$onInit()` in `LexiconAppController`. I restructured `$onInit()` to ensure that `loadEditorData()` always runs _after_ `lexProjectService.users()` finishes. 
See [the trello card](https://trello.com/c/Os5YtuQI/368-on-startup-empty-entries) for more technical details.

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/725)

### CODE REVIEW

**Comment by feliks-montez** [comment]
[On startup, empty entries](https://trello.com/c/Os5YtuQI/368-on-startup-empty-entries)

**Comment by feliks-montez** [comment]
# Overview
On some computers, upon loading the entries in a project, the entries list returned blank.

# Technical Details
There was a race condition between `lexProjectService.users()` and `loadEditorData()` within `$onInit()` in `LexiconAppController`. I restructured `$onInit()` to ensure that `loadEditorData()` always runs _after_ `lexProjectService.users()` finishes. 
See [the trello card](https://trello.com/c/Os5YtuQI/368-on-startup-empty-entries) for more technical details.

**Comment by megahirt** [comment]
I copied @feliks-montez  's comment up to the PR message, which is where it should have been.  This is not a bad PR message, although it lacks some coherence if you don't have inside knowledge of the problem.  This PR fixes a user-facing UI problem that could have a screenshot demo'ed here.

**Comment by feliks-montez** [comment]
[Get E2E tests running on 18.04 dev machines](https://trello.com/c/SRqo2IWy/372-get-e2e-tests-running-on-1804-dev-machines)

**Pull request merged**
