### PR TITLE
Improvements on mobile

### PR DESCRIPTION
**Pull request by Nateowami**
Miscellaneous improvements, some for layout on small screens, others to remove reliance on hovering in order to show something (because touch screens don't have hover).

Also makes rune2e.sh exit with the exit status of the gulp task that ran the tests (`gulp test-e2e-run`).

Here's the change to the language select modal. it was possible to use it before, but results could only be seen after the keyboard closed.

| Before | After |
|----------|--------|
| lf-language-picker-before | lf-language-picker-after |

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/130)

### CODE REVIEW

**Comment by megahirt** [comment]
:lgtm:  as far as code goes.  I'm wondering what the comment edit toolbar looks like now that it's always showing?  So for instance, if there are 10 comments, do you get 10 toolbars?

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/130#-:-KnZoaEmbVSaYAvyYizm:bm9d55q)*

**Comment by Nateowami** [comment]
Yes, one toolbar for each comment. It does look cluttered. I think there's plenty of room for improvement in the comment UI. Here's what it looks like now:

lf-comments

**Comment by megahirt** [comment]
Can you make each comment a bootstrap "card" and see what that looks like?
That might help to separate the controls.  Also, what about moving all
extra functions into a single hotdog menu.  So one hotdog menu per comment,
but then you have the following menu items (as permissions allow):  Mark
Resolved, Mark Todo, Delete Comment.  Reply still gets it's own button at
this point.

On Tue, Jun 27, 2017 at 12:02 PM, Nathaniel Paulus <notifications@github.com

**Comment by Nateowami** [comment]
I think that's a good idea. I'll give it a try. Do you have an example hotdog menu you're thinking of? I looked it up and have seen several styles, though the basic idea remains the same.

**Comment by megahirt** [comment]
The only style I have in my mind is google docs comment style hotdog, but
I'm not picky.

On Tue, Jun 27, 2017 at 10:04 PM, Nathaniel Paulus <notifications@github.com

**Comment by irahopkinson** [comment]
*[src/Site/views/languageforge/theme/default/sass/_global.scss, line 218 at r3](https://reviewable.io:443/reviews/sillsdev/web-languageforge/130#-KngYmecDaolAyfHu-al:-KngYmecDaolAyfHu-am:b-p01z4z) ([raw file](https://github.com/sillsdev/web-languageforge/blob/a226305f49144228b9bc7ac3dc52468585b89432/src/Site/views/languageforge/theme/default/sass/_global.scss#L218)):*
> ```SCSS
> }
> 
> @include media-breakpoint-down(sm) {
> ```

Is there some reason these same media breakpoints aren't combined (what am I missing) ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/130)*

**Comment by irahopkinson** [comment]
BTW we use AirBNB JS style guide (https://github.com/airbnb/javascript). In particular here, anonymous functions and variable declarations. Using PHPStorm with JSCS helps a lot with automating this. In PHP we use PSR2 (http://www.php-fig.org/psr/psr-2/). It will be nice to move to use prettier as pre-commit.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/130#-:-KngcJfJJiJ8YXzlmh0v:b-ck6fas)*

**Comment by Nateowami** [comment]
@irahopkinson Good catch. I think I originally made the Sass changes in a different file and copied them over. I'll combine them.

@megahirt I'm not sure what Google Docs menu you're referring to. This one? 
google docs comments

It's very different from [what I found when I looked up the hotdog menu.](https://www.raizlabs.com/graiz/2016/05/06/no-more-hamburger-menus-introducing-the-hot-dog-menu/)

@irahopkinson Thanks; I've just installed JSCS in VSCode and updated the style to match. Will push it soon.

**Comment by megahirt** [comment]
Sorry to be so vague on the hotdog menu.  Here's the google docs comment hotdog:
image

**Comment by Nateowami** [comment]
Ah, got it.

**Comment by irahopkinson** [comment]
Audio Input System now uses one like that if you want to copy.  You need a field with a file uploaded to see it; in **TestLangProj** select *ɒɾu ɛiɡwɾɛ*, *ken*, *-kes* or *kʰala*.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/130#-:-KnlV5tU_pAHgswouM98:bx1z48b)*

**Comment by megahirt** [comment]
Yes, would be great to keep the same style as the audio input system hotdog menu.

---

Review status: 6 of 17 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/130#-:-KnljB0kwoqVKZPP5xzq:b-hjo60p)*

**Comment by Nateowami** [comment]
@irahopkinson Looking at the ken entry, there's an image uploaded, but I don't see a hotdog menu. I can't find an uploads to the other entries you mention (perhaps I don't have the right project). I'm looking at https://languageforge.org/app/lexicon/57bc1a8f8b21475c24783a11#!/editor/entry/57bc1ab79e76d3a37f4238d3

testlangprojimg

**Comment by Nateowami** [comment]
This is my project's input systems config:

lf_input_systems_ff

The audio input doesn't show up in any of the multitexts. I'm probably skipping some important step, but I'm at a loss as to what it could be.

**Comment by megahirt** [comment]
Adding an audio writing system is step 1.  Step two is adding that audio WS to a field, such as a lexeme form or the definition or whatever.  Let's interact on flowdock if you're still having trouble seeing the audio field.  Here's a screenshot of the audio hotdog menu:
image

**Comment by irahopkinson** [comment]
For the pictures, it doesn't have a hotdog menu (because its a list of pictures, not a single picture). Scroll a bit further to click **Add Picture**.

lf picture image holder 2017-07-13 10-59-22

**Comment by Nateowami** [comment]
@megahirt Here's what I have so far. I'm trying to move quickly so it will be ready in time to ship, but also trying to make something semi-decent.

I haven't run the tests; I'm sure they'll fail because I've changed how the UI works. Once we're happy enough with the UI I'll update the tests. There's still an overlap issue with the replies dropdown menus being covered by the next menu button. It looks like a quick z-index fix, but [there's actually a lot more to stacking,](https://philipwalton.com/articles/what-no-one-told-you-about-z-index/) and I haven't comprehended it.

comment-lf-new

Looking for feedback so I can quickly get it to a shippable state with the tests passing.

**Comment by Nateowami** [comment]
Just pushed an amended commit to fix the stacking issue and remove some commented-out CSS that didn't need to be committed.

**Comment by Nateowami** [comment]
I'm mostly done with the comments view, so it's ready for further review. There's still lots of room for improvement, but it's shippable (unless there are bugs I'm not aware of). Tests are basically passing (by which I mean the only consistent failures are the select tags on the user profile page--due to an Angular update).

Known issue (preexisting): Images and audio selected as what the comment is regarding are rendered as a URL, rather than the image itself, or an audio player. I'm planning to look into that, but I don't think it needs to hold up the rest of the changes.

**Comment by megahirt** [comment]
Just reading your description and seeing the screenshots, this is a big
improvement.  I'm happy.  Will do a full review on Monday/Tuesday.  Thanks!

**Comment by irahopkinson** [comment]
BTW you can get rid of the caret in the ellipsis button by using the attribute `pui-no-caret`. The ellipsis says **more** the same way the caret does so the caret is redundant

**Comment by irahopkinson** [comment]
As in the screen shot above, its a bit weird to have only one item in the **more** menu. Its better to have just the **Delete** button to replace the **more** menu when it is the only item. It does add more HTML but is a better UX. I did this for the audio upload if you want an example.

**Comment by irahopkinson** [comment]
Its a bit clunky to have 3 scroll bars (left panel, right panel, page). In the edit view I removed the scroll bar from the right panel (the working panel) and just rely on the page scroll bar for that. I think that would be appropriate here also. From the class `commentListView` remove **overflow-y** and **height**.

**Comment by irahopkinson** [comment]
That last one off course is an existing issue but an easy fix since your adjusting that code anyway. In general your UI is a great step forward. Good job.

**Comment by Nateowami** [comment]
@irahopkinson 
- Good point about the caret being redundant. I'm pushing changes to remove it.
- The existence of only one menu item is due to a bug which was fixed in a later commit. I'm not aware of any situation in which one can delete a comment but not edit it, but maybe there are some. Is e.g. an admin allowed to delete another user's comments, but not edit them? I'm guessing it's an impossible state. The screenshot would have made it look otherwise though.
- I'd wondered about the scroll bars. I'm removing both the the right and the left one. If you think the left one should remain I can put it back in, but it looks right to me.

I've merged master and all e2e tests are passing.

**Comment by megahirt** [comment]
:lgtm:  This is long running and @nateowami has addressed all the issues I'm aware of.  Merging.

---

Reviewed 1 of 4 files at r2, 2 of 5 files at r3, 8 of 8 files at r5, 2 of 4 files at r7, 4 of 5 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/130#-:-KpNYloBttlSosgNktjN:b-oshzmq)*

**Pull request merged**
