### PR TITLE
WIP: e2e-test for login page.

### PR DESCRIPTION
**Pull request by Arun86Sekar**
* Update the E2E tests to use the new Angular Login page.

 * Add a test that checks that a user can login by pressing the Enter key (rather than the Login button)

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/513)

### CODE REVIEW

**Comment by Arun86Sekar** [comment]
___
*[src/SIL.XForge.Scripture/ClientApp/e2e/src/login.po.ts, line 24 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/513#-LVFKHQxE71zKPUQLezw:-LVJZXIDAfx-S_HWgCJr:b-drs9i6) ([raw file](https://github.com/sillsdev/web-languageforge/blob/a4d9591acabb35c1d0168f7b51fbec3cda86d78f/src/SIL.XForge.Scripture/ClientApp/e2e/src/login.po.ts#L24)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

Your overall solution is good. No need to write an extra method. Changing the parameter `event?: string` to `event?: 'EnterKeyPress'` will  prevent clients from passing some unsupported string, like `'MouseClick'`, which would do the wrong thing with the current implementation. So after you make this one change, I approve your pull request.
</blockquote></details>

Okay, Thanks Hasso.

**Comment by Arun86Sekar** [comment]
___
*[src/SIL.XForge.Scripture/ClientApp/e2e/src/login.po.ts, line 9 at r4](https://reviewable.io/reviews/sillsdev/web-languageforge/513#-LVhXstD558Grw6vP5Zf:-LVlgFPD2usZCtAl-HaJ:bf28k9c) ([raw file](https://github.com/sillsdev/web-languageforge/blob/e56205007c8f31a2ef694d9712075e04a575a170/src/SIL.XForge.Scripture/ClientApp/e2e/src/login.po.ts#L9)):*
<details><summary><i>Previously, Arun86Sekar wrote…</i></summary><blockquote>

Okay, I have done this. Thanks.
Two ID's are displayed on UI when I set Id for username field, and the driver finds two elements when I find the element with id, So again I have used cssselector to find the ID of username.
</blockquote></details>

**Comment by Arun86Sekar** [comment]
___
*[src/SIL.XForge.Scripture/ClientApp/e2e/src/login.po.ts, line 10 at r4](https://reviewable.io/reviews/sillsdev/web-languageforge/513#-LVhY9lT6dRqke2c4MT4:-LVlgzh-AvP7CmPw5giX:bgka3lu) ([raw file](https://github.com/sillsdev/web-languageforge/blob/e56205007c8f31a2ef694d9712075e04a575a170/src/SIL.XForge.Scripture/ClientApp/e2e/src/login.po.ts#L10)):*
<details><summary><i>Previously, Arun86Sekar wrote…</i></summary><blockquote>

Okay, I have done this. Thanks.
Two ID's are displayed on UI when I set Id for password field, and the driver finds two elements when I find the element with id, So again I have used cssselector to find the ID of password.
</blockquote></details>

**Comment by Arun86Sekar** [comment]
___
*[src/SIL.XForge.Scripture/ClientApp/e2e/src/login.po.ts, line 36 at r4](https://reviewable.io/reviews/sillsdev/web-languageforge/513#-LVhW0gq7YtBjO8SB63H:-LVljTNSE--3vXvcCiJ1:b6mb39c) ([raw file](https://github.com/sillsdev/web-languageforge/blob/e56205007c8f31a2ef694d9712075e04a575a170/src/SIL.XForge.Scripture/ClientApp/e2e/src/login.po.ts#L36)):*
<details><summary><i>Previously, Arun86Sekar wrote…</i></summary><blockquote>

Yes, It takes 6 seconds to load the elements and I have also checked in two machines, It remains the same. It seems a performance issue because we could not run the e2e test with 3 seconds.
</blockquote></details>

**Comment by irahopkinson** [comment]
Yes, the `App` tests are all passing but not all the other E2E tests are passing yet. Keep going and make another PR. Move SF-134 back to `In Progress`; its complete when all E2E tests are passing.

**Comment by Arun86Sekar** [comment]
Okay Ira, we will work on SF-134 to make passing all other e2e tests.

**Pull request merged**
