### PR TITLE
fix peer dependency issue with ajv

### PR DESCRIPTION
**Pull request by megahirt**
## Description

update ajv to 8.11.0 (npm dependency).  This solves the peer dependency issue seen when doing a fresh npm install:

```
npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @apideck/better-ajv-errors@0.3.3
npm WARN Found: ajv@6.12.6
npm WARN node_modules/ajv
npm WARN   dev ajv@"^6.10.0" from the root project
npm WARN   9 more (ajv-keywords, schema-utils, schema-utils, schema-utils, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer ajv@">=8" from @apideck/better-ajv-errors@0.3.3
npm WARN node_modules/@apideck/better-ajv-errors
npm WARN   @apideck/better-ajv-errors@"^0.3.1" from workbox-build@6.5.1
npm WARN   node_modules/workbox-build
npm WARN 
npm WARN Conflicting peer dependency: ajv@8.11.0
npm WARN node_modules/ajv
npm WARN   peer ajv@">=8" from @apideck/better-ajv-errors@0.3.3
npm WARN   node_modules/@apideck/better-ajv-errors
npm WARN     @apideck/better-ajv-errors@"^0.3.1" from workbox-build@6.5.1
npm WARN     node_modules/workbox-build
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
```

🧹 Also a bit of housekeeping: deleted a deprecated vscode extension recommendation: debugger-for-chrome

Fixes # (issue)

### Type of Change

Only keep lines below that describe this change, then delete the rest.

- Bug fix (non-breaking change which fixes an issue)

## Testing on your branch

Please describe how to test and/or verify your changes. Provide instructions so we can reproduce.  Please also provide relevant test data as necessary.  These instructions will be used for QA testing below.

- [ ] `npm install` no longer has this error or requires you to use --legacy-deps

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have reviewed the title/description of this PR which will be used as the squashed PR commit message
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by longrunningprocess** [comment]
I tested this locally (on my m1) and got the following:

```
~/projects/sil/lsdev/web-languageforge (bugfix/peerDepAjv*) » npm i                                                                                                                      neowannabe@toybox
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: extract-text-webpack-plugin@4.0.0-beta.0
npm ERR! Found: webpack@5.27.1
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"5.27.1" from the root project
npm ERR!   peer webpack@"4.x.x || 5.x.x" from @webpack-cli/configtest@1.0.2
npm ERR!   node_modules/@webpack-cli/configtest
npm ERR!     @webpack-cli/configtest@"^1.0.2" from webpack-cli@4.6.0
npm ERR!     node_modules/webpack-cli
npm ERR!       dev webpack-cli@"^4.5.0" from the root project
npm ERR!       3 more (@webpack-cli/configtest, @webpack-cli/info, @webpack-cli/serve)
npm ERR!   14 more (copy-webpack-plugin, css-loader, file-loader, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^3.0.0 || ^4.0.0" from extract-text-webpack-plugin@4.0.0-beta.0
npm ERR! node_modules/extract-text-webpack-plugin
npm ERR!   dev extract-text-webpack-plugin@"^4.0.0-beta.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: webpack@4.46.0
npm ERR! node_modules/webpack
npm ERR!   peer webpack@"^3.0.0 || ^4.0.0" from extract-text-webpack-plugin@4.0.0-beta.0
npm ERR!   node_modules/extract-text-webpack-plugin
npm ERR!     dev extract-text-webpack-plugin@"^4.0.0-beta.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```


```sh
 npm --version
8.12.1
```

**Comment by longrunningprocess** [comment]
I tried doing things in `node:latest` without a `platform` flag (which would target `arm64` on my machine)

```sh
docker run --rm --volume $PWD/package.json:/package.json node npm i                                                        neowannabe@toybox
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: web-languageforge@1.0.0
npm ERR! Found: webpack@5.27.1
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"5.27.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^3.0.0 || ^4.0.0" from extract-text-webpack-plugin@4.0.0-beta.0
npm ERR! node_modules/extract-text-webpack-plugin
npm ERR!   dev extract-text-webpack-plugin@"^4.0.0-beta.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-25T16_45_26_086Z-debug-0.log
```

when I targeted Intel, I saw the same thing:

```sh
docker run --platform linux/amd64 --rm --volume $PWD/package.json:/package.json node npm i                             1 ↵ neowannabe@toybox
Unable to find image 'node:latest' locally
latest: Pulling from library/node
1671565cc8df: Pull complete 
3e94d13e55e7: Pull complete 
fa9c7528c685: Pull complete 
53ad072f9cd1: Pull complete 
d6b983117533: Pull complete 
eac9917c3316: Pull complete 
56b8d2414e53: Pull complete 
8342b6d78d6f: Pull complete 
52437043774d: Pull complete 
Digest: sha256:a0a2fc4435b0c9ae7bec0a69b1279323a4a41c5a005581fbf30d39cd5777db37
Status: Downloaded newer image for node:latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: web-languageforge@1.0.0
npm ERR! Found: webpack@5.27.1
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"5.27.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^3.0.0 || ^4.0.0" from extract-text-webpack-plugin@4.0.0-beta.0
npm ERR! node_modules/extract-text-webpack-plugin
npm ERR!   dev extract-text-webpack-plugin@"^4.0.0-beta.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-25T16_47_16_233Z-debug-0.log
```

**Comment by megahirt** [comment]
Thank you so much for this help!  With your testing, I realized that our
package -lock file has issues and I'm going to delete and recreate it.
This PR doesn't address the webpack issue, just the Ajv one.  Your testing
didn't show that error because you didn't copy in the package -lock file.

**Comment by longrunningprocess** [comment]
> Thank you so much for this help! With your testing, I realized that our package -lock file has issues and I'm going to delete and recreate it. This PR doesn't address the webpack issue, just the Ajv one. Your testing didn't show that error because you didn't copy in the package -lock file.

wonderful, I'm glad that was helpful

**Comment by megahirt** [comment]
UPDATE

Once I saw Billy's repro above, I realized that this ajv dependency problem only exists in our current package-lock.json file.  If we delete the package-lock.json file and allow npm to recreate it, this dependency problem goes away.

With old lock file:
image

After deleting the lock file:
image

(there is still a webpack conflict which must be resolved - different PR)

I am closing this PR as no longer relevant.  Will instead tackle the webpack error.

**Pull request closed without merging**
