### PR TITLE
updated error message about FLEx support

### LINKED ISSUE #1625: bug: outdated message about FLEx support
**Describe the bug**
An error message shows reporting the latest supported version of FLEx is 8.2 but it's actually supposed to be 9 now.

**To Reproduce**

Try to import a project from an unsupported version of FLEx

**Expected behavior**
The message should simply let the user know the project version is not currently supported

**Additional context**

https://github.com/sillsdev/web-languageforge/blob/47bb3acbc07baeb2db47d62aa126749d6c8974fc/src/angular-app/languageforge/lexicon/core/lexicon-send-receive.service.ts#L137

### PR DESCRIPTION
**Pull request by longrunningprocess**
Fixes #1625 

## Description

This PR simply updates an outdated compatibility message

### Type of Change

- Bug fix (non-breaking change which fixes an issue)

## Screenshots

N/A

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have reviewed the title & description of this PR which I will use as the squashed PR commit message
- [x] I have enabled auto-merge (optional)

## How to test

- somehow or another, find a project on LD that is older than 9.0 and try to import it.

## qa.languageforge.org testing

Testers should add his/her findings to end of the PR in a comment and include screenshots, files, etc that are beneficial.

### CODE REVIEW

**Review by megahirt — APPROVED** [review]
LGTM

**Comment by myieye** [comment]
My impression is we should publish this without testing it in QA 😬.

**Comment by longrunningprocess** [comment]
it occurred to me that we have our prod data in qa now and this issue was originally related to the `mgb-ib-flex` so maybe trying to S/R that one would do the job.  I think any project whose model version is '7000070' would also work.  I suspect a way to determine that model version might be to do a little searching across plans in language depot for QA.

**Comment by megahirt** [comment]
When I went to test this on QA, the mgb-ib-flex project was already created and already synced, so perhaps this was not the right project?  Or maybe it was already upgraded, I'm not sure.  In any case, I'm happy to mark this as approved/tested as we are just looking at a content change.

**Pull request merged**
