### PR TITLE
WIP: OAuth signup and login forms in a single page

### PR DESCRIPTION
**Pull request by rmunn**
Should be ready for review. There may be security concerns in exposing the `check_unique_identity` function without a login, but I couldn't think of any other way to manage the "This username is taken" field in the OAuth signup page. That's something to discuss during the review.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/173)

### CODE REVIEW

**Comment by megahirt** [comment]
:lgtm: I approve with comments.  Also, would be good to include a screenshot in the PR since I can't actually see the UI without checking the branch out and viewing it locally, which is somewhat separate from the PR process.  I know this is both code review and UI review, but is still something easy to include.

---

Reviewed 15 of 15 files at r1.
Review status: 12 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/angular-app/bellows/apps/public/oauth-signup/oauth-signup-app.module.ts, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/173#-L-UZdZT7oLNdDk8Eti1:-L-UZdZT7oLNdDk8Eti2:b321aj5) ([raw file](https://github.com/sillsdev/web-languageforge/blob/cefcdaad6141552ed3f7b959bccfa10fd06b7a2a/src/angular-app/bellows/apps/public/oauth-signup/oauth-signup-app.module.ts#L13)):*
> ```XML
> 
> 
> /*
> ```

we can get rid of the commented out code here

---

*[src/Api/Model/Shared/Command/UserCommands.php, line 417 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/173#-L-VMRLXWENJ0D-2biUX:-L-VMRLXWENJ0D-2biUY:b-eyd456) ([raw file](https://github.com/sillsdev/web-languageforge/blob/cefcdaad6141552ed3f7b959bccfa10fd06b7a2a/src/Api/Model/Shared/Command/UserCommands.php#L417)):*
> ```PHP
>      * Public: Register a new user and activate them if they already exist on a new site.
>      *
>      * @param array $params (email, name, password, captcha)
> ```

remove password and captcha from comment

---

*[src/Site/Controller/Auth.php, line 58 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/173#-L-VVhjxpninKSeJygWK:-L-VVhjxpninKSeJygWL:b-km3xpb) ([raw file](https://github.com/sillsdev/web-languageforge/blob/cefcdaad6141552ed3f7b959bccfa10fd06b7a2a/src/Site/Controller/Auth.php#L58)):*
> ```PHP
>                 $this->setupAngularAppVariables($app, $appName);
>                 $this->setupAuthView($request, $app);
>                 if ($appName === 'oauth-signup') {
> ```

could this block be moved inside the case: 'oauth-signup' ?

---

*[src/Site/Controller/Auth.php, line 192 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/173#-L-VW4Kgl5xHL53ghVqu:-L-VW4Kgl5xHL53ghVqv:b7lljpa) ([raw file](https://github.com/sillsdev/web-languageforge/blob/cefcdaad6141552ed3f7b959bccfa10fd06b7a2a/src/Site/Controller/Auth.php#L192)):*
> ```PHP
>         $roles = AuthUserProvider::getSiteRoles($userModel, $app['website']);
>         $userWithId = new UserWithId($userModel->username, '', $userModel->username, $roles);
>         $authToken = new UsernamePasswordToken($userWithId, '', 'site', $userWithId->getRoles());
> ```

I don't believe I've seen the UsernamePasswordToken() class before.  Is this how the login is implemented in Silex internally?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/173#-:-L-VWaRk_e_X19RefeiF:b-ewu97n)*

**Comment by rmunn** [comment]
Review status: 12 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/angular-app/bellows/apps/public/oauth-signup/oauth-signup-app.module.ts, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/173#-L-UZdZT7oLNdDk8Eti1:-L-WmLYP3YorovN73lJp:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/cefcdaad6141552ed3f7b959bccfa10fd06b7a2a/src/angular-app/bellows/apps/public/oauth-signup/oauth-signup-app.module.ts#L13)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

we can get rid of the commented out code here
</blockquote></details>

Done.

---

*[src/Api/Model/Shared/Command/UserCommands.php, line 417 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/173#-L-VMRLXWENJ0D-2biUX:-L-WmEPvniHIsSpRRVTe:bhy9ot6) ([raw file](https://github.com/sillsdev/web-languageforge/blob/cefcdaad6141552ed3f7b959bccfa10fd06b7a2a/src/Api/Model/Shared/Command/UserCommands.php#L417)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

remove password and captcha from comment
</blockquote></details>

Will do.

---

*[src/Site/Controller/Auth.php, line 58 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/173#-L-VVhjxpninKSeJygWK:-L-WkyGI1vEq66orhFh4:b-ht429a) ([raw file](https://github.com/sillsdev/web-languageforge/blob/cefcdaad6141552ed3f7b959bccfa10fd06b7a2a/src/Site/Controller/Auth.php#L58)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

could this block be moved inside the case: 'oauth-signup' ?
</blockquote></details>

Not without duplicating code. I tried it multiple ways, and this was the best one. The `oauth-signup` case needs to do all the same things as the other cases except for setting up the OAuth view, which needs to happen in the middle. I could put the `oauth-signup` case first and let it fall through to the other cases, except that the `reset_password` case is also falling through. The other alternative would be to use a `goto` statement to jump from the `oauth-signup` case to the default case, except that it would turn into *multiple* goto statements because I still need to *not* call the `removeOAuthData` function. Overall, this solution was the one that made the least mess; all the other ways to do it would have turned into spaghetti code.

---

*[src/Site/Controller/Auth.php, line 192 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/173#-L-VW4Kgl5xHL53ghVqu:-L-Wm1WAzTLIB7ETKZ2U:b-cso1su) ([raw file](https://github.com/sillsdev/web-languageforge/blob/cefcdaad6141552ed3f7b959bccfa10fd06b7a2a/src/Site/Controller/Auth.php#L192)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

I don't believe I've seen the UsernamePasswordToken() class before.  Is this how the login is implemented in Silex internally?
</blockquote></details>

Yes; if you chase down the Silex internals this is what ends up happening in a post-auth-success service.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/173)*

**Comment by rmunn** [comment]
BTW, here's a screenshot of the UI:

image

**Comment by rmunn** [comment]
Made changes after code review, and used Github's editor to resolve the one conflict since I was curious what it would do (the answer is that it merged the master branch into this one). Since this has been approved pending the edits that I just made, I'm merging it in so we can start testing on the dev server.

**Pull request merged**
