### PR TITLE
Apex/theme lexicon

### PR DESCRIPTION
**Pull request by nigel-wells**
Adjusted the Lexicon list/edit view header area as per UxPin design

**Trello Card:**
https://trello.com/c/3fANSbtT/1106-update-to-lexicon-header-area

**New design for words in dictionary**
image

image

**Added label for the entry preview area**
image

For mobile I decided best to just hide the words in dictionary off the edit view as it was too clumbsy to get it working well with the current search/filtering option setup. Mobile users can use the back to list button to get the words which works fine. Ideally, once the search keyword filter is merged in with the options filter, then this panel could be a slide in panel from the left.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/198)

### CODE REVIEW

**Comment by irahopkinson** [comment]
None of my comments are show stoppers but would be good to fix up if possible. :lgtm: 

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/angular-app/bellows/directive/typeahead.js, line 68 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6rvli-m1P7U_Em1UCD:-L6rvli-m1P7U_Em1UCE:bvpc94k) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/bellows/directive/typeahead.js#L68)):*
> ```JavaScript
> 
>       link: function (scope, element, attrs, controller) {
>         var $input = element.find('#typeaheadInput');
> ```

This assumes there is only one typeahead component on the page. Possibly an ok assumption for now?

---

*[src/angular-app/languageforge/lexicon/editor/editor-entry.html, line 11 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6rwToD2wpKxpmAfvSt:-L6rwToD2wpKxpmAfvSu:bdhr9ux) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/languageforge/lexicon/editor/editor-entry.html#L11)):*
> ```HTML
>                             <div class="words-container-title list-group-item list-group-item-action active">
>                                 <div>
>                                     <h5>{{ 'Words in dictionary' | translate }}</h5>
> ```

Don't use the `translate` filter any more. Localization is done a different way now. Change to `<h5>Words in dictionary</h5>`. Here and elsewhere. Same for `translate` attribute. Whenever I touch a file I've been clearing these out through the whole file.

---

*[src/angular-app/languageforge/lexicon/editor/field/_dc-rendered.scss, line 6 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6ryUqOl0je60p2B8MM:-L6ryUqOl0je60p2B8MN:b4t6j64) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/languageforge/lexicon/editor/field/_dc-rendered.scss#L6)):*
> ```SCSS
>     font-size: 24px;
>   }
>   .dc-rendered-word {
> ```

I read in a best practice somewhere that just because you can nest doesn't mean you should. I'm no SCSS guru but wonder if the previous un-nested specificity was enough?

---

*[src/angular-app/languageforge/lexicon/editor/field/dc-rendered.html, line 2 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6rykPEsfL2BuhYjFCo:-L6rykPEsfL2BuhYjFCp:brh2ec3) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/languageforge/lexicon/editor/field/dc-rendered.html#L2)):*
> ```HTML
> <div class="dc-rendered-entryContainer" ng-hide="hideIfEmpty && !entry.word">
>     <h3 data-ng-show="$state.is('editor.entry')">Entry Preview</h3>
> ```

It might be convenient to have this here but I wonder if this doesn't fit the scope of `dc-rendered`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-:-L6rzI7wu3zgwnPURwWL:b-7c129q)*

**Comment by nigel-wells** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/angular-app/bellows/directive/typeahead.js, line 68 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6rvli-m1P7U_Em1UCD:-L6sLnJEQdcVrhC1zD0Y:b-21koz) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/bellows/directive/typeahead.js#L68)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This assumes there is only one typeahead component on the page. Possibly an ok assumption for now?
</blockquote></details>

Yes it does though technically it will still work as it is only looking for that ID in the context of the parent element. A class is preferable - guess I was shy from changing too much as I don't know everywhere it is in use across all your projects. Happy to change if it is only setup on LF at the moment.

---

*[src/angular-app/languageforge/lexicon/editor/editor-entry.html, line 11 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6rwToD2wpKxpmAfvSt:-L6sMGGIyfHeLAB1oW_A:bkk3w0u) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/languageforge/lexicon/editor/editor-entry.html#L11)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Don't use the `translate` filter any more. Localization is done a different way now. Change to `<h5>Words in dictionary</h5>`. Here and elsewhere. Same for `translate` attribute. Whenever I touch a file I've been clearing these out through the whole file.
</blockquote></details>

Good to know, I'll also start removing that wherever I come across it in code now as well.

---

*[src/angular-app/languageforge/lexicon/editor/field/_dc-rendered.scss, line 6 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6ryUqOl0je60p2B8MM:-L6sMTcJA_hUwpG-pVUQ:b-al47hb) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/languageforge/lexicon/editor/field/_dc-rendered.scss#L6)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I read in a best practice somewhere that just because you can nest doesn't mean you should. I'm no SCSS guru but wonder if the previous un-nested specificity was enough?
</blockquote></details>

The main reason I nest as it makes it much more readable to other developers as well as avoiding any unwanted inheritance. What I've found going through all the SCSS to date is it is obvious multiple developers are working on the code as some elements are referenced in multiple files when it really should all be contained in the one spot. I'm sure some of that is the nature of just doing pure CSS before but there are the nice advantages of using nesting this way to keep stuff in context.

---

*[src/angular-app/languageforge/lexicon/editor/field/dc-rendered.html, line 2 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6rykPEsfL2BuhYjFCo:-L6sNBs8T096WmlqZao3:bb0c00z) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/languageforge/lexicon/editor/field/dc-rendered.html#L2)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

It might be convenient to have this here but I wonder if this doesn't fit the scope of `dc-rendered`?
</blockquote></details>

The rendered control appears on the list and entry views. Would you prefer I set an attribute to show/hide rather than checking the current state?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198)*

**Comment by irahopkinson** [comment]
I changed to your branch but SCSS is not building (during `./refreshDeps`). I get this error:
```
[16:19:28] {
  "status": 1,
  "file": "/home/ira/src/xForge/web-languageforge/src/angular-app/bellows/directive/palaso.ui.comments.lex-comments-view.scss",
  "line": 10,
  "column": 10,
  "message": "Undefined variable: \"$Eden\".",
  "formatted": "Error: Undefined variable: \"$Eden\".\n        on line 10 of src/angular-app/bellows/directive/palaso.ui.comments.lex-comments-view.scss\n>>   color: $Eden;\n   ---------^\n"
}
```

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/angular-app/bellows/directive/typeahead.js, line 68 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6rvli-m1P7U_Em1UCD:-L6tC597CTOu8ITUr1te:b3xh4xf) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/bellows/directive/typeahead.js#L68)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Yes it does though technically it will still work as it is only looking for that ID in the context of the parent element. A class is preferable - guess I was shy from changing too much as I don't know everywhere it is in use across all your projects. Happy to change if it is only setup on LF at the moment.
</blockquote></details>

I haven't been able to think of anywhere we use it more than once on a page nor a case where we might. Leave as is.

---

*[src/angular-app/languageforge/lexicon/editor/editor-entry.html, line 11 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6rwToD2wpKxpmAfvSt:-L6tGh1fLhXzEKB3FcS4:busch0x) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/languageforge/lexicon/editor/editor-entry.html#L11)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Good to know, I'll also start removing that wherever I come across it in code now as well.
</blockquote></details>

Will you fix in this PR or leave it? Also note to remove usage of `$filter('translate')` in JS/TS as well. I posted this in slack here https://sil-language-software.slack.com/archives/C8049CA90/p1519701395000103 a week ago.

---

*[src/angular-app/languageforge/lexicon/editor/field/_dc-rendered.scss, line 6 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6ryUqOl0je60p2B8MM:-L6tCz59rW6QKI0Iimpl:biyaymw) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/languageforge/lexicon/editor/field/_dc-rendered.scss#L6)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

The main reason I nest as it makes it much more readable to other developers as well as avoiding any unwanted inheritance. What I've found going through all the SCSS to date is it is obvious multiple developers are working on the code as some elements are referenced in multiple files when it really should all be contained in the one spot. I'm sure some of that is the nature of just doing pure CSS before but there are the nice advantages of using nesting this way to keep stuff in context.
</blockquote></details>

Yeah I hear you. Our CSS was changed to SCSS by renaming the file extension not by re-thinking in the new ways or gathering appropriate pieces together. Of course SCSS still doesn't require a developer to put stuff in the right place rather then the first convenient place they find. Leave as is.

---

*[src/angular-app/languageforge/lexicon/editor/field/dc-rendered.html, line 2 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6rykPEsfL2BuhYjFCo:-L6tKdMSWV4pNMFAYO-Q:bo6649n) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/languageforge/lexicon/editor/field/dc-rendered.html#L2)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

The rendered control appears on the list and entry views. Would you prefer I set an attribute to show/hide rather than checking the current state?
</blockquote></details>

I would suggest making this H3 an older sibling of `dc-rendered` rather than its child in the entry view then its in the right scope and you don't need to check `$state` at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-:-L6tLt332yU5ws_Mcnza:b-lltrwm)*

**Comment by nigel-wells** [comment]
You're right, after trying to run `./refreshDeps` it now breaks the SCSS. The reason for the break is I moved all the colour variables I had setup in to, what I thought was, the a global variables file called`_variables.scss`. Typically when I'm building sites I have a parent like that which then imports all the relevant scss files it needs. Am I right in thinking that the setup for this takes each scss file at face value and each file needs to import what it needs to run correctly? If that is case then can you confirm if there is a global scss file I can use for variables as the file in the error above is in bellows which means its used for both LF & SF doesn't it? The `_vaiables.scss` file I moved my variables in to is a LF specific file and I suspect you'd prefer me not to reference that from a file in the bellows directory?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/angular-app/languageforge/lexicon/editor/editor-entry.html, line 11 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6rwToD2wpKxpmAfvSt:-L6wn7m06x28V2vmiHlq:bu49lpv) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/languageforge/lexicon/editor/editor-entry.html#L11)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Will you fix in this PR or leave it? Also note to remove usage of `$filter('translate')` in JS/TS as well. I posted this in slack here https://sil-language-software.slack.com/archives/C8049CA90/p1519701395000103 a week ago.
</blockquote></details>

I'll update this PR to remove those filters.

---

*[src/angular-app/languageforge/lexicon/editor/field/dc-rendered.html, line 2 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L6rykPEsfL2BuhYjFCo:-L6wqx5x_y1OXYwSwVDh:bb6un1j) ([raw file](https://github.com/sillsdev/web-languageforge/blob/dcc578749e099f5ef8df4323038f26cb1feb5cdf/src/angular-app/languageforge/lexicon/editor/field/dc-rendered.html#L2)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I would suggest making this H3 an older sibling of `dc-rendered` rather than its child in the entry view then its in the right scope and you don't need to check `$state` at all.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-:-L6wveYvcxfdfpfzX7Z7:bqeo2x0)*

**Comment by irahopkinson** [comment]
> palaso.ui.comments.lex-comments-view.scss

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-:-L6y8sLHLsTZoLr8hOw1:b-hs6lc9)*

**Comment by irahopkinson** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-:-L6yMDNFGruyQ_d35mUB:bnfp4nl)*

**Comment by megahirt** [comment]
:lgtm:

---

Reviewed 4 of 11 files at r1, 6 of 7 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/angular-app/languageforge/lexicon/editor/editor-entry.html, line 101 at r3](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L72eOu6uMfF9wQhRk__:-L72eOu6uMfF9wQhRk_a:bchxrr3) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5b92c8e9003c925cc25e854c80292f02ad87a4b1/src/angular-app/languageforge/lexicon/editor/editor-entry.html#L101)):*
> ```HTML
>             <div class="col-md-7 col-lg-8 entry-primary-container">
>                 <div class="word-definition-title">
>                     <h3>Entry Preview</h3>
> ```

I can't remember if this was something that was in the original UXPin, but at first glance I don't really like the existence of this label.  I'm fine letting it through at this time though to see if I get used to it.  It mostly seems unnecessary to me.  It may get deleted though :)  FLEx users certainly understand what they are seeing without having the label.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-:-L72fEIkmK4RYYofVCfH:bnfp4nl)*

**Comment by nigel-wells** [comment]
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/angular-app/languageforge/lexicon/editor/editor-entry.html, line 101 at r3](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L72eOu6uMfF9wQhRk__:-L7S-q6LrUnxnrPx4TCZ:bgzewgl) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5b92c8e9003c925cc25e854c80292f02ad87a4b1/src/angular-app/languageforge/lexicon/editor/editor-entry.html#L101)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

I can't remember if this was something that was in the original UXPin, but at first glance I don't really like the existence of this label.  I'm fine letting it through at this time though to see if I get used to it.  It mostly seems unnecessary to me.  It may get deleted though :)  FLEx users certainly understand what they are seeing without having the label.
</blockquote></details>

Yep it was there. It isn't as bad now with the adjustment of the words in dictionary panel. For all of us looking at the app with fresh eyes that "Entry Preview" text appeared to be floating up there and it was difficult to know what it was or how it was related to anything else on the screen. Giving it a title helped to give it some purpose and a little explanation as to what it was. If all your users (current and new) know what it is then it could probably be done away with.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198)*

**Comment by nigel-wells** [comment]
All resolved now @megahirt. I made one further tweak to the list view to make it look better when there are no entries in a project yet.

**Comment by megahirt** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/angular-app/languageforge/lexicon/editor/editor-entry.html, line 101 at r3](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-L72eOu6uMfF9wQhRk__:-L7S0nDKpKn5gEjqDOx2:bkg23f) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5b92c8e9003c925cc25e854c80292f02ad87a4b1/src/angular-app/languageforge/lexicon/editor/editor-entry.html#L101)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Yep it was there. It isn't as bad now with the adjustment of the words in dictionary panel. For all of us looking at the app with fresh eyes that "Entry Preview" text appeared to be floating up there and it was difficult to know what it was or how it was related to anything else on the screen. Giving it a title helped to give it some purpose and a little explanation as to what it was. If all your users (current and new) know what it is then it could probably be done away with.
</blockquote></details>

ok cool.  thanks for explaining.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/198#-:-L7S0lbhLX5HkOSuegNe:bnfp4nl)*

**Pull request merged**
