### PR TITLE
[Ansible] Add cronjob for lfmergeqm

### PR DESCRIPTION
**Pull request by ermshiperete**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/340)

### CODE REVIEW

**Comment by rmunn** [comment]
I could have sworn we already have this cron job set up somewhere. Maybe in a different Ansible repo; I'll check.

**Comment by ermshiperete** [comment]
yep, it's in the ops-ansible-sites repo.

**Comment by megahirt** [comment]
And is it also deployed and functional on production?  Tested?

**Comment by rmunn** [comment]
@megahirt - I know the cron job is deployed on production, because I see its effects in the LfMerge logs: every twenty minutes I see an LfMerge process (now it's `lfmergeqm`) start up, log the fact that the queue is empty and there's nothing to do, and go to sleep again.

**Pull request closed without merging**
