### PR TITLE
fix SF user profile list settings not persisting

### PR DESCRIPTION
**Pull request by irahopkinson**
- add regression E2E tests
- remove readonly restriction on 'userProperties'
- fix pick list editor submitting forms (change <button> to <a>)
- some general tidy-up in changed files

Note: `projectSettings.js` changes are all non-functional tidy-up changes.

This is in response to a user reported error: https://community.scripture.software.sil.org/t/how-to-access-and-display-user-profiles/451

SF E2E tests passing.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/289)

### CODE REVIEW

**Comment by Nateowami** [comment]
All the e2e tests (except those that already normally fail for me) are passing. :lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

---

*[src/angular-app/bellows/directive/picklist-editor.html, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/289#-LFI33Jn9zLUnyUusWPt:-LFI33Jn9zLUnyUusWPu:b-uxm4wk) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d3d59e29d115b74aae9ac1e33cb27ae5b566d132/src/angular-app/bellows/directive/picklist-editor.html#L4)):*
> ```HTML
>     <div data-ng-show="showDefault">
>         <label for="default-select">Default Value</label>
>         <select class="custom-select" id="default-select" data-ng-model="defaultKey"
> ```

Are we guaranteed to have no more than one picklist-editor on a page?

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/289#-:-LFIOM2I4BRiZTm0VSQV:b-pjycfi)*

**Comment by irahopkinson** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

---

*[src/angular-app/bellows/directive/picklist-editor.html, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/289#-LFI33Jn9zLUnyUusWPt:-LFJj8GY0yO-g_nseZKx:b-dghu45) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d3d59e29d115b74aae9ac1e33cb27ae5b566d132/src/angular-app/bellows/directive/picklist-editor.html#L4)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Are we guaranteed to have no more than one picklist-editor on a page?
</blockquote></details>

No, but we do for now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/289)*

**Comment by Nateowami** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[src/angular-app/bellows/directive/picklist-editor.html, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/289#-LFI33Jn9zLUnyUusWPt:-LFJkQDt3mS2TgR6MUV_:b-ix5jny) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d3d59e29d115b74aae9ac1e33cb27ae5b566d132/src/angular-app/bellows/directive/picklist-editor.html#L4)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

No, but we do for now.
</blockquote></details>

OK. I just wondered because in the past we've had conflicts with multiple components using the same ID.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/289)*

**Comment by irahopkinson** [comment]
Review status: 7 of 8 files reviewed, all discussions resolved (waiting on @Nateowami)

---

*[src/angular-app/bellows/directive/picklist-editor.html, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/289#-LFI33Jn9zLUnyUusWPt:-LFJlgYW1GFit4gdaUTa:b1brdj2) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d3d59e29d115b74aae9ac1e33cb27ae5b566d132/src/angular-app/bellows/directive/picklist-editor.html#L4)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

OK. I just wondered because in the past we've had conflicts with multiple components using the same ID.
</blockquote></details>

Yeah, I re-thought after I posted. Have reverted now. Thanx

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/289)*

**Comment by Nateowami** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[src/angular-app/bellows/directive/picklist-editor.html, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/289#-LFI33Jn9zLUnyUusWPt:-LFJmvC_8BH3edYhlC8c:b-h9b0fh) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d3d59e29d115b74aae9ac1e33cb27ae5b566d132/src/angular-app/bellows/directive/picklist-editor.html#L4)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yeah, I re-thought after I posted. Have reverted now. Thanx
</blockquote></details>

Another way to make the label be for an input is to just wrap the input with the label tag. That affects layout though, so it's not always desirable, and I'm guessing this would be one of those cases.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/289)*

**Pull request merged**
