### PR TITLE
improved delete and move UX on entry, meaning and examples

### LINKED ISSUE #1537: feat: Better UI for deleting entries
**Is your feature request related to a problem? Please describe.**
How to delete an entry from Language Forge is not obvious. A user had to ask how to do that (answer: use the three dots at the top right of the editing area). 

**Describe the solution you'd like**
Trash can symbol or red X symbol, visible (not in the three dots) for Entry, Meaning, and Example. These should display on mobile.

**Describe alternatives you've considered**
What we already have

### PR DESCRIPTION
**Pull request by longrunningprocess**
Fixes #1537 

## Description

This PR changes the UI in accordance with some developer observations of users struggling with how to perform some activities on their dictionary entries.

### Type of Change

- UI change

### Entry 

image

### Meaning

image

image

image

### Example

image

### Tooltips

https://user-images.githubusercontent.com/4412848/200657385-8f6fcc8b-527f-41e7-9bea-0a8c76dec26c.mov

### Mobile

looks good but I do demonstrate the widely-known issue of hover behavior on mobile devices... we can either live with it, consider bringing popper or some other 3rd-party lib in, remove the tooltips entirely or utilize more javascript to isolate hovers to appropriate devices.

https://user-images.githubusercontent.com/4412848/200659475-dff5cb87-8371-4e8a-9d11-3fd6ea6a634c.mov

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have reviewed the title/description of this PR which will be used as the squashed PR commit message
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works

## How to test

Please describe how to test and/or verify your changes. Provide instructions so we can reproduce. Please also provide relevant test data as necessary. These instructions will be used for QA testing below.

- Add an entry, hover over it ensuring the tooltip content is correct and ensure the entry is actually deleted
- Add a few meanings, hover over the movement and delete icons ensuring the tooltip content is correct and ensure the meaning is actually moved and/or deleted
- Add a few examples, hover over the movement and delete icons ensuring the tooltip content is correct and ensure the example is actually moved and/or deleted

## qa.languageforge.org testing

Testers should add his/her findings to end of the PR in a comment and include screenshots, files, etc that are beneficial.

### CODE REVIEW

**Comment by longrunningprocess** [comment]
I'm moving this back to draft... I'm not happy with the current solution and did not hear back about whether we could simply eliminate it or not.

**Comment by longrunningprocess** [comment]
after discussing at stand-up today, we've decide to eliminate the tooltips altogether.  We will also go with just the icons, no extra text to turn on and off based on the viewport since we believe the icons are pretty universally clear.

**Review by megahirt — APPROVED** [review]
Great - thank you for this!

I did look up the title= attribute as a cheap tooltip and MDN says it still works:

https://developer.mozilla.org/en-US/docs/web/html/global_attributes/title

but has "accessibility concerns"

I personally think that adding a title attribute / tooltip on the up down arrows is a cheap win and only adds value for those not using a touch interface.

**Comment by longrunningprocess** [comment]
> Great - thank you for this!
> 
> I did look up the title= attribute as a cheap tooltip and MDN says it still works:
> 
> https://developer.mozilla.org/en-US/docs/web/html/global_attributes/title
> 
> but has "accessibility concerns"
> 
> I personally think that adding a title attribute / tooltip on the up down arrows is a cheap win and only adds value for those not using a touch interface.

Have you tried it?  I don't think it works anymore...

**Comment by longrunningprocess** [comment]
yeah, doesn't work for me in Chrome, works improperly in Safari and works as expected in FireFox and Edge

**Comment by megahirt** [comment]
> yeah, doesn't work for me in Chrome, works improperly in Safari and works as expected in FireFox and Edge

So I tried it just now and works as expected for me in Chrome, Safari and Edge on Mac.  https://www.w3schools.com/TAGS/tryit.asp?filename=tryhtml5_global_title
(apologies for the W3schools link - yuck)

When I suggested `title=` as a cheap win, I was referring to the fact that we have nothing right now, so even if it only works for some users (not mobile/touch), that is better than what we have right now, which is no tooltip, with no immediate plans to change that.

**Comment by laineyhm** [comment]
image

Delete and move icons are readily visible and working as expected to delete entries/meanings/examples and move meanings/examples. 

* In the (delete) chicken page, I recommend that we add a question mark to the end of the question "Are you sure you want to delete the entry ______"

**Pull request merged**
