### PR TITLE
Feature/e2e tests docker

### PR DESCRIPTION
**Pull request by megahirt**
This isn't ready to merge yet because there are a bunch of broken tests, and increases the number of broken PHP tests.  We'll call this mergable when I get the PHP tests fixed up that were previously working.

In summary:

E2E tests are running in Docker!  I'm amazed.  I feel like my docker-compose setup is pretty solid but feel free to give it a critique.

HOW TO RUN: `docker-compose run e2e-ui`

Here's a screenshot showing VNC peeking into a selenium docker container running the e2e tests.
image

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/827)

### CODE REVIEW

**Review by longrunningprocess — COMMENTED** [review]
> Reviewed 34 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/827)* status: all files reviewed, 14 unresolved discussions (waiting on @megahirt)

___
*[gulpfile.js, line 674 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg29aU4pOWMqk0YxoO:-MTg29aU4pOWMqk0YxoP:b-8hu1cc) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/gulpfile.js#L674)):*
> ```JavaScript
>   var specString = (params.specs) ? params.specs : '*';
>   var specs = [
>     "test/app/allspecs/**/*.e2e-spec.js",
> ```

this is where your value really shines, knowing how to make this change!!!  :trophy: 
___
*[gulpfile.js, line 1259 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg204b0Sn1EPY71lXQ:-MTg204b0Sn1EPY71lXR:bvm5l00) ([raw file](https://github.com/sillsdev/web-languageforge/blob/ba13722f48ed402b1fb8590c6a852aafdf66d43d/gulpfile.js#L1259)):*
> ```JavaScript
>     'test-php',
>     'test-ts',
>     'test-restart-webserver'
> ```

dude, the clean up in this whole file is a beauty!
___
*[rune2e.sh, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg3UQl9PrnHxfEHWKf:-MTg3UQl9PrnHxfEHWKg:b-qaz5s4) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/rune2e.sh#L31)):*
> ```Shell
> attach_debugger &
> gulp test-e2e-clean-compile
> gulp test-e2e-doTest --webserverHost e2e ${@:2}
> ```

so nice being able to refer to the container that way!
___
*[docker/docker-compose.yml, line 98 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg3nru0VdBrBiD8VXi:-MTg3nru0VdBrBiD8VXj:b5yy2tf) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/docker-compose.yml#L98)):*
> ```YAML
>   #   volumes:
>   #     - lfmerge-data:/var/lib/languageforge
> ```

doesn't get much cleaner than that, well done folding this work into Docker!
___
*[docker/docker-compose.yml, line 105 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg43Ug7j1duuCXEDc6:-MTg43Ug7j1duuCXEDc7:b5nexb9) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/docker-compose.yml#L105)):*
> ```YAML
>       - "e2e-api:e2e"
>     volumes:
>       - /dev/shm:/dev/shm
> ```

not sure how you figured this one out but nice detective work!
___
*[docker/api/Dockerfile, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg4DcN089aCbKYTGW5:-MTg4DcN089aCbKYTGW6:b-skjlj7) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/api/Dockerfile#L31)):*
> ```Dockerfile
>     WAIT_HOSTS=db:27017,mail:25 \
>     WAIT_HOSTS_TIMEOUT=300 \
>     WAIT_SLEEP_INTERVAL=2 \
> ```

you are the speedracer :fast_forward: 
___
*[docker/e2e-api/Dockerfile, line 1 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg4Lxr18-dO3BaV7Z1:-MTg4Lxr18-dO3BaV7Z2:b-mzjn4z) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/e2e-api/Dockerfile#L1)):*
> ```Dockerfile
> FROM lf-api:latest
> ```

you don't have to pin this one to `latest` unless you want to be explicit
___
*[docker/e2e-api/Dockerfile, line 8 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg4d2-6Kn0mMRz7lAO:-MTg4d2-6Kn0mMRz7lAP:bp5nhmy) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/e2e-api/Dockerfile#L8)):*
> ```Dockerfile
> COPY test /var/www/test/
> RUN ln -s /var/www/html /var/www/src
> RUN cp /var/www/src/config.php.fortest /var/www/src/config.php
> ```

`COPY` wouldn't work here?
___
*[docker/e2e-ui/Dockerfile, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg4p590ZZtLveEcQSp:-MTg4p590ZZtLveEcQSq:b-jhdgk4) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/e2e-ui/Dockerfile#L10)):*
> ```Dockerfile
> COPY test/ /data/test/
> 
> # Add docker-compose-wait tool -------------------
> ```

not critical but these lines would be better above the `COPY`'s for the sake of layer caching
___
*[src/Api/Library/Shared/Website.php, line 87 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg5CRd13GQxGVDt24Y:-MTg5CRd13GQxGVDt24Z:bgewn2z) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/src/Api/Library/Shared/Website.php#L87)):*
> ```PHP
>     }
> 
>     private static function getHostname()
> ```

excellent!  I wonder if you could simply get rid of this function definition altogether and replace with the `localhost`?
___
*[test/app/protractorConf.js, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg5heV35dICSRUiPuY:-MTg5heV35dICSRUiPuZ:b-a2dwvx) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/test/app/protractorConf.js#L4)):*
> ```JavaScript
> exports.config = {
>   // The address of a running selenium server.
>   seleniumAddress: 'http://selenium:4444/wd/hub',
> ```

interesting...`4444` isn't explicitly exposed in the `docker-compose.yml`, I might not expect this to work unless the ports are coming from a parent `Dockerfile`
___
*[test/app/setupTestEnvironment.php, line 428 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg5xtK1PQ3V9mgBkHD:-MTg5xtK1PQ3V9mgBkHE:bsn7pzw) ([raw file](https://github.com/sillsdev/web-languageforge/blob/ba13722f48ed402b1fb8590c6a852aafdf66d43d/test/app/setupTestEnvironment.php#L428)):*
> ```PHP
>         $website
>     );
> }
> ```

YES!  The fastest and most error-free code we write is the code we don't write!  So basically you just eliminated bugs and performance issues, nice work :ice_cream: 
___
*[test/common/MongoTestEnvironment.php, line 107 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg6OcV2LTonbNC7WUK:-MTg6OcV2LTonbNC7WUL:b-d44yj2) ([raw file](https://github.com/sillsdev/web-languageforge/blob/ba13722f48ed402b1fb8590c6a852aafdf66d43d/test/common/MongoTestEnvironment.php#L107)):*
> ```PHP
>         if ($appName != '') {
>             $projectModel->appName = $appName;
>         }  else if ($this->website->base == Website::SCRIPTUREFORGE) {
> ```

too bad we don't have historical info on the complexity of this entire codebase before and after, talk about a seriously GREAT story!
___
*[test/php/model/shared/commands/ProjectCommandsTest.php, line 363 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg6ePv4YLwYAjORTiF:-MTg6ePv4YLwYAjORTiG:bd9rh8g) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/test/php/model/shared/commands/ProjectCommandsTest.php#L363)):*
> ```PHP
>             $user1->id->asString(), self::$environ->website);
> 
>         $project = new LexProjectModel($projectId);
> ```

priceless work here, you were def the right guy for the job here :-)

**Review by megahirt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/827)* status: all files reviewed, 14 unresolved discussions (waiting on @longrunningprocess)

___
*[gulpfile.js, line 674 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg29aU4pOWMqk0YxoO:-MTh7_la2ADGXfIvbRFC:b-o2lju4) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/gulpfile.js#L674)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

this is where your value really shines, knowing how to make this change!!!  :trophy: 
</blockquote></details>

thanks :)  I haven't tested whether doing the specString format will still work after the change, but I don't care that much at this point.
___
*[gulpfile.js, line 1259 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg204b0Sn1EPY71lXQ:-MTh7ke6C5m3mBnAbWin:bte8rux) ([raw file](https://github.com/sillsdev/web-languageforge/blob/ba13722f48ed402b1fb8590c6a852aafdf66d43d/gulpfile.js#L1259)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

dude, the clean up in this whole file is a beauty!
</blockquote></details>

yeah, trying to restart apache from the ui container, um, isn't going to fly.  Just removed it.
___
*[rune2e.sh, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg3UQl9PrnHxfEHWKf:-MTh7s5iBzIGCriVQsYe:b-jlbpkz) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/rune2e.sh#L31)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

so nice being able to refer to the container that way!
</blockquote></details>

yeah, this was actually a little confusing because of the way things actually worked.  I needed a name for the container that *wasn't* localhost, since localhost is a special network reserve word referring to "self".   The commands are generated on the ui container, sent to the selenium container with the browser, which are accessed on the api container, and then results reported back on the ui container.  So in this case, "e2e" actually refers to the e2e-api container.
___
*[docker/docker-compose.yml, line 98 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg3nru0VdBrBiD8VXi:-MTh8U0q7vT4D65E7ktb:b-43r8o0) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/docker-compose.yml#L98)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

doesn't get much cleaner than that, well done folding this work into Docker!
</blockquote></details>

thanks!  Here's a summary:

the "-debug" selenium image includes VNC so you can see what the browser is actually doing instead of trying to debug selenium/protractor errors (horrible).  I used this once already and it saved me a bunch of time.

the "e2e-api:e2e" is a network alias

the "/dev/shm volume" is recommended by the selenium container - otherwise the browser may crash under certain scenarios.  I didn't experience this but just went with their advice on their [github quickstart readme](https://github.com/SeleniumHQ/docker-selenium#quick-start).
___
*[docker/docker-compose.yml, line 105 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg43Ug7j1duuCXEDc6:-MTh96e31XTzY6E1NmXp:bbw4h2b) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/docker-compose.yml#L105)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

not sure how you figured this one out but nice detective work!
</blockquote></details>

see above.
___
*[docker/api/Dockerfile, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg4DcN089aCbKYTGW5:-MTh9gHh2MZKfChjcT4U:b-xyi25i) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/api/Dockerfile#L31)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

you are the speedracer :fast_forward: 
</blockquote></details>

just couldn't be bothered waiting that long :)
___
*[docker/e2e-api/Dockerfile, line 1 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg4Lxr18-dO3BaV7Z1:-MTh9jjI98r5QTmaWfMa:b69aro7) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/e2e-api/Dockerfile#L1)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

you don't have to pin this one to `latest` unless you want to be explicit
</blockquote></details>

ok good point, I will change this.
___
*[docker/e2e-api/Dockerfile, line 8 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg4d2-6Kn0mMRz7lAO:-MTh9niIAM2hU6GLaDyx:b-30jm4e) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/e2e-api/Dockerfile#L8)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

`COPY` wouldn't work here?
</blockquote></details>

I suppose it would.  I was mostly mimicking what is done as part of the gulp "set config to test task".  
___
*[docker/e2e-ui/Dockerfile, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg4p590ZZtLveEcQSp:-MThA90dCy3l7sANX86C:b-yt5a59) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/e2e-ui/Dockerfile#L10)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

not critical but these lines would be better above the `COPY`'s for the sake of layer caching
</blockquote></details>

ok that's a good idea.  Will do.  FYI once I get this PR in I was going to ask you to do some magic/reorganization on the Docker files especially regarding COPY and volume mappings.  I repent of not having all the source code COPY'd in whereas some files are only volume mapped.  I get it now.  I'm still fine with volume mapping critical files, but we shouldn't have any files that are necessary that are *only* volume mapped.

On another note, I'm not sure what to do about running the PHP tests - the /test/ directory isn't COPY'ed into the image, but it is volume mapped in the docker-compose for the api container, but those aren't needed for the application.  I was wondering if we could move the volume map for the tests to the Makefile?  Either that or I'd rather have another Dockerfile for a test container.  I know you removed that earlier, but it actually seems cleaner to me to have these concerns separated, even if it means an additional Dockerfile.
___
*[src/Api/Library/Shared/Website.php, line 87 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg5CRd13GQxGVDt24Y:-MThBb9uAORbJUOSQq61:bhqxtqd) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/src/Api/Library/Shared/Website.php#L87)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

excellent!  I wonder if you could simply get rid of this function definition altogether and replace with the `localhost`?
</blockquote></details>

yeah, this is a super hack.  Just wanted to get things running.  A proper fix will include removing all usage of the Website class.  Unfortunately, it's pretty much everywhere.
___
*[test/app/protractorConf.js, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg5heV35dICSRUiPuY:-MThBnkr9CaXKvHNq1Yy:bsd0djo) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/test/app/protractorConf.js#L4)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

interesting...`4444` isn't explicitly exposed in the `docker-compose.yml`, I might not expect this to work unless the ports are coming from a parent `Dockerfile`
</blockquote></details>

yes, the selenium containers expose 4444 on the internal docker network from their own Dockerfile.  We don't need to expose it to the host however.
___
*[test/app/setupTestEnvironment.php, line 428 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg5xtK1PQ3V9mgBkHD:-MThC27p7IHojvldUyhy:b-y4bxbs) ([raw file](https://github.com/sillsdev/web-languageforge/blob/ba13722f48ed402b1fb8590c6a852aafdf66d43d/test/app/setupTestEnvironment.php#L428)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

YES!  The fastest and most error-free code we write is the code we don't write!  So basically you just eliminated bugs and performance issues, nice work :ice_cream: 
</blockquote></details>

yeah :)  I cherry-picked a commit from my cleanup branch and this came along for the ride.
___
*[test/common/MongoTestEnvironment.php, line 107 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg6OcV2LTonbNC7WUK:-MThDMkdBGocYHAeS-k_:bb7hc1j) ([raw file](https://github.com/sillsdev/web-languageforge/blob/ba13722f48ed402b1fb8590c6a852aafdf66d43d/test/common/MongoTestEnvironment.php#L107)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

too bad we don't have historical info on the complexity of this entire codebase before and after, talk about a seriously GREAT story!
</blockquote></details>

haha
___
*[test/php/model/shared/commands/ProjectCommandsTest.php, line 363 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg6ePv4YLwYAjORTiF:-MThDSV6CcIttPeXdm0O:b-1bjpmn) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/test/php/model/shared/commands/ProjectCommandsTest.php#L363)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

priceless work here, you were def the right guy for the job here :-)
</blockquote></details>

thanks :)

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/827)* status: all files reviewed, 6 unresolved discussions (waiting on @megahirt)

___
*[rune2e.sh, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg3UQl9PrnHxfEHWKf:-MTkSK7E1pAd9b94PXwr:b-7htpx4) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/rune2e.sh#L31)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

yeah, this was actually a little confusing because of the way things actually worked.  I needed a name for the container that *wasn't* localhost, since localhost is a special network reserve word referring to "self".   The commands are generated on the ui container, sent to the selenium container with the browser, which are accessed on the api container, and then results reported back on the ui container.  So in this case, "e2e" actually refers to the e2e-api container.
</blockquote></details>

that's a lot of plumbing, glad you found a way through!
___
*[docker/docker-compose.yml, line 98 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg3nru0VdBrBiD8VXi:-MTkST5REAmFaW5lTQsT:bsh1gg0) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/docker-compose.yml#L98)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

thanks!  Here's a summary:

the "-debug" selenium image includes VNC so you can see what the browser is actually doing instead of trying to debug selenium/protractor errors (horrible).  I used this once already and it saved me a bunch of time.

the "e2e-api:e2e" is a network alias

the "/dev/shm volume" is recommended by the selenium container - otherwise the browser may crash under certain scenarios.  I didn't experience this but just went with their advice on their [github quickstart readme](https://github.com/SeleniumHQ/docker-selenium#quick-start).
</blockquote></details>

I've never used the network alias, cool to a real use for it.
___
*[docker/api/Dockerfile, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg4DcN089aCbKYTGW5:-MTkSZYO4EsBbHeYEpbL:b-aa2u4z) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/api/Dockerfile#L31)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

just couldn't be bothered waiting that long :)
</blockquote></details>

no, that's a lifetime for a CPU
___
*[docker/e2e-ui/Dockerfile, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg4p590ZZtLveEcQSp:-MTkSprv8yxIkM0oToT3:b-czb51t) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/e2e-ui/Dockerfile#L10)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

ok that's a good idea.  Will do.  FYI once I get this PR in I was going to ask you to do some magic/reorganization on the Docker files especially regarding COPY and volume mappings.  I repent of not having all the source code COPY'd in whereas some files are only volume mapped.  I get it now.  I'm still fine with volume mapping critical files, but we shouldn't have any files that are necessary that are *only* volume mapped.

On another note, I'm not sure what to do about running the PHP tests - the /test/ directory isn't COPY'ed into the image, but it is volume mapped in the docker-compose for the api container, but those aren't needed for the application.  I was wondering if we could move the volume map for the tests to the Makefile?  Either that or I'd rather have another Dockerfile for a test container.  I know you removed that earlier, but it actually seems cleaner to me to have these concerns separated, even if it means an additional Dockerfile.


</blockquote></details>

agreed on the COPY vs `volume`.  I think of it this way, I only volume map things I intend to be working on for development (most of the time).  Sometimes I might volume something in if I don't have the Dockerfile and need to drop a customization in the container, that's more of a convenience technique.

regarding the php tests, I'm def with you on the idea of getting those files out of the application that are only there to make the tests work...I think another image makes sense since we need to essentially take the api image and then inject our test-related files/dependencies for testing.
___
*[src/Api/Library/Shared/Website.php, line 87 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg5CRd13GQxGVDt24Y:-MTkTfNr5VPuXM_v0FOP:bh2c79q) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/src/Api/Library/Shared/Website.php#L87)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

yeah, this is a super hack.  Just wanted to get things running.  A proper fix will include removing all usage of the Website class.  Unfortunately, it's pretty much everywhere.
</blockquote></details>

gotcha, I suspected something like that.
___
*[test/app/protractorConf.js, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg5heV35dICSRUiPuY:-MTkTjyt83A-qXEBHQSU:b-gn6a68) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/test/app/protractorConf.js#L4)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

yes, the selenium containers expose 4444 on the internal docker network from their own Dockerfile.  We don't need to expose it to the host however.
</blockquote></details>

makes sense.

**Comment by megahirt** [comment]
This is not mergeable until @rmunn is able to fix up master with a working application state.

However, I have the e2e tests down to 16 failures out of 388, and this is a real accomplishment.  Most of the errors are related to "element not clickable" for mock upload buttons, which I suspect don't work in the latest version of Chrome.

Here's the full e2e run output:
```
**************************************************
*                    Failures                    *
**************************************************

1) Bellows E2E Page Traversal Explore reset password page
  - Failed: No element found using locator: by.model("$ctrl.record.password")

2) Bellows E2E Project Settings app Manager can delete if owner
  - Expected 4 to be 3.

3) Lexicon E2E Editor List and Entry can delete audio Input System
  - Expected false to be true.

4) Lexicon E2E Editor List and Entry file upload drop box is displayed when Upload is clicked
  - Expected false to be true.
  - Failed: element not interactable
    (Session info: chrome=88.0.4324.96)
  Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
  System info: host: '19fcc07ece34', ip: '192.168.16.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.128-microsoft-standard', java.version: '1.8.0_275'
  Driver info: driver.version: unknown

5) Lexicon E2E Editor List and Entry file upload drop box is not displayed when Cancel Uploading Audio is clicked
  - Expected false to be true.
  - Failed: element not interactable
    (Session info: chrome=88.0.4324.96)
  Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
  System info: host: '19fcc07ece34', ip: '192.168.16.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.128-microsoft-standard', java.version: '1.8.0_275'
  Driver info: driver.version: unknown

6) Lexicon E2E Editor List and Entry Mock file upload can't upload a non-audio file
  - Expected 1 to be 0.
  - Failed: element not interactable
    (Session info: chrome=88.0.4324.96)
  Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
  System info: host: '19fcc07ece34', ip: '192.168.16.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.128-microsoft-standard', java.version: '1.8.0_275'
  Driver info: driver.version: unknown

7) Lexicon E2E Editor List and Entry Mock file upload can upload an audio file
  - Expected 1 to be 0.
  - Failed: element not interactable
    (Session info: chrome=88.0.4324.96)
  Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
  System info: host: '19fcc07ece34', ip: '192.168.16.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.128-microsoft-standard', java.version: '1.8.0_275'
  Driver info: driver.version: unknown

8) Lexicon E2E New Project wizard app Send Receive Verify page can clone project
  - Failed: Wait timed out after 3014ms

9) Lexicon E2E New Project wizard app Send Receive Verify page cannot move on while cloning
  - Expected true to be false.
  - Expected true to be false.

10) Lexicon E2E New Project wizard app Initial Data page with upload Mock file upload cannot upload large file
  - Expected 1 to be 0.
  - Expected 2 to be 1.
  - Expected '×
  Close
  Oh. Exception
  Click for details' to contain 'is too large. It must be smaller than'.

11) Lexicon E2E New Project wizard app Initial Data page with upload Mock file upload cannot upload jpg
  - Expected 1 to be 0.
  - Expected 2 to be 1.
  - Expected '×
  Close

  TestLexProject.zip (128.0 MB) is too large. It must be smaller than 60.0 MB.' to contain 'TestImage.jpg is not an allowed compressed file. Ensure the file is'.
  - Expected '

  Browser Console JS Error:
  http://e2e/upload/lf-lexicon/import-zip - Failed to load resource: the server responded with a status of 403 (Forbidden)

  ' to equal ''.
  - Expected '

  Browser Console JS Error:
  http://e2e/dist/vendor.bundle.js?v=9.9.9 38576:40 "Error: undefined (reported to Bugsnag)"

  ' to equal ''.

12) Lexicon E2E New Project wizard app Initial Data page with upload Mock file upload can upload zip file
  - Expected 1 to be 0.
  - Failed: No element found using locator: By(css selector, *[id="entries-imported"])
  - Expected '

  Browser Console JS Error:
  http://e2e/upload/lf-lexicon/import-zip - Failed to load resource: the server responded with a status of 403 (Forbidden)

  ' to equal ''.
  - Expected '

  Browser Console JS Error:
  http://e2e/dist/vendor.bundle.js?v=9.9.9 38576:40 "Error: undefined (reported to Bugsnag)"

  ' to equal ''.

13) Lexicon E2E New Project wizard app Verify Data page displays stats
  - Failed: No element found using locator: By(css selector, *[id="new-project-verify"])

14) Lexicon E2E New Project wizard app Verify Data page displays non-critical errors
  - Expected false to be true.
  - Failed: No element found using locator: By(css selector, *[id="import-errors"])

15) Lexicon E2E New Project wizard app Verify Data page can go to lexicon
  - Expected 'btn ng-binding float-right btn-std' to match /btn-primary(?:\s|$)/.
  - Failed: Wait timed out after 3016ms

16) Lexicon E2E New Project wizard app Primary Language page can go to lexicon and primary language has changed
  - Failed: Wait timed out after 3080ms
  - Expected '

  Browser Console JS Error:
  http://e2e/dist/vendor.bundle.js?v=9.9.9 38576:40 "Error: You don't have sufficient privileges. - Insufficient privileges accessing API method 'lex_configuration_update'"

  ' to equal ''.

Executed 318 of 318 specs (16 FAILED) in 12 mins 2 secs.
```

**Comment by megahirt** [comment]
- PHP tests are all passing (except LF Merge)

image

- E2E tests verified mostly passing (16 failures)

**Review by megahirt — COMMENTED** [review]
> Dismissed @longrunningprocess from 6 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/827)* status: 27 of 65 files reviewed, all discussions resolved (waiting on @longrunningprocess)

___
*[rune2e.sh, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg3UQl9PrnHxfEHWKf:-MUGCHDi88xFObVVSczC:blwosvi) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/rune2e.sh#L31)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

that's a lot of plumbing, glad you found a way through!
</blockquote></details>

yup - good to go
___
*[docker/e2e-ui/Dockerfile, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/827#-MTg4p590ZZtLveEcQSp:-MUGC86T70mRO9hJcyY-:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/6fd83b1195574541989a0090053ba311fe126d22/docker/e2e-ui/Dockerfile#L10)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

agreed on the COPY vs `volume`.  I think of it this way, I only volume map things I intend to be working on for development (most of the time).  Sometimes I might volume something in if I don't have the Dockerfile and need to drop a customization in the container, that's more of a convenience technique.

regarding the php tests, I'm def with you on the idea of getting those files out of the application that are only there to make the tests work...I think another image makes sense since we need to essentially take the api image and then inject our test-related files/dependencies for testing.
</blockquote></details>

Done.

**Review by megahirt — COMMENTED** [review]
> Reviewed 27 of 34 files at r1, 38 of 38 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/827)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
