### PR TITLE
Make corrections to the Vagrant install method

### PR DESCRIPTION
**Pull request by Nateowami**
Yesterday's changes did not fully fix everything. Today's changes:
- Install SF too, not just LF
- Fix a README typo
- Make minor improvements to the Vagrant provisioning script
- Fix two symlink issues experienced by Windows users

The hope is to have this merged in time for the developers in India to use it on Monday. Reviewers who see something that needs to be changed, feel free to make the change directly if that allows it to be merged in time for them to use it.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/276)

### CODE REVIEW

**Comment by irahopkinson** [comment]
:lgtm:
Please add the gist as a MD file to our repo. I'll merge this one now without that tho.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/276#-:-LDz5hidCtwXJMXor9wu:bis2uq9)*

**Comment by Nateowami** [comment]
@irahopkinson OK, will do. Do you want the screenshot in the repo too?

**Comment by irahopkinson** [comment]
@Nateowami Yes, you can put images in the `readme_images` folder.

**Comment by Nateowami** [comment]
Sorry I still haven't gotten to this. Does it need its own Markdown file? To me it seems small enough to go in the README, but the README is getting rather large, so I guess it could go either way.

**Comment by irahopkinson** [comment]
Up to you.

**Pull request merged**
