### PR TITLE
upgraded db container to mongodb 5.0

### LINKED ISSUE #1568: upgrade mongodb to 5.0
**Is your feature request related to a problem? Please describe.**

There is a desire to utilize aggregation pipelines and take advantage of possible perf improvements.

**Additional context**
 see #1567

### PR DESCRIPTION
**Pull request by longrunningprocess**
Fixes #1568 

## Description

This PR upgrades the running versions of mongodb to 5.0

### Type of Change

- database upgrade

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have reviewed the title & description of this PR which I will use as the squashed PR commit message
- [x] I have enabled auto-merge (optional)
- [x] db-deployment.yml has been manually applied to staging

## How to test

- Successful automated tests are a decent indicator of success
- A general smoke test of the app would be further affirming

## qa.languageforge.org testing

Testers should add his/her findings to end of the PR in a comment and include screenshots, files, etc that are beneficial.

### CODE REVIEW

**Review by megahirt — APPROVED** [review]
LGTM

**Comment by longrunningprocess** [comment]
Mind suggesting a project in staging with an input system for audio?  Since I can't create the input system the way I used to I believe I need a project with that input system already in place.  Thanks!

**Comment by longrunningprocess** [comment]
updated prod container manually to 5.0 while waiting for POSO and a release

**Comment by longrunningprocess** [comment]
set compat in staging

image

**Comment by longrunningprocess** [comment]
staging smoke test seems good and db logs upon startup were clean.

**Comment by longrunningprocess** [comment]
set compat in prod

```
> db.adminCommand( { getParameter: 1, featureCompatibilityVersion: 1 } )
{ "featureCompatibilityVersion" : { "version" : "5.0" }, "ok" : 1 }
> 
```

general smoke test of prod seems good and all logs are clean.

**Pull request merged**
