### PR TITLE
Feature/dockerize

### PR DESCRIPTION
**Pull request by megahirt**
This has been a long running development branch to get a dockerized developer environment working for language forge.  While we haven't arrived yet, this branch gets us a long way there.

In this branch:
- docker/docker-compose setup for the following containers:
-- mongodb
-- postfix
-- node ui builder
-- php api back-end
-- php-test container to run php-tests

TODO for a complete developer setup:
- modify README.md to include instructions for starting the environment (`make ssl`)
- modify README.md and remove ansible developer install instructions
- make PHP tests run using docker-compose-wait
- LFMerge container working and tested
- e2e test container for running protractor tests using selenium webdriverJS

After talking with Ira, I decided that this branch is really more of a long running develop branch and not a feature branch.  It contains loads of commits and multiple authors, so we will simply merge it and not worry about a squash/rebase.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/815)

### CODE REVIEW

**Comment by megahirt** [comment]
It should be noted that PHP unit tests are expected to fail, as the teamcity build agent does not understand how to run the php-tests in docker (yet).

**Comment by longrunningprocess** [comment]
I think it's ready, I entirely cleaned my local env and `make` then `make db-reset`.  All the resulting artifacts are gtg and the app let me log in and update my profile, log out, etc...

Certainly there's more work to be done but this approach allows everyone to simply install docker and `make` and they'll be ready to rock within a few minutes.  I know this was a long time goal of yours and it's worthy of being celebrated!  I"m looking forward to our pairing session tonight to put a bow on this.

**Review by megahirt — COMMENTED** [review]
> Reviewed 9 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/815)* status: 9 of 42 files reviewed, 1 unresolved discussion

___
*[gulpfile.js, line 1137 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/815#-MTIiDt71bmLz20AHIPP:-MTIiDt71bmLz20AHIPQ:bvftkws) ([raw file](https://github.com/sillsdev/web-languageforge/blob/8cbe8b30231f0032b3d1b10833faaf79b966ebd5/gulpfile.js#L1137)):*
> ```JavaScript
> // Create WebsiteInstances.php from template
> // ------------------------------------------
> // gulp.task('build-createWebsiteDefsPhp', function () {
> ```

TODO delete these blocks that are already commented out

**Review by megahirt — COMMENTED** [review]
:lgtm: ready to merge

> Reviewed 33 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/815#-:-MTIj-O8DiuTI6UsBXcY:b-n7r5b5)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
