### PR TITLE
Restructured angular app to allow vscode debugging

### PR DESCRIPTION
**Pull request by palmtreefrb**
Needed to make changes to the structure of the angularjs app to allow vscode debugging

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/921)

### CODE REVIEW

**Review by longrunningprocess — CHANGES_REQUESTED** [review]
looked like a bunch of these changes were in another PR as well...I'm good with them as long as they all work but the E2E tests failed so we'll have to take a closer look to see if it's just a flaky test thing or if there's truly an issue.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/921#-:-MYt_6OQDKPTp_9eQ7EP:b65hn26)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @palmtreefrb)

___
*[.vscode/launch.json, line 14 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/921#-MYt_GCX0dV4NrkWUE9k:-MYt_GCX0dV4NrkWUE9l:b-tslusy) ([raw file](https://github.com/sillsdev/web-languageforge/blob/9a206aa9dcbee0f49918e244cf513621fc99827f/.vscode/launch.json#L14)):*
> ```JSON
>       "request": "launch",
>       "name": "Launch Chrome",
>       "url": "http://localhost:8080",
> ```

not sure about this one...that `8080` thing seems like it shouldn't work to me.

**Comment by palmtreefrb** [comment]
> looked like a bunch of these changes were in another PR as well...I'm good with them as long as they all work but the E2E tests failed so we'll have to take a closer look to see if it's just a flaky test thing or if there's truly an issue.
> 
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/921#-:-MYt_6OQDKPTp_9eQ7EP:b65hn26)_ status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @palmtreefrb)
> 
> _[.vscode/launch.json, line 14 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/921#-MYt_GCX0dV4NrkWUE9k:-MYt_GCX0dV4NrkWUE9l:b-tslusy) ([raw file](https://github.com/sillsdev/web-languageforge/blob/9a206aa9dcbee0f49918e244cf513621fc99827f/.vscode/launch.json#L14)):_
> 
> > ```json
> >       "request": "launch",
> >       "name": "Launch Chrome",
> >       "url": "http://localhost:8080",
> > ```
> 
> not sure about this one...that `8080` thing seems like it shouldn't work to me.

This one is not used for the docker launch. I was using it to launch something else during testing. It can be removed.

**Review by longrunningprocess — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/921)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @palmtreefrb)

___
*[.vscode/launch.json, line 14 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/921#-MYt_GCX0dV4NrkWUE9k:-MYte9KB7JOYuCGszHPT:b-eeldke) ([raw file](https://github.com/sillsdev/web-languageforge/blob/9a206aa9dcbee0f49918e244cf513621fc99827f/.vscode/launch.json#L14)):*
<details><summary><i>Previously, palmtreefrb (Rick) wrote…</i></summary><blockquote>

This one is not used for the docker launch. I was using it to launch something else during testing. It can be removed.
</blockquote></details>

gotcha, thanks

**Review by megahirt — COMMENTED** [review]
:lgtm: Rick - I haven't tried it myself but this looks to be masterful work.  Thanks for figuring this out and getting debugging going again.  After this PR it would be great to have step-by-step instructions added to the readme and probably also do a screencast on how to debug the application in VSCode.  It's something I've thought about doing myself but haven't given it priority.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/921#-:-MYtASYt1oBD8CqD4qhG:bnoylzi)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @megahirt and @palmtreefrb)

**Review by megahirt — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/921)* status: all files reviewed, 1 unresolved discussion (waiting on @palmtreefrb)

**Review by longrunningprocess — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/921)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @palmtreefrb)

**Pull request merged**
