### PR TITLE
Chore/migrate bugsnag env

### PR DESCRIPTION
**Pull request by longrunningprocess**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/906)

### CODE REVIEW

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/906)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @longrunningprocess)

___
*[src/Api/Library/Shared/Palaso/Exception/BugsnagExceptionHandler.php, line 22 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/906#-MXcufB93LSgs1LiDIrK:-MXcufB93LSgs1LiDIrL:b-7u9qcj) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b094c1f6b2a25222cf3f752f85d58830985b135b/src/Api/Library/Shared/Palaso/Exception/BugsnagExceptionHandler.php#L22)):*
> ```PHP
>         ];
> 
>         $application['bugsnag']->setNotifyReleaseStages(Env::requireArray('BUGSNAG_NOTIFY_RELEASE_STAGES'));
> ```

I'm not sure I really appreciate the utility of this release stages config...first of all, we don't want to use bugsnag in qa correct?  Additionally the instantiation for this class is being ultimately driven by the `ENVIRONMENT` var...so is this additional config actually doing anything?

**Comment by longrunningprocess** [comment]
don't forget the following after PR is approved:

- [ ]  bump `build-n-publish-images` to appropriate commit
- [ ] add ENV vars to k8s and redeploy

**Review by megahirt — DISMISSED** [review]
Well done!  Really appreciate this consolidation.  I agree with your intuition on the release stage variable.  Let's hard code 'live' and remove the variable.  Fix that up and should be good to go.

> Reviewed 4 of 6 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/906#-:-MY-Fb300UVhDE6kZzRA:b-o5mis)* status: all files reviewed, 3 unresolved discussions (waiting on @longrunningprocess)

___
*[docker/docker-compose.yml, line 44 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/906#-MY-FEK2Bee2lmM5jnQj:-MY-FEK32dzAxz8s8DOP:b-9pv9eg) ([raw file](https://github.com/sillsdev/web-languageforge/blob/97294d541cdb3b683d4b4e458760a9d0cc896400/docker/docker-compose.yml#L44)):*
> ```YAML
>       # - ENVIRONMENT=testing|production
>       # - BUGSNAG_API_KEY=some-key
>       # - BUGSNAG_NOTIFY_RELEASE_STAGES=live,qa
> ```

remove references to the `BUGSNAG_NOTIFY_RELEASE_STAGES` variable
___
*[src/Api/Library/Shared/Palaso/Exception/BugsnagExceptionHandler.php, line 22 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/906#-MXcufB93LSgs1LiDIrK:-MY-EMkZ2dLc4I-bD8a5:b7q2byr) ([raw file](https://github.com/sillsdev/web-languageforge/blob/717f8523f3c9480d62373ce4787571a291e784d4/src/Api/Library/Shared/Palaso/Exception/BugsnagExceptionHandler.php#L22)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

I'm not sure I really appreciate the utility of this release stages config...first of all, we don't want to use bugsnag in qa correct?  Additionally the instantiation for this class is being ultimately driven by the `ENVIRONMENT` var...so is this additional config actually doing anything?
</blockquote></details>

I think that when Bugsnag was originally setup, and before we had really proved any real utility of it, we set it up so that it would trigger on both QA and Production.  After using it and receiving bug reports, I don't see a need to report bugs on anything but production.  I think having a variable for release stage is overkill.  Can we simply hard-code the release stage as `live` and remove references to the `BUGSNAG_NOTIFY_RELEASE_STAGES` variable?
___
*[src/angular-app/bellows/core/exception-handling.service.ts, line 25 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/906#-MY-FOJC5BWHc2EuROeX:-MY-FOJC5BWHc2EuROeY:b-ys5quc) ([raw file](https://github.com/sillsdev/web-languageforge/blob/97294d541cdb3b683d4b4e458760a9d0cc896400/src/angular-app/bellows/core/exception-handling.service.ts#L25)):*
> ```XML
>     this.bugsnagClient = Bugsnag({
>       apiKey: process.env.BUGSNAG_API_KEY,
>       notifyReleaseStages: ['live', 'qa'],
> ```

let's just notify `['live']` thank you

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/906)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @megahirt)

___
*[docker/docker-compose.yml, line 44 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/906#-MY-FEK2Bee2lmM5jnQj:-MY5G0OE2-PN5NuhXMGi:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/97294d541cdb3b683d4b4e458760a9d0cc896400/docker/docker-compose.yml#L44)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

remove references to the `BUGSNAG_NOTIFY_RELEASE_STAGES` variable
</blockquote></details>

Done.
___
*[src/Api/Library/Shared/Palaso/Exception/BugsnagExceptionHandler.php, line 22 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/906#-MXcufB93LSgs1LiDIrK:-MY5FcAz1iLZPHx6UDiG:b-fk5b33) ([raw file](https://github.com/sillsdev/web-languageforge/blob/717f8523f3c9480d62373ce4787571a291e784d4/src/Api/Library/Shared/Palaso/Exception/BugsnagExceptionHandler.php#L22)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

I think that when Bugsnag was originally setup, and before we had really proved any real utility of it, we set it up so that it would trigger on both QA and Production.  After using it and receiving bug reports, I don't see a need to report bugs on anything but production.  I think having a variable for release stage is overkill.  Can we simply hard-code the release stage as `live` and remove references to the `BUGSNAG_NOTIFY_RELEASE_STAGES` variable?
</blockquote></details>

I've gone ahead and done that now.  I see a lot of opportunity here to reduce complexity by eliminating the notion of release stages and it's repeated configuration from the codebase altogether but I'm going to fight the urge to extract it all.  Maybe we can revisit it "one day" ;-)
___
*[src/angular-app/bellows/core/exception-handling.service.ts, line 25 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/906#-MY-FOJC5BWHc2EuROeX:-MY5FaskBq8poUczl8qp:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/97294d541cdb3b683d4b4e458760a9d0cc896400/src/angular-app/bellows/core/exception-handling.service.ts#L25)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

let's just notify `['live']` thank you
</blockquote></details>

Done.

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/906)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @megahirt)

___
*[docker/docker-compose.yml, line 44 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/906#-MY-FEK2Bee2lmM5jnQj:-MY68tN86kIV2hBRq17p:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/97294d541cdb3b683d4b4e458760a9d0cc896400/docker/docker-compose.yml#L44)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[src/angular-app/bellows/core/exception-handling.service.ts, line 25 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/906#-MY-FOJC5BWHc2EuROeX:-MY68wFH6VAwPgtkRU7A:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/97294d541cdb3b683d4b4e458760a9d0cc896400/src/angular-app/bellows/core/exception-handling.service.ts#L25)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by longrunningprocess — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 3 of 5 files at r2, 5 of 5 files at r3.
> Dismissed @megahirt from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/906#-:-MY69mCAE-VeErCYhKaO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @longrunningprocess)

___
*[docker/docker-compose.yml, line 44 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/906#-MY-FEK2Bee2lmM5jnQj:-MY69tss8Vzq74NTv7Bl:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/97294d541cdb3b683d4b4e458760a9d0cc896400/docker/docker-compose.yml#L44)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[src/angular-app/bellows/core/exception-handling.service.ts, line 25 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/906#-MY-FOJC5BWHc2EuROeX:-MY6A0vE-4cy_HdcPo58:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/97294d541cdb3b683d4b4e458760a9d0cc896400/src/angular-app/bellows/core/exception-handling.service.ts#L25)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Pull request merged**
