### PR TITLE
Enable playwright tests in deployment workflow

### PR DESCRIPTION
**Pull request by myieye**
## Description

Playwright tests seem to be pretty stable now, so we can reenable them in the deployment workflow/job.

I removed the browser caching steps with the thought that deployment doesn't run often enough for them to add as much value as they do complexity.

### Type of Change

- New feature (reenabling workflow step)

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have reviewed the title/description of this PR which will be used as the squashed PR commit message
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works

## How to test

Ran the workflow here and the playwright steps are green: https://github.com/sillsdev/web-languageforge/actions/runs/3322471978

### CODE REVIEW

**Comment by myieye** [comment]
Uncovered a flaky test: https://github.com/sillsdev/web-languageforge/actions/runs/3322410002/jobs/5491390263
So, I'll fix that up before merging this.

**Comment by longrunningprocess** [comment]
> Uncovered a flaky test: https://github.com/sillsdev/web-languageforge/actions/runs/3322410002/jobs/5491390263 So, I'll fix that up before merging this.

I just noted this on the other PR, thanks Tim!

**Review by longrunningprocess — APPROVED** [review]

**Review by megahirt — APPROVED** [review]
Looking good!  I'm very happy to see that we are at this point again with E2E tests

**Comment by longrunningprocess** [comment]
# Testing

GTG on `develop` run ✅

**Pull request merged**
