### PR TITLE
Ignore GUIDs and other fields in dictionary search

### PR DESCRIPTION
**Pull request by Nateowami**
Previously searching the dictionary returned results found in GUIDs and other properties not seen by users. Now it ignores many metadata fields that are not visible to users. It's possible there are more properties that I am not aware of, but the blacklist includes everything I've come across so far.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/215)

### CODE REVIEW

**Comment by irahopkinson** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/angular-app/languageforge/lexicon/editor/editor.js, line 907 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215#-L9N3Cbo5uO1-5UlSPVv:-L9N3Cbo5uO1-5UlSPVw:b-1dnmvs) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5f73c466d61264a89efbb23bd55cc298dad548f0/src/angular-app/languageforge/lexicon/editor/editor.js#L907)):*
> ```JavaScript
>           ];
> 
>         var isBlacklisted = function (key) {
> ```

This new function appears to be unused. Does it need to be here?

---

*[src/angular-app/languageforge/lexicon/editor/editor.js, line 922 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215#-L9N5-jR3KqudOGhoZY1:-L9N5-jR3KqudOGhoZY2:b-cg9hid) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5f73c466d61264a89efbb23bd55cc298dad548f0/src/angular-app/languageforge/lexicon/editor/editor.js#L922)):*
> ```JavaScript
>           switch (value == null ? 'null' : typeof value) {
>             // Array.prototype.some tests whether some element satisfies the function
>             case 'object': return Object.keys(value).some(function (key) {
> ```

The object case doesn't appear to test against the `query`. Did I miss somethng?

---

*[src/angular-app/languageforge/lexicon/editor/editor.js, line 930 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215#-L9N3hrr71dCps_NmROz:-L9N3hrr71dCps_NmRP-:b-1hg5f5) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5f73c466d61264a89efbb23bd55cc298dad548f0/src/angular-app/languageforge/lexicon/editor/editor.js#L930)):*
> ```JavaScript
>             case 'boolean': return false;
>             default:
>               console.error('Unexpected type ' + (typeof value) + ' on entry.');
> ```

We've never used `console.error` before. If this is a developer error message (which I suspect it is) then use `throw`. If its a user error then give an appropriate message to the user.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215)*

**Comment by Nateowami** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/angular-app/languageforge/lexicon/editor/editor.js, line 907 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215#-L9N3Cbo5uO1-5UlSPVv:-L9N64kq8IOVzZkhotKN:but8pv2) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5f73c466d61264a89efbb23bd55cc298dad548f0/src/angular-app/languageforge/lexicon/editor/editor.js#L907)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This new function appears to be unused. Does it need to be here?
</blockquote></details>

This was supposed to replace `!blacklistKeys.includes(key)` on line 923, but I apparently forgot to actually use it. Thanks for catching that; I will fix it and push again.

---

*[src/angular-app/languageforge/lexicon/editor/editor.js, line 922 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215#-L9N5-jR3KqudOGhoZY1:-L9N6R6-2vi4G1oDhL_U:b-9k99fg) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5f73c466d61264a89efbb23bd55cc298dad548f0/src/angular-app/languageforge/lexicon/editor/editor.js#L922)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

The object case doesn't appear to test against the `query`. Did I miss somethng?
</blockquote></details>

This is a recursive function, so when it encounters an object it iterates over the keys and calls isMatch (the function we are already in). Only when we reach an actual string value is there anything to compare. The line below is essentially "if the property/key is not blacklisted and property's value is a match."

---

*[src/angular-app/languageforge/lexicon/editor/editor.js, line 930 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215#-L9N3hrr71dCps_NmROz:-L9N6qqHDbyzM7K8eGhH:b-tszs70) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5f73c466d61264a89efbb23bd55cc298dad548f0/src/angular-app/languageforge/lexicon/editor/editor.js#L930)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

We've never used `console.error` before. If this is a developer error message (which I suspect it is) then use `throw`. If its a user error then give an appropriate message to the user.
</blockquote></details>

Thank you; yes this is intended for developers and should never be reached. I'll change it to throw.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215)*

**Comment by Nateowami** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/angular-app/languageforge/lexicon/editor/editor.js, line 930 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215#-L9N3hrr71dCps_NmROz:-L9N7hTk6dcHrvk3jwPb:bg0hq9n) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5f73c466d61264a89efbb23bd55cc298dad548f0/src/angular-app/languageforge/lexicon/editor/editor.js#L930)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Thank you; yes this is intended for developers and should never be reached. I'll change it to throw.
</blockquote></details>

Actually, on second thought, there is a good reason this does not throw. If it did it would break functionality for the user, whereas simply logging the error and saying no match was found allows it to fail gracefully in this unlikely but non-fatal situation. I could just remove the check. The only possible return values for typeof that I have not check for are  `symbol`, `undefined`, `number`, and `function`. `undefined` and `number` are not that improbable though. I'll go ahead and commit a fix for the other issue since I'm not sure what to do with this yet.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215)*

**Comment by irahopkinson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/angular-app/languageforge/lexicon/editor/editor.js, line 930 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215#-L9N3hrr71dCps_NmROz:-L9N9YOf83UxFoyvWI6y:b-3toqcg) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5f73c466d61264a89efbb23bd55cc298dad548f0/src/angular-app/languageforge/lexicon/editor/editor.js#L930)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Actually, on second thought, there is a good reason this does not throw. If it did it would break functionality for the user, whereas simply logging the error and saying no match was found allows it to fail gracefully in this unlikely but non-fatal situation. I could just remove the check. The only possible return values for typeof that I have not check for are  `symbol`, `undefined`, `number`, and `function`. `undefined` and `number` are not that improbable though. I'll go ahead and commit a fix for the other issue since I'm not sure what to do with this yet.
</blockquote></details>

Yes, missed that this is a recursive function; `console.error` might be appropriate.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215)*

**Comment by Nateowami** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/angular-app/languageforge/lexicon/editor/editor.js, line 930 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215#-L9N3hrr71dCps_NmROz:-L9NA_9H3ZU6m01bb51t:b-owizpo) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5f73c466d61264a89efbb23bd55cc298dad548f0/src/angular-app/languageforge/lexicon/editor/editor.js#L930)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yes, missed that this is a recursive function; `console.error` might be appropriate.
</blockquote></details>

`console.error` isn't likely to be seen in production, but for development console errors are likely to be seen (especially since they make the e2e tests fail). I'm running the tests right now and will push when they are complete.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215)*

**Comment by Nateowami** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/angular-app/languageforge/lexicon/editor/editor.js, line 907 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215#-L9N3Cbo5uO1-5UlSPVv:-L9ND3HV9W9REbYQ2QT2:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5f73c466d61264a89efbb23bd55cc298dad548f0/src/angular-app/languageforge/lexicon/editor/editor.js#L907)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This was supposed to replace `!blacklistKeys.includes(key)` on line 923, but I apparently forgot to actually use it. Thanks for catching that; I will fix it and push again.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215)*

**Comment by irahopkinson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215#-:-L9NEi-u1WjO1agq_c65:bnfp4nl)*

**Comment by megahirt** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/215#-:-L9VHn1M1AfM0tb4eRbX:bnfp4nl)*

**Pull request merged**
