### PR TITLE
Feature/bs ui bootstrap

### PR DESCRIPTION
**Pull request by darcywong00**
Update to ui-bootstrap 2.5.0

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/72)

### CODE REVIEW

**Comment by megahirt** [comment]
Reviewed 47 of 47 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html, line 39 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGR7rqw_EnRQrrX4Pz:-KcGR7rqw_EnRQrrX4Q-:b-cqc7kl) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html#L39)):*
> ```HTML
>                                disabled type="email" name="email"
>                                placeholder="{{'your email' | translate}}" data-ng-model="record.email"/>
>                         <span uib-alert class="input-group-addon" data-ng-class="'alert-success'" data-ng-show="!emailExists">
> ```

I'm not sure this is necessary to transform into a uib-alert.  Does the BS4 CSS provide enough here?  e.g. class="alert alert-success"

---

*[src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html, line 65 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGROEsj5pTEn5iTiBd:-KcGROEsj5pTEn5iTiBe:b2ss7xm) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html#L65)):*
> ```HTML
>                                    title="Passwords must be at least 7 characters"
>                                    data-ng-model="record.password"/>
>                             <span uib-alert class="input-group-addon" data-ng-class="'alert-danger'" data-ng-show='record.password && record.password.length < 7'>
> ```

see comment above

---

*[src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html, line 89 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGRRxAMoKG8jQl-Qoo:-KcGRRxAMoKG8jQl-Qop:b2ss7xm) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html#L89)):*
> ```HTML
>                                    title="Passwords must be at least 7 characters"
>                                    data-ng-model="record.password"/>
>                             <span uib-alert class="input-group-addon" data-ng-class="'alert-danger'" data-ng-show='record.password && record.password.length < 7'>
> ```

see comment above

---

*[src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html, line 105 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGRTJWgijrA1VCmnpG:-KcGRTJWgijrA1VCmnpH:b2ss7xm) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html#L105)):*
> ```HTML
>                                    data-ng-disabled="showPassword"
>                                    data-ng-model="confirmPassword"/>
>                             <span uib-alert class="input-group-addon" data-ng-class="'alert-danger'" data-ng-show='record.password && record.password != confirmPassword'>
> ```

see comment above

---

*[src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html, line 108 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGRU2-Lnv9S8e15izF:-KcGRU2-Lnv9S8e15izG:b2ss7xm) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html#L108)):*
> ```HTML
>                                 <i class="fa fa-warning" title="Passwords do not match!"></i>
>                             </span>
>                             <span uib-alert class="input-group-addon" data-ng-class="'alert-success'" data-ng-show='record.password && record.password == confirmPassword'>
> ```

see comment above

---

*[src/angular-app/bellows/apps/usermanagement/bootstrap4/usermanagement.html, line 9 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGRjqtpVqYkAnSa-zA:-KcGRjqtpVqYkAnSa-zB:b6vwfct) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/apps/usermanagement/bootstrap4/usermanagement.html#L9)):*
> ```HTML
> 
>             <a class="btn btn-secondary" ng-href="{{project.appLink}}" uib-tooltip="Back to the project"
>                     tooltip-placement="right">
> ```

wherever possible I would like to preserve the {{interfaceConfig.placementNormal}} and related settings for use when we do UI localization for RTL languages

---

*[src/angular-app/bellows/directive/bootstrap4/palaso.ui.comments.comments-right-panel.html, line 41 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGSbs1UNCW4OQu1Chx:-KcGSbs2SbxcM_Xtu5uS:bh1g22y) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/directive/bootstrap4/palaso.ui.comments.comments-right-panel.html#L41)):*
> ```HTML
>                             </div>
>                         </div>
>                         <div uib-alert ng-hide="newComment.regarding.field" data-ng-class="'alert-warning'"><span data-translate="Click on a field to the left and give context to your comment"></span></div>
> ```

i don't see a reason to make this a uib-alert  I think just leaving it styled as a BS4 class="alert alert-warning" is fine.

---

*[src/angular-app/bellows/directive/bootstrap4/pui-send-receive-credentials.html, line 18 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGSxKQIZXdwq_8TnAm:-KcGSxKQIZXdwq_8TnAn:bo9fsf8) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/directive/bootstrap4/pui-send-receive-credentials.html#L18)):*
> ```HTML
>                             <i id="usernameLoading" class="fa fa-spinner fa-spin" ></i>
>                         </span>
>                         <span uib-alert class="input-group-addon" data-ng-class="'alert-success'" data-ng-show="puiProject.sendReceive.username.length > 0 && puiProject.sendReceive.credentialsStatus == 'valid'">
> ```

same as previous comments

---

*[src/angular-app/bellows/directive/bootstrap4/pui-send-receive-credentials.html, line 46 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGT-KD8YTvS2Svp28B:-KcGT-KEttTMegLdKrRF:bo9fsf8) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/directive/bootstrap4/pui-send-receive-credentials.html#L46)):*
> ```HTML
>                             <i id="passwordLoading" class="fa fa-spinner fa-spin"></i>
>                         </span>
>                         <span uib-alert class="input-group-addon" data-ng-class="'alert-success'" data-ng-show="puiProject.sendReceive.password.length > 0 && puiProject.sendReceive.credentialsStatus == 'valid'">
> ```

same as previous comments

---

*[src/angular-app/bellows/directive/bootstrap4/pui-send-receive-credentials.html, line 52 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGT3NMAeVZAXRaW4jd:-KcGT3NMAeVZAXRaW4je:bo9fsf8) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/directive/bootstrap4/pui-send-receive-credentials.html#L52)):*
> ```HTML
>                 </div>
>             </div>
>             <div uib-alert data-ng-class="'alert-danger'"
> ```

same as previous comments

---

*[src/angular-app/languageforge/lexicon/new-project/views/new-project-name.html, line 31 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGTOulmgEYn6l6WlSI:-KcGTOulmgEYn6l6WlSJ:bo9fsf8) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/languageforge/lexicon/new-project/views/new-project-name.html#L31)):*
> ```HTML
>                                     <i id="projectCodeAlphanumeric" class="fa fa-times" title="Project Code must begin with a letter, and only contain lower-case letters, numbers, dashes and underscores!" ></i>
>                                 </span>
>                                 <span uib-alert class="input-group-addon" data-ng-class="'alert-success'" data-ng-show="newProject.projectCode.length > 0 && projectCodeState == 'ok'">
> ```

same as previous comments

---

*[src/angular-app/languageforge/lexicon/views/view-settings.html, line 148 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGTyp8V3nnhVuu-td_:-KcGTyp9NzNOuA1nqN-P:b-23fyyj) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/languageforge/lexicon/views/view-settings.html#L148)):*
> ```HTML
>                             <div class="controls">
>                                 <label class="checkbox {{interfaceConfig.pullNormal}}">
>                                     <input type="checkbox" id="overrideInputSsystemsCheckbox"
> ```

spellcheck on the id="overrideInputSsystemsCheckbox"

---

*[src/angular-app/languageforge/semdomtrans/semdomtrans.html, line 9 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGUAcOQMB-P03IxFV4:-KcGUAcOQMB-P03IxFV5:b-sae0au) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/languageforge/semdomtrans/semdomtrans.html#L9)):*
> uib--tooltip
looks like there's an extra dash here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72)*

**Comment by darcywong00** [comment]
Review status: 40 of 45 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/angular-app/bellows/apps/usermanagement/bootstrap4/usermanagement.html, line 9 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGRjqtpVqYkAnSa-zA:-KcGfh2bbR8ysEi-Me6m:b-w2zfop) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/apps/usermanagement/bootstrap4/usermanagement.html#L9)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

wherever possible I would like to preserve the {{interfaceConfig.placementNormal}} and related settings for use when we do UI localization for RTL languages
</blockquote></details>

{{interfaceConfig.placementNormal}} was getting obscurred by the navbar, so I had to move it right


---

*[src/angular-app/bellows/directive/bootstrap4/pui-send-receive-credentials.html, line 18 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGSxKQIZXdwq_8TnAm:-KcGijOqxO_YlQ0_H_vC:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/directive/bootstrap4/pui-send-receive-credentials.html#L18)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

same as previous comments
</blockquote></details>

Done.

---

*[src/angular-app/bellows/directive/bootstrap4/pui-send-receive-credentials.html, line 46 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGT-KD8YTvS2Svp28B:-KcGilkHQ-MMe_ELGJgT:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/directive/bootstrap4/pui-send-receive-credentials.html#L46)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

same as previous comments
</blockquote></details>

Done.

---

*[src/angular-app/bellows/directive/bootstrap4/pui-send-receive-credentials.html, line 52 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGT3NMAeVZAXRaW4jd:-KcGinQwaxRA3rr0RzOV:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/directive/bootstrap4/pui-send-receive-credentials.html#L52)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

same as previous comments
</blockquote></details>

Done.

---

*[src/angular-app/languageforge/lexicon/new-project/views/new-project-name.html, line 31 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGTOulmgEYn6l6WlSI:-KcGjJ3kn7MS0-Mly5sX:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/languageforge/lexicon/new-project/views/new-project-name.html#L31)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

same as previous comments
</blockquote></details>

Done.

---

*[src/angular-app/languageforge/lexicon/views/view-settings.html, line 148 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGTyp8V3nnhVuu-td_:-KcG_wYbes26uHRwjrnw:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/languageforge/lexicon/views/view-settings.html#L148)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

spellcheck on the id="overrideInputSsystemsCheckbox"
</blockquote></details>

Done.

---

*[src/angular-app/languageforge/semdomtrans/semdomtrans.html, line 9 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGUAcOQMB-P03IxFV4:-KcGa1aq10GUAQYmyP3m:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/languageforge/semdomtrans/semdomtrans.html#L9)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

> uib--tooltip
looks like there's an extra dash here
</blockquote></details>

Done.

---

*[src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html, line 39 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGR7rqw_EnRQrrX4Pz:-KcGaHr-AGEthJiwEg5P:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html#L39)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

I'm not sure this is necessary to transform into a uib-alert.  Does the BS4 CSS provide enough here?  e.g. class="alert alert-success"
</blockquote></details>

Done.

---

*[src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html, line 65 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGROEsj5pTEn5iTiBd:-KcGaMVmTT55-p2Fhk3s:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html#L65)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

see comment above
</blockquote></details>

Done.

---

*[src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html, line 89 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGRRxAMoKG8jQl-Qoo:-KcGcn4JW9uvWoyISdIV:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html#L89)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

see comment above
</blockquote></details>

Done.

---

*[src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html, line 105 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGRTJWgijrA1VCmnpG:-KcGco2iR5C674WZmE6_:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html#L105)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

see comment above
</blockquote></details>

Done.

---

*[src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html, line 108 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGRU2-Lnv9S8e15izF:-KcGcojPoFJr0zx__W6d:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html#L108)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

see comment above
</blockquote></details>

Done.

---

*[src/angular-app/bellows/directive/bootstrap4/palaso.ui.comments.comments-right-panel.html, line 41 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-KcGSbs1UNCW4OQu1Chx:-KcGi2_yKUEsx8O08Zy2:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/1492a1d6b734d2164efe3c5b594d64e15b609a66/src/angular-app/bellows/directive/bootstrap4/palaso.ui.comments.comments-right-panel.html#L41)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

i don't see a reason to make this a uib-alert  I think just leaving it styled as a BS4 class="alert alert-warning" is fine.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72)*

**Comment by megahirt** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72)*

**Comment by megahirt** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/72#-:-KcH6nr5ejJ6686CyGQq:bnfp4nl)*

**Pull request merged**
