### PR TITLE
Rename docker-compose services

### PR DESCRIPTION
**Pull request by megahirt**
This PR re-arranges service names yet again to reflect my current thinking/understanding of the services and their role.  Naming things is hard!

## Changes in this PR

- Rename services as follows:

Old Name | New Name
------------ | -------------
api | **app**
ui | **ui-builder**
e2e | **test-e2e**
test-api | **test-php**
e2e-api | **app-for-e2e**

- The Makefile has been updated with the new names, which I believe more clearly reflect what is going on.

- The services that start with **`test-`** are test runner containers

- The `app` service now depends upon `ui-builder`, not the other way around.  This makes sense to me , since there is now a `--from=ui-builder` line in the `app` Dockerfile.  Further, the backwards dependency (fixed in this commit) was causing a build failure when building from scratch after a `make clean-powerwash`,

- Updated the README.md with the new names.

-  Removed `-t 1` due to LTOps team feedback (generates broken pipe error messages in journalctl logs)  Feel free to keep `-t 1` as a local change on your machine if you want.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/875)

### CODE REVIEW

**Review by longrunningprocess — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/875)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

___
*[docker/docker-compose.yml, line 85 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/875#-MVvB9MS2Xsn6pY1UFVR:-MVvB9MS2Xsn6pY1UFVS:b7uudyf) ([raw file](https://github.com/sillsdev/web-languageforge/blob/87cbd4190a3db8e01381532abe36bdb09306e029/docker/docker-compose.yml#L85)):*
> ```YAML
>     image: selenium/standalone-chrome-debug
>     links:
>       - "app-for-e2e:e2e"
> ```

Next time you come across this line, mind removing it and updating the reference in the code for the container?  I think we discussed the possibility that line is simply an unnecessary alias.  Thanks!

**Review by longrunningprocess — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/875)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

___
*[docker/docker-compose.yml, line 13 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/875#-MVw2uGR5ifGXEsf8XWp:-MVw2uGR5ifGXEsf8XWq:b6nwfml) ([raw file](https://github.com/sillsdev/web-languageforge/blob/87cbd4190a3db8e01381532abe36bdb09306e029/docker/docker-compose.yml#L13)):*
> ```YAML
>     volumes:
>       # share dist folder between ui and api containers
>       - lf-webpack-dist-folder:/data/src/dist
> ```

just for clarification, does this share still make sense?

**Review by longrunningprocess — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/875)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

___
*[docker/docker-compose.yml, line 85 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/875#-MVvB9MS2Xsn6pY1UFVR:-MVw89m00LKsfzab7YMG:bylo0p5) ([raw file](https://github.com/sillsdev/web-languageforge/blob/87cbd4190a3db8e01381532abe36bdb09306e029/docker/docker-compose.yml#L85)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

Next time you come across this line, mind removing it and updating the reference in the code for the container?  I think we discussed the possibility that line is simply an unnecessary alias.  Thanks!
</blockquote></details>

ref:  https://docs.docker.com/compose/compose-file/compose-file-v3/#links

**Review by megahirt — COMMENTED** [review]
addressed review comments.  Thanks @longrunningprocess for your review!

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/875#-:-MW2RwLv9kL75mu7UHmK:bgtba1m)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

___
*[docker/docker-compose.yml, line 13 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/875#-MVw2uGR5ifGXEsf8XWp:-MW2S-kx7eQMQtjZcqRd:b-j4x10) ([raw file](https://github.com/sillsdev/web-languageforge/blob/87cbd4190a3db8e01381532abe36bdb09306e029/docker/docker-compose.yml#L13)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

just for clarification, does this share still make sense?
</blockquote></details>

nope.  Thanks for catching that!  I've removed it.
___
*[docker/docker-compose.yml, line 85 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/875#-MVvB9MS2Xsn6pY1UFVR:-MW2S3x_6URZx0zzWPyA:b-ume0s4) ([raw file](https://github.com/sillsdev/web-languageforge/blob/87cbd4190a3db8e01381532abe36bdb09306e029/docker/docker-compose.yml#L85)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

ref:  https://docs.docker.com/compose/compose-file/compose-file-v3/#links
</blockquote></details>

Good point.  I've removed it.  Thanks!

**Review by megahirt — COMMENTED** [review]
> Reviewed 12 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/875)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

**Review by megahirt — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/875#-:-MW2SK481hAfcM9YPmgg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

**Review by megahirt — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/875)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

**Review by longrunningprocess — COMMENTED** [review]
these seem helpful, thank you!  I think they will result in some needed changes to the README as well.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/875#-:-MW5sv17778pompHWjS3:bpm06v7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
