### PR TITLE
Record comment "likes" in activity log

### PR DESCRIPTION
**Pull request by rmunn**
We don't record *who* pressed the "Like" button, only who wrote the comment that was "liked".

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/266)

### CODE REVIEW

**Comment by rmunn** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/Api/Model/Languageforge/Lexicon/Command/LexCommentCommands.php, line 109 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/266#-LDK-6u23ObW0yNNVJ4s:-LDLN4ZDCzxZ_1ZlrsGJ:bdq7zz) ([raw file](https://github.com/sillsdev/web-languageforge/blob/ce388e449dad152a3d02449c39f3075e90a10593/src/Api/Model/Languageforge/Lexicon/Command/LexCommentCommands.php#L109)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> 'increase'
> ```
Use a constant instead of this immediate string.
</blockquote></details>

Good point; we should also change this in the ActivityCommands::updateScore function that I copied the idea from.

---

*[src/Api/Model/Shared/Command/ActivityCommands.php, line 339 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/266#-LDJzePkBm5WtKqn2xTj:-LDa7YTy5OnjzSM3FFIZ:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/ce388e449dad152a3d02449c39f3075e90a10593/src/Api/Model/Shared/Command/ActivityCommands.php#L339)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> $mode
> ```
Describe the valid values of this. Better yet use a constant that's available to this functions client.
</blockquote></details>

Done.

---

*[src/Api/Model/Shared/Command/ActivityCommands.php, line 346 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/266#-LDK-p304wYBWpYJWPFd:-LDLRZyrEE-NHzsbCfrv:b2a079b) ([raw file](https://github.com/sillsdev/web-languageforge/blob/ce388e449dad152a3d02449c39f3075e90a10593/src/Api/Model/Shared/Command/ActivityCommands.php#L346)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> modifiedByUserRef
> ```
This would be the last one to edit the comment not the original author. Is this intentional?
</blockquote></details>

Not intentional; I copied and pasted the updateEntry function (and then adjusted it as needed) to make this one, and missed that bit of the logic. It makes more sense to credit the original author of the comment, so I'll make that change.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/266)*

**Comment by irahopkinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/266)*

**Comment by rmunn** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Api/Model/Languageforge/Lexicon/Command/LexCommentCommands.php, line 109 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/266#-LDK-6u23ObW0yNNVJ4s:-LDkJEYp32R_0eFiHc4G:btcxzww) ([raw file](https://github.com/sillsdev/web-languageforge/blob/ce388e449dad152a3d02449c39f3075e90a10593/src/Api/Model/Languageforge/Lexicon/Command/LexCommentCommands.php#L109)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

Good point; we should also change this in the ActivityCommands::updateScore function that I copied the idea from.
</blockquote></details>

Done in commit a994f0b.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/266)*

**Comment by irahopkinson** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/266#-:-LDmyqjj5ruUTSUEkHOc:bnfp4nl)*

**Comment by irahopkinson** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/266)*

**Pull request merged**
