### PR TITLE
Fix comments export to ParaText 7 and/or 8

### PR DESCRIPTION
**Pull request by rmunn**
PR originally on [web-scriptureforge repo](https://github.com/sillsdev/web-scriptureforge/pull/128), transferred over to this repo instead. Will probably squash-and-merge rather than merge the branch.

This fixes comment exporting for both Paratext 7 and 8. I've changed the "Prepare Export" button to be two buttons, one for Paratext 7 and one for Paratext 8 instead, and also changed the two-step process into a single-step process. (You used to click "Prepare", then wait a short while, then click "Download", but it makes more sense to download the file as soon as it's available. Thanks to @megahirt for the suggestion.) Screenshot:

screenshot

One feature NOT included in this PR is the ability to export all comments, not just those in a single text. The code is in place, we just have to implement it and add the UI to the project settings screen. But this branch will at least get the feature working first; then we can add convenience.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/183)

### CODE REVIEW

**Comment by megahirt** [comment]
I have a few comments, but everything else looks good.  Nice work Robin!

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/angular-app/scriptureforge/sfchecks/partials/questions-settings.html, line 154 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/183#-L4KOdPyvKh_paA6SiNZ:-L4KOdPyvKh_paA6SiN_:b-gisgt0) ([raw file](https://github.com/sillsdev/web-languageforge/blob/2258e41110949b11bc8cb58cd21f8d08b80ce300/src/angular-app/scriptureforge/sfchecks/partials/questions-settings.html#L154)):*
> ```HTML
>                 <div class="col-sm-6" data-ng-show="download.totalCount">
>                     <br class="d-sm-none">
>                     <p data-ng-show="download.totalCount > 0" class="text-success">
> ```

I think it would still be nice to see the number of comments downloaded, even after the user has saved the file.  Can we still keep the answerCount and commentCount in the display somewhere?

---

*[src/Api/Library/Scriptureforge/Sfchecks/ParatextExport.php, line 120 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/183#-L4KPk-Jn4m2ilE9mPNX:-L4KPk-Jn4m2ilE9mPNY:b-okl9x8) ([raw file](https://github.com/sillsdev/web-languageforge/blob/071570172a7c1f9a11ea8fd505f5a66f53eb54e3/src/Api/Library/Scriptureforge/Sfchecks/ParatextExport.php#L120)):*
> ```PHP
> 
>         // Is there a better way than specifying the function name *and* class name as "magic strings"? I'm unfamiliar with how to do this in PHP. - 2018-01 RM
>         return call_user_func(["\Api\Library\Scriptureforge\Sfchecks\ParatextExport", $commentFormatter], $threadId, $username, $textInfo, "", $comment['dateEdited']->toDateTime(), $content);
> ```

I don't think self::$commentFormatter actually works, but how about:

```
if ($commentFormatter == "formatForPT7") {
    return self::formatForPT7($threadId, $username, $textInfo, "", $comment['dateEdited']->toDateTime(), $content);
} else {
    return self::formatForPT8($threadId, $username, $textInfo, "", $comment['dateEdited']->toDateTime(), $content);
}
```

But seeing it now it looks like maybe you really only need a self::formatComment() which takes a $format parameter, and inside you can switch formats based on that.  The methods seem really similar to me at this point (although they could in theory diverge more later)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/183#-:-L4KSElDpX5Mrpo-vivC:b-olxkpo)*

**Comment by rmunn** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/angular-app/scriptureforge/sfchecks/partials/questions-settings.html, line 154 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/183#-L4KOdPyvKh_paA6SiNZ:-L4Kb9id2ttOQfsM8O0_:bjq9g8u) ([raw file](https://github.com/sillsdev/web-languageforge/blob/2258e41110949b11bc8cb58cd21f8d08b80ce300/src/angular-app/scriptureforge/sfchecks/partials/questions-settings.html#L154)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

I think it would still be nice to see the number of comments downloaded, even after the user has saved the file.  Can we still keep the answerCount and commentCount in the display somewhere?
</blockquote></details>

Yes, I can make it display as the file starts downloading.

---

*[src/Api/Library/Scriptureforge/Sfchecks/ParatextExport.php, line 120 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/183#-L4KPk-Jn4m2ilE9mPNX:-L4KbI4NEybk92nZkJoE:b-d430km) ([raw file](https://github.com/sillsdev/web-languageforge/blob/071570172a7c1f9a11ea8fd505f5a66f53eb54e3/src/Api/Library/Scriptureforge/Sfchecks/ParatextExport.php#L120)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

I don't think self::$commentFormatter actually works, but how about:

```
if ($commentFormatter == "formatForPT7") {
    return self::formatForPT7($threadId, $username, $textInfo, "", $comment['dateEdited']->toDateTime(), $content);
} else {
    return self::formatForPT8($threadId, $username, $textInfo, "", $comment['dateEdited']->toDateTime(), $content);
}
```

But seeing it now it looks like maybe you really only need a self::formatComment() which takes a $format parameter, and inside you can switch formats based on that.  The methods seem really similar to me at this point (although they could in theory diverge more later)
</blockquote></details>

They are very similar; in fact, they're basically the same method except for which header method they call. I decided not to combine them into a single method, though, because I felt that the extra mental step to understand that combined method wouldn't be justified by the savings. After all, as you point out, they might diverge later, and this isn't a case where I'll want to change both methods at once in the future. So in this one case, factoring out the repeated code would (IMO) have added more complexity than it removed (though factoring out repeated code is *usually* what you want to do).

Yes, I think moving that `switch` statement into its own function (one that takes a `$format` parameter) probably makes the most sense. I'll do that before I merge the branch.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/183)*

**Comment by megahirt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/angular-app/scriptureforge/sfchecks/partials/questions-settings.html, line 154 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/183#-L4KOdPyvKh_paA6SiNZ:-L4Km7ZMuIJzmwmJ0uFg:bp7vbga) ([raw file](https://github.com/sillsdev/web-languageforge/blob/2258e41110949b11bc8cb58cd21f8d08b80ce300/src/angular-app/scriptureforge/sfchecks/partials/questions-settings.html#L154)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

Yes, I can make it display as the file starts downloading.
</blockquote></details>

sounds good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/183)*

**Comment by megahirt** [comment]
@rmunn merge this one yourself when you're ready

**Pull request merged**
