### PR TITLE
Refactor SASS compilation in gulpfile

### PR DESCRIPTION
**Pull request by Nateowami**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/80)

### CODE REVIEW

**Comment by megahirt** [comment]
:lgtm: Thanks for doing this Nathaniel! 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gulpfile.js, line 620 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/80#-Kd0AiiMQbimZ-Mfo3Bx:-Kd0AiiMQbimZ-Mfo3By:b5hs8rc) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4537804beb81a7d96928c9ed0f805e5236ea420e/gulpfile.js#L620)):*
> ```JavaScript
> ];
> 
> gulp.task('sass', () => {
> ```

I prefer having `function ()` instead of just `()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/80#-:-Kd0Aew0pgNS9gP6lJoR:b3c0729)*

**Comment by Nateowami** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gulpfile.js, line 620 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/80#-Kd0AiiMQbimZ-Mfo3Bx:-Kd0DuqFeoQMsI3htWg_:b3k7ffq) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4537804beb81a7d96928c9ed0f805e5236ea420e/gulpfile.js#L620)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

I prefer having `function ()` instead of just `()`
</blockquote></details>

OK, I'll change it to the function() style then. The same for the anonymous functions that do take arguments (like the line below) I presume?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/80)*

**Comment by Nateowami** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[gulpfile.js, line 102 at r2](https://reviewable.io:443/reviews/sillsdev/web-languageforge/80#-Kd0GBTZ2yNVwd8uDZXg:-Kd0GBTZ2yNVwd8uDZXh:bcsg7q8) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4542920a49d87dd24d336f3846c9e88ba8d29819/gulpfile.js#L102)):*
> ```JavaScript
> 
> var execute = function (command, options, callback) {
>   if (!options) {
> ```

I initially changed == to === because == does weak comparison (and linter flags it). Turns out in every case if options are not given it's null, so this broke it (`null == undefined` in JavaScript). Now it should handle both cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/80)*

**Comment by Nateowami** [comment]
If you could hold off on merging this, I just ran the e2e tests and had over 100 failures. I wasn't aware of changing anything that should affect them, but I need to see if it's related.

**Comment by Nateowami** [comment]
I ran the tests again this morning and it appears the results are inconsistent on my machine. They're now all passing. So disregard the above; it's OK to merge once all other checks are passed.

**Comment by darcywong00** [comment]
Yep, thanks for cleaning this up.  Could you also update .gitignore to ignore these generated css files?  Other than that LGTM

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[gulpfile.js, line 1002 at r3](https://reviewable.io:443/reviews/sillsdev/web-languageforge/80#-Kd5DC7O2XbwconMvD45:-Kd5DC7O2XbwconMvD46:b-dzjabh) ([raw file](https://github.com/sillsdev/web-languageforge/blob/41b622a7c36202748b0962afa14cbdb3d1a9444e/gulpfile.js#L1002)):*
> ```JavaScript
>       'build-clearLocalCache',
>       'build-remove-test-fixtures'),
>     'sass:buildAll',
> ```

With the sass task being renamed, can you also update the README.md ?

Install node_modules used to build sass files and run E2E tests
```
cd web-languageforge
npm install
gulp sass:buildAll
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/80#-:-Kd5E7OMKZoLsPCqLrg_:b9mfutl)*

**Pull request merged**
