### PR TITLE
Feature/cleanup user commands

### PR DESCRIPTION
**Pull request by darcywong00**
Feature to handle [story 2](https://docs.google.com/document/d/16e0qYviMaCf9OXMYbUWpzOjhzO1U8jLvzm1rXYIiitk/edit) 

Cleanup user commands involving **check identity**
Add API to ban (deactivate) users

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/93)

### CODE REVIEW

**Comment by megahirt** [comment]
*[src/Api/Model/Shared/Command/UserCommands.php, line 62 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/93#-KgDaASwm_qMhmwvpu8A:-KgDaASxr4dn3XxH624V:b-pilyx2) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5eae1577c37d8cee17e27e2fcbde1a21fee1885f/src/Api/Model/Shared/Command/UserCommands.php#L62)):*
> ```PHP
>      * @return string $userId
>      */
>     public static function updateUser($params, $website)
> ```

I approve this PR.  Just a note to say that I think we should use the existing register command to create new users, and not allow users to be created through the updateUser method.  I'd like to see us move toward this change.  Creating an user involves too many complexities and I want to encapsulate that in a single method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/93)*

**Comment by megahirt** [comment]
A few small changes but otherwise this looks really good!

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Site/Controller/Auth.php, line 83 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/93#-KgDbO7vKVt-v653HBmP:-KgDbO7vKVt-v653HBmQ:bsoe4w9) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5eae1577c37d8cee17e27e2fcbde1a21fee1885f/src/Site/Controller/Auth.php#L83)):*
> ```PHP
>         $this->data['last_username'] = $app['session']->get(Security::LAST_USERNAME);
>         $errorMsg = $app['security.last_error']($request);
>         if($errorMsg == 'Bad credentials.') $errorMsg = 'Invalid username or password.';
> ```

I suppose we could use the same trick you did for the reset and forgot password methods, in that we load an user model for the purpose of checking the active flag.  Then we tailor the message to suit.  If you were going to change one thing on this PR, that's what I'd like.

---

*[src/Site/Provider/AuthUserProvider.php, line 28 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/93#-KgDb2seOj44dzz8g7cz:-KgDb2seOj44dzz8g7d-:bmvrzll) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5eae1577c37d8cee17e27e2fcbde1a21fee1885f/src/Site/Provider/AuthUserProvider.php#L28)):*
> ```PHP
> 
>         $user = new UserModelWithPassword();
>         $user->readByUsernameOrEmail($usernameOrEmail);
> ```

BTW glad to see this in a method of it's own

---

*[test/php/model/shared/commands/UserCommandsTest.php, line 68 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/93#-KgDc1pdj9STpwT_DGrf:-KgDc1pdj9STpwT_DGrg:b-775vp8) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5eae1577c37d8cee17e27e2fcbde1a21fee1885f/test/php/model/shared/commands/UserCommandsTest.php#L68)):*
> ```PHP
>         self::$environ->clean();
> 
>         $userId = UserCommands::banUser(null);
> ```

We should use 

`$this->expectException(InvalidArgumentException::class); `

see: https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.exceptions.examples.ExceptionTest.php

---

*[test/php/model/shared/commands/UserCommandsTest.php, line 78 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/93#-KgDc-negY29Bj8CWspI:-KgDc-nf8S2oHrrmeAO8:bnj7hl0) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5eae1577c37d8cee17e27e2fcbde1a21fee1885f/test/php/model/shared/commands/UserCommandsTest.php#L78)):*
> ```PHP
>         self::$environ->clean();
> 
>         $userId = UserCommands::banUser('notAnId');
> ```

same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/93#-:-KgDgAEUH5VwZO78Weqw:b17lvxs)*

**Comment by megahirt** [comment]
*[test/php/model/shared/commands/UserCommandsTest.php, line 68 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/93#-KgDc1pdj9STpwT_DGrf:-KgE6ppv_g01F4kZscBQ:bmu0xa8) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5eae1577c37d8cee17e27e2fcbde1a21fee1885f/test/php/model/shared/commands/UserCommandsTest.php#L68)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

We should use 

`$this->expectException(InvalidArgumentException::class); `

see: https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.exceptions.examples.ExceptionTest.php
</blockquote></details>

lets just put a TODO message in here that we want to use `$this->expectException(InvalidArgumentException::class);` when our version of PHPUnit supports it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/93)*

**Comment by megahirt** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/93#-:-KgE75Y4hUbdglP2JByE:bnfp4nl)*

**Comment by darcywong00** [comment]
Review status: 6 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Api/Model/Shared/Command/UserCommands.php, line 62 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/93#-KgDaASwm_qMhmwvpu8A:-KgE98DarQBsyCS6FAjw:briuh35) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5eae1577c37d8cee17e27e2fcbde1a21fee1885f/src/Api/Model/Shared/Command/UserCommands.php#L62)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

I approve this PR.  Just a note to say that I think we should use the existing register command to create new users, and not allow users to be created through the updateUser method.  I'd like to see us move toward this change.  Creating an user involves too many complexities and I want to encapsulate that in a single method.
</blockquote></details>

When using the site admin panel to create new users, this introduces a limitation of not assigning the initial System Role (register  defaults all new users to User

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/93)*

**Pull request merged**
