### PR TITLE
Try to fix up Typescript errors

### PR DESCRIPTION
**Pull request by rmunn**
I think this will fix the compile errors on master.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/834)

### CODE REVIEW

**Comment by rmunn** [comment]
With commit 4565256856d6b3a98e8130ba6cd8a231ce37a7b1, the compile is working now.

**Review by longrunningprocess — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/834)* status: all files reviewed, 1 unresolved discussion (waiting on @rmunn)

___
*[src/angular-app/scriptureforge/sfchecks/shared/sil-selection.directive.ts, line 2 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/834#-MUEy97VAXNrQOMliB8u:-MUEy97W6t9UzrpmcMSQ:b-5gf5fy) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4565256856d6b3a98e8130ba6cd8a231ce37a7b1/src/angular-app/scriptureforge/sfchecks/shared/sil-selection.directive.ts#L2)):*
> ```XML
> // tslint:disable-next-line:no-reference
> ///<reference types="rangy/rangy-classapplier"/>
> ```

now this is a lovely change!

**Review by megahirt — APPROVED** [review]
:lgtm: I checked out your branch, rebuild my containers and the TS compile errors are fixed.  Well done!


> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/834#-:-MUG3Tac8vAt_pM_ck8E:b-lsh9m7)* status: all files reviewed, 1 unresolved discussion (waiting on @rmunn)

**Review by megahirt — APPROVED** [review]
> Dismissed @longrunningprocess from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/834)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
