### PR TITLE
feature/commentOnListItems

### PR DESCRIPTION
**Pull request by ThomasBlok**
Added warning to start project, downgraded button to (underlined) link

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/174)

### CODE REVIEW

**Comment by megahirt** [comment]
Code looks good after changing the "not recommended" message to use bootstrap.  Thanks!  :lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/angular-app/languageforge/lexicon/new-project/views/new-project-name.html, line 6 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/174#-L-jh09PrIh7ggP6DMls:-L-jh09QCP87i5VplFPQ:b-pa1mm7) ([raw file](https://github.com/sillsdev/web-languageforge/blob/722d56e4bf22648c23ce18d4ad877f334052a556/src/angular-app/languageforge/lexicon/new-project/views/new-project-name.html#L6)):*
> ```HTML
>             <div class="text-xs-center">
>                 <h3 class ="no-space-break" data-translate="Choose a project name"></h3>
>                 <I style="color:red">Creating a non-send/receive project in Language Forge is no longer recommended because of the lack of an export path.</I>
> ```

In thinking about this some more, how about using a bootstrap style that is designed to display a warning:  E.g:
<div class="alert alert-warning" role="alert">
Creating a non-send/receive project in Language Forge is no longer recommended because of the lack of an export path.
</div>

See https://v4-alpha.getbootstrap.com/components/alerts/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/174#-:-L-jhRXE_Wvw9H2qn_Ho:b-b9f0ri)*

**Comment by ThomasBlok** [comment]
*[src/angular-app/languageforge/lexicon/new-project/views/new-project-name.html, line 6 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/174#-L-jh09PrIh7ggP6DMls:-L07VzG40QsP8-AE472V:bb6un1j) ([raw file](https://github.com/sillsdev/web-languageforge/blob/722d56e4bf22648c23ce18d4ad877f334052a556/src/angular-app/languageforge/lexicon/new-project/views/new-project-name.html#L6)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

In thinking about this some more, how about using a bootstrap style that is designed to display a warning:  E.g:
<div class="alert alert-warning" role="alert">
Creating a non-send/receive project in Language Forge is no longer recommended because of the lack of an export path.
</div>

See https://v4-alpha.getbootstrap.com/components/alerts/
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/174)*

**Comment by ThomasBlok** [comment]
I added these commits as per your request

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/174#-:-L07WHba9eWVqAMieDcG:b-fsd8cq)*

**Comment by megahirt** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/174)*

**Pull request merged**
