### PR TITLE
Feature/dockerize lfmerge

### PR DESCRIPTION
**Pull request by longrunningprocess**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/857)

### CODE REVIEW

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/857)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @megahirt and @rmunn)

___
*[docker/docker-compose.yml, line 42 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3CwoV6pwG3XNOKBGQ:-MV3CwoW46EoUa-pSEPX:b5bjq1d) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/docker-compose.yml#L42)):*
> ```YAML
>       - lf-user-data-assets:/var/www/src/assets
> 
>       #TODO: need a place that makes sense in this container - lfmerge-queue:
> ```

Need some help on where might be the best location within the api container to drop files...typical convention would put them in `/data`
___
*[docker/lfmerge/Dockerfile, line 1 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3EUkL2-9FAGU88wJe:-MV3EUkL2-9FAGU88wJf:byhexev) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L1)):*
> ```Dockerfile
> FROM ubuntu:bionic
> ```

does this HAVE to be bionic?  I'm assuming yes for some dependency lfmerge probably has on it but thought I'd ask since bringing something similar to inotify requires all kinds of additional hoops to jump through unless I'm just not using the os properly.
___
*[docker/lfmerge/Dockerfile, line 8 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3EpmxEyYn6Po3QeVQ:-MV3EpmxEyYn6Po3QeVR:bz1kxng) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L8)):*
> ```Dockerfile
> RUN debconf-set-selections quiet-install-postfix.conf
> 
> RUN apt-get update \
> ```

I'd like to think through the build approach with someone to see if there are things we can optimize.
___
*[docker/lfmerge/Dockerfile, line 17 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3Eyw696yHJLB_F4u8:-MV3Eyw696yHJLB_F4u9:b-wsk75w) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L17)):*
> ```Dockerfile
>  && apt-get install --yes --no-install-recommends lfmerge
> 
> CMD iwatch -c /usr/bin/lfmergeqm -e create /var/lib/languageforge/lexicon/sendreceive/syncqueue
> ```

I'm guessing at this part for now, does this look right so far?
___
*[docker/lfmerge/Dockerfile, line 17 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3F7DIBZKSI0Mrjvbf:-MV3F7DIBZKSI0Mrjvbg:b-7fb8wr) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L17)):*
> ```Dockerfile
>  && apt-get install --yes --no-install-recommends lfmerge
> 
> CMD iwatch -c /usr/bin/lfmergeqm -e create /var/lib/languageforge/lexicon/sendreceive/syncqueue
> ```

iwatch is a perl wrapper, are we cool with that?
___
*[docker/lfmerge/Dockerfile, line 17 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3FC5E9IqebiF1QKNd:-MV3FC5E9IqebiF1QKNe:b-7pj4ll) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L17)):*
> ```Dockerfile
>  && apt-get install --yes --no-install-recommends lfmerge
> 
> CMD iwatch -c /usr/bin/lfmergeqm -e create /var/lib/languageforge/lexicon/sendreceive/syncqueue
> ```

I noticed the group owner on this syncqueue directory is `fieldworks`...I'd like to challenge the need for such things until I understand it's importance and the possible issues that result for us volume sharing things...not sure if would anticipate problems resulting from sharing this between two containers with potentially different file perms.

**Comment by rmunn** [comment]
Hi @longrunningprocess,

@megahirt and I talked about this on Friday and we identified another place where lfmerge is tightly coupled to the Language Forge PHP server. In the part of lfmerge that handles custom fields, it actually makes a call to the Language Forge PHP server via a PHP entrypoint called RunClass.php in the LF repo. The work that it does there *could* be done entirely within the lfmerge code, but we decided (at the time, which was about 4 years ago) that since LF already contained the code needed for that particular process, we'd just couple the two and only write that code once.

Since this means two points of coupling between LF and lfmerge, @megahirt decided to see whether the lfmerge .deb package would install cleanly in our existing Docker container for LF — and it did.

So I think we should put this PR on hold, and just add the lfmerge Debian package to the build process for the lf-api container. Later on we can work on separating lfmerge out (which will include a partial rewrite of its logic so it no longer needs to do a PHP shell call into RunClass.php), but for now I believe it makes the most sense to run lfmerge inside the lf-api container, rather than build a separate container for it. I know that's not Docker best practices, but the two apps are too tightly coupled right now to be worth separating them. Let's get all of LF up and running and passing E2E tests first, and then revisit moving lfmerge into a separate container.

@megahirt, is that your opinion also? Based on our conversation at the office last week I think that's what you were leaning towards, but I want to double-check that I understood you right.

**Comment by megahirt** [comment]
Yes @rmunn you've summarized our conversation well.  @longrunningprocess thanks for your work in trying out various approaches to kick off the lfmerge process via inotify.  I'm going to start a separate branch which copies the LFMerge apt lines into the PHP container and then we can further discuss how to integrate the inotify work you've already done.

**Review by megahirt — COMMENTED** [review]
So, while we cannot merge this PR branch, we've learned some things and will take what we've learned onto the next branch/PR.  Thanks again @longrunningprocess and @rmunn 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-:-MVG8WSZAmmX1J9unj-i:bchlqop)* status: all files reviewed, 6 unresolved discussions (waiting on @longrunningprocess and @rmunn)

___
*[docker/lfmerge/Dockerfile, line 1 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3EUkL2-9FAGU88wJe:-MVG7IZ5-AKvjEIvvuWW:bc7ippe) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L1)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

does this HAVE to be bionic?  I'm assuming yes for some dependency lfmerge probably has on it but thought I'd ask since bringing something similar to inotify requires all kinds of additional hoops to jump through unless I'm just not using the os properly.
</blockquote></details>

Well, the deb package was built and tested on ubuntu:bionic.  However, I did just recently test install the lfmerge package on the php7.3-apache container (which is based upon debian buster I think) and it worked!  This is a small miracle of sorts - and I'll take it.  Due to the reasons that @rmunn outlined in his comments, LFMerge is actually really tightly coupled with the PHP container, so it's unreasonable at this point to try and separate it out into a separate container without shipping a new version of LFMerge (could be challenging as our build/ship process on Jenkins is in question ATM)
___
*[docker/lfmerge/Dockerfile, line 8 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3EpmxEyYn6Po3QeVQ:-MVGGBjTA18qMyVis8dp:bxtpn3o) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L8)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

I'd like to think through the build approach with someone to see if there are things we can optimize.
</blockquote></details>

I've taken a look at [iwatch](http://iwatch.sourceforge.net/index.html) and we actually don't want to use that.  It has perl as a dependency and appears to be last updated in 2009, ugh.  See comment below on my suggested replacement.
___
*[docker/lfmerge/Dockerfile, line 17 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3FC5E9IqebiF1QKNd:-MVG8C08EOTlR2HK1HK7:bdrgcdp) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L17)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

I noticed the group owner on this syncqueue directory is `fieldworks`...I'd like to challenge the need for such things until I understand it's importance and the possible issues that result for us volume sharing things...not sure if would anticipate problems resulting from sharing this between two containers with potentially different file perms.
</blockquote></details>

Always good to challenge.  As I understand it the fieldworks user is a requirement of the underlying liblcm library which lfmerge takes as a dependency.  Unfortunately, we cannot change that as we are not in control of liblcm (at least right now).
___
*[docker/lfmerge/Dockerfile, line 17 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3Eyw696yHJLB_F4u8:-MVGGX1-Ep5aWUCn4n-4:b-kogkic) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L17)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

I'm guessing at this part for now, does this look right so far?
</blockquote></details>

If we were using iwatch then that looks right (although I didn't test it).  See below comment for a better alternative
___
*[docker/lfmerge/Dockerfile, line 17 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3F7DIBZKSI0Mrjvbf:-MVGGj0S-yYl6aibjoJ5:bskgfhz) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L17)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

iwatch is a perl wrapper, are we cool with that?
</blockquote></details>

I found this [high traffic SO page which lists a number of ways that we could accomplish the watch without polling](https://superuser.com/questions/181517/how-to-execute-a-command-whenever-a-file-changes).  Of the options presented, I like entr the best.  The github page was updated a week or two ago and it's available in apt for ubuntu/debian and appears to have no dependencies above the base debian install.  See http://eradman.com/entrproject/ and https://github.com/eradman/entr/

**Review by longrunningprocess — COMMENTED** [review]
agreed, this has been valuable if nothing else to shake out the concrete points of coupling...nice to know what we're dealing with.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-:-MVH8CryBHYiFWzg31fV:b-iypolf)* status: all files reviewed, 6 unresolved discussions (waiting on @megahirt and @rmunn)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3FzcfDpAVyVScVrPO:-MV3FzcfDpAVyVScVrPP:b-4yw70e) (no related file):*
I would appreciate some assistance with portions of this implementation.

Additionally, there are outstanding tasks in the related issue https://github.com/sillsdev/web-languageforge/issues/818

---
___
*[docker/lfmerge/Dockerfile, line 1 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3EUkL2-9FAGU88wJe:-MVH8TDM6en5vCB3AeTV:bklaumr) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L1)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

Well, the deb package was built and tested on ubuntu:bionic.  However, I did just recently test install the lfmerge package on the php7.3-apache container (which is based upon debian buster I think) and it worked!  This is a small miracle of sorts - and I'll take it.  Due to the reasons that @rmunn outlined in his comments, LFMerge is actually really tightly coupled with the PHP container, so it's unreasonable at this point to try and separate it out into a separate container without shipping a new version of LFMerge (could be challenging as our build/ship process on Jenkins is in question ATM)
</blockquote></details>

that's great news!
___
*[docker/lfmerge/Dockerfile, line 8 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3EpmxEyYn6Po3QeVQ:-MVH8ZHW9UlE7eEvImbY:b9uq55u) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L8)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

I've taken a look at [iwatch](http://iwatch.sourceforge.net/index.html) and we actually don't want to use that.  It has perl as a dependency and appears to be last updated in 2009, ugh.  See comment below on my suggested replacement.
</blockquote></details>

no problem, ideally we would just use inotifyd which is already installed in alpine...but we'll cross that bridge when/if we get there.
___
*[docker/lfmerge/Dockerfile, line 17 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3F7DIBZKSI0Mrjvbf:-MVH8oVU-Sjz4yVXUkJ7:b7u2tj6) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L17)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

I found this [high traffic SO page which lists a number of ways that we could accomplish the watch without polling](https://superuser.com/questions/181517/how-to-execute-a-command-whenever-a-file-changes).  Of the options presented, I like entr the best.  The github page was updated a week or two ago and it's available in apt for ubuntu/debian and appears to have no dependencies above the base debian install.  See http://eradman.com/entrproject/ and https://github.com/eradman/entr/
</blockquote></details>

yep, we can keep those in mind, ideally we'd just use inotifyd as I did in my first attempt, it's the closest to the os imo.
___
*[docker/lfmerge/Dockerfile, line 17 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/857#-MV3FC5E9IqebiF1QKNd:-MVH8xQy7baHYr4q3QDF:bkfwhx4) ([raw file](https://github.com/sillsdev/web-languageforge/blob/d5d8fc7fc294b74f211d2e161d4a7e66a53f6460/docker/lfmerge/Dockerfile#L17)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

Always good to challenge.  As I understand it the fieldworks user is a requirement of the underlying liblcm library which lfmerge takes as a dependency.  Unfortunately, we cannot change that as we are not in control of liblcm (at least right now).
</blockquote></details>

gotcha, good to know.

**Pull request closed without merging**
