### PR TITLE
Feature/LFMerge in api container

### PR DESCRIPTION
**Pull request by megahirt**
This PR adds LFMerge deb package and the related permissions necessary to the api docker container.

This also re-enables 2 E2E tests and 2 PHP tests which were removed previously due to the absence of an LFMerge install (they were expected failures).  Now that we have LFMerge installed, we add the tests back in.

We had a go at making a separate container for LFMerge initially, but that proved to be too cumbersome because of the tight coupling between the PHP and LFMerge codebase.  Running them in the same PHP container simplifies the setup somewhat.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/865)

### CODE REVIEW

**Review by rmunn — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/865)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

___
*[docker/api/Dockerfile, line 22 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/865#-MVLEreZDrZfneQErsTf:-MVLEre_DmE3pP5YQlMM:b-uyhofa) ([raw file](https://github.com/sillsdev/web-languageforge/blob/c00a6c106ba5f8c5d69977d02a04151ffb8e7898/docker/api/Dockerfile#L22)):*
> ```Dockerfile
> && echo "deb http://linux.lsdev.sil.org/ubuntu bionic main" > /etc/apt/sources.list.d/linux-lsdev-sil-org.list \
> && apt-get update \
> && apt-get purge --yes curl \
> ```

I think we'll want to investigate why curl needed to be removed. I remember a conflict with package dependencies, but not what that conflict was. It's possible that removing curl here will cause PHP HTTP requests to fail, because I know the GuzzleHttp library is using curl under the hood. That will only show up in the Send/Receive page when Language Forge does an HTTP request to Language Depot to check what projects the user is a member of. But once the Language Depot API containers are added to the project, then more E2E tests might start failing if GuzzleHttp can't function without curl.

But let's go ahead and merge this as-is for now, then remove the `apt-get purge curl` line and see if it continues to work.

**Review by megahirt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/865)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @rmunn)

___
*[docker/api/Dockerfile, line 22 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/865#-MVLEreZDrZfneQErsTf:-MVLIU_71kZ9eBhkjYHj:b-430gdl) ([raw file](https://github.com/sillsdev/web-languageforge/blob/c00a6c106ba5f8c5d69977d02a04151ffb8e7898/docker/api/Dockerfile#L22)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

I think we'll want to investigate why curl needed to be removed. I remember a conflict with package dependencies, but not what that conflict was. It's possible that removing curl here will cause PHP HTTP requests to fail, because I know the GuzzleHttp library is using curl under the hood. That will only show up in the Send/Receive page when Language Forge does an HTTP request to Language Depot to check what projects the user is a member of. But once the Language Depot API containers are added to the project, then more E2E tests might start failing if GuzzleHttp can't function without curl.

But let's go ahead and merge this as-is for now, then remove the `apt-get purge curl` line and see if it continues to work.
</blockquote></details>

I am totally fine leaving curl installed.  It made sense to remove it in the separate LFMerge container where we had no dependency on curl.  It doesn't make sense to play with fire and remove the curl package when we know that our application has a dependency on libcurl.  Chalk this up to a copy/paste error.  Good catch.

**Review by megahirt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/865)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @rmunn)

___
*[docker/api/Dockerfile, line 22 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/865#-MVLEreZDrZfneQErsTf:-MVLKghC1k2KhIrioXRu:brpmqc3) ([raw file](https://github.com/sillsdev/web-languageforge/blob/c00a6c106ba5f8c5d69977d02a04151ffb8e7898/docker/api/Dockerfile#L22)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

I am totally fine leaving curl installed.  It made sense to remove it in the separate LFMerge container where we had no dependency on curl.  It doesn't make sense to play with fire and remove the curl package when we know that our application has a dependency on libcurl.  Chalk this up to a copy/paste error.  Good catch.
</blockquote></details>

removed.

**Review by rmunn — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/865)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

___
*[test/php/model/languageforge/lexicon/command/SendReceiveCommandsTest.php, line 261 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/865#-MVLLnm262YkgaghCszS:-MVLLnm262YkgaghCszT:bhk6odx) ([raw file](https://github.com/sillsdev/web-languageforge/blob/c00a6c106ba5f8c5d69977d02a04151ffb8e7898/test/php/model/languageforge/lexicon/command/SendReceiveCommandsTest.php#L261)):*
> ```PHP
>         file_put_contents($mockPidFilePath, $pid);
> 
>         $isRunning = SendReceiveCommands::isProcessRunningByPidFile($mockPidFilePath);
> ```

I think https://stackoverflow.com/a/14880926 is a better way to check if a process is running. We can change that in a later PR.

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/865)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

___
*[docker/api/Dockerfile, line 22 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/865#-MVNK0xh3MCdI2WT8U4o:-MVNK0xh3MCdI2WT8U4p:b-les0mq) ([raw file](https://github.com/sillsdev/web-languageforge/blob/c00a6c106ba5f8c5d69977d02a04151ffb8e7898/docker/api/Dockerfile#L22)):*
> ```Dockerfile
> && echo "deb http://linux.lsdev.sil.org/ubuntu bionic main" > /etc/apt/sources.list.d/linux-lsdev-sil-org.list \
> && apt-get update \
> && apt-get purge --yes curl \
> ```

fwiw, I see this sometimes when people are cleaning up the final image...when I first saw this I assumed it was there because curl was only needed for the key and was then deleted because nothing else in the container needed it.

I couldn't find the discussion on this line anywhere in reviewable, sorry if this isn't the right place for this.

**Review by megahirt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/865)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

___
*[docker/api/Dockerfile, line 22 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/865#-MVNK0xh3MCdI2WT8U4o:-MVODYfm9_OtkdTrkBtl:bxxgnco) ([raw file](https://github.com/sillsdev/web-languageforge/blob/c00a6c106ba5f8c5d69977d02a04151ffb8e7898/docker/api/Dockerfile#L22)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

fwiw, I see this sometimes when people are cleaning up the final image...when I first saw this I assumed it was there because curl was only needed for the key and was then deleted because nothing else in the container needed it.

I couldn't find the discussion on this line anywhere in reviewable, sorry if this isn't the right place for this.
</blockquote></details>

yes.  I explained this to Robin that we had the purge line in the lfmerge container to "clean up" since curl wasn't needed for anything other than getting the file from the internet.

I was much less confident purging the curl package knowing that our application depends upon libcurl.

FYI reviewable will close and "hide" resolved discussions that can be hard to find.  I can see a little "checkbox" next to the line where the previous discussion was.  If I click on that, I can see the resolved discussion thread.

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/865)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

___
*[docker/api/Dockerfile, line 22 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/865#-MVNK0xh3MCdI2WT8U4o:-MVOJLku0tnumTE4Ui8p:b-u6mvha) ([raw file](https://github.com/sillsdev/web-languageforge/blob/c00a6c106ba5f8c5d69977d02a04151ffb8e7898/docker/api/Dockerfile#L22)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

yes.  I explained this to Robin that we had the purge line in the lfmerge container to "clean up" since curl wasn't needed for anything other than getting the file from the internet.

I was much less confident purging the curl package knowing that our application depends upon libcurl.

FYI reviewable will close and "hide" resolved discussions that can be hard to find.  I can see a little "checkbox" next to the line where the previous discussion was.  If I click on that, I can see the resolved discussion thread.
</blockquote></details>

ah!  Yes, I see that little checkmark as well, thank you!

**Review by rmunn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/865)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

___
*[docker/api/Dockerfile, line 22 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/865#-MVNK0xh3MCdI2WT8U4o:-MVUSUnWAyLzqp4U2Iey:b-s1n7u2) ([raw file](https://github.com/sillsdev/web-languageforge/blob/c00a6c106ba5f8c5d69977d02a04151ffb8e7898/docker/api/Dockerfile#L22)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

ah!  Yes, I see that little checkmark as well, thank you!
</blockquote></details>

Also, at the top of the Reviewable page where the "main" comments are (the comments on the PR as a whole), there's a "Show N older comments" link, with a dropdown arrow. The dropdown arrow lets you pick "Show all in: all files". That will auto-expand all the file- or line-specific dicussions, including resolved ones. You can then hide the N older comments in the main thread without hiding the ones in all other files. This can be an easier way to get back to the discussions without hunting for the faint gray checkmark.

**Comment by rmunn** [comment]
Rebased on top of latest master, which should help fix the flaky E2E tests.

**Review by rmunn — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r7, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/865)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

**Comment by megahirt** [comment]
Per an in-office discussion with @rmunn we've decided to remove the two pid file tests as they provide no value and are improperly mocked such that they don't actually detect the presence or absence of LFMerge.  So a separate PR will delete those.

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/865)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[test/php/model/languageforge/lexicon/command/SendReceiveCommandsTest.php, line 261 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/865#-MVLLnm262YkgaghCszS:-MVWZthL6W6vEKZyBIL6:b-7cjw3l) ([raw file](https://github.com/sillsdev/web-languageforge/blob/c00a6c106ba5f8c5d69977d02a04151ffb8e7898/test/php/model/languageforge/lexicon/command/SendReceiveCommandsTest.php#L261)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

I think https://stackoverflow.com/a/14880926 is a better way to check if a process is running. We can change that in a later PR.
</blockquote></details>

I presume this was discussed and resolved in-office?

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/865)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[docker/api/Dockerfile, line 22 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/865#-MVNK0xh3MCdI2WT8U4o:-MVW_52M5nsJ4M1JKQrN:b-pb2ud0) ([raw file](https://github.com/sillsdev/web-languageforge/blob/c00a6c106ba5f8c5d69977d02a04151ffb8e7898/docker/api/Dockerfile#L22)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

Also, at the top of the Reviewable page where the "main" comments are (the comments on the PR as a whole), there's a "Show N older comments" link, with a dropdown arrow. The dropdown arrow lets you pick "Show all in: all files". That will auto-expand all the file- or line-specific dicussions, including resolved ones. You can then hide the N older comments in the main thread without hiding the ones in all other files. This can be an easier way to get back to the discussions without hunting for the faint gray checkmark.
</blockquote></details>

I'm not seeing that, maybe you can show me that when we're together some time.  Thanks

**Comment by megahirt** [comment]
Yeah, that's right, future PR should fix the implementation.

Kind regards,

Chris

**Pull request merged**
