### PR TITLE
updates to README.md

### PR DESCRIPTION
**Pull request by megahirt**
- deleted sections that are no longer relevant
- updated TeamCity build URLs
- minor style changes

TODO for a future PR
- Testing section needs more organization/explanation.  Right now there are two testing sections.  I hesitate to delete the old section because there is some useful information I'd like to incorporate.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/877)

### CODE REVIEW

**Comment by megahirt** [comment]
FYI #875 must be merged first and this branch rebased for the tests to pass.  I made changes to the build configurations based upon #875, so the CI test results presume those changes exist on master.

**Review by longrunningprocess — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/877)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

**Review by longrunningprocess — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/877)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

**Review by megahirt — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/877)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @megahirt)

**Review by longrunningprocess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/877)* status: all files reviewed, 1 unresolved discussion

___
*[README.md, line 100 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/877#-MW5tgzOBp5g8Mc2DIJ5:-MW5tgzOBp5g8Mc2DIJ6:bg9o1nw) ([raw file](https://github.com/sillsdev/web-languageforge/blob/98a460755a9a7e276d504874a4d0fafd4e7a66ad/README.md#L100)):*
> ```Markdown
> ### Running PHP Unit Tests
> 
> 1. `make test-php`
> ```

are these still accurate (after you added the additional Make targets for TC?

**Review by megahirt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/877)* status: all files reviewed, 1 unresolved discussion

___
*[README.md, line 100 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/877#-MW5tgzOBp5g8Mc2DIJ5:-MW7Cdo_0Nb-HIXycVVW:bca0294) ([raw file](https://github.com/sillsdev/web-languageforge/blob/98a460755a9a7e276d504874a4d0fafd4e7a66ad/README.md#L100)):*
<details><summary><i>Previously, longrunningprocess (billy clark) wrote…</i></summary><blockquote>

are these still accurate (after you added the additional Make targets for TC?
</blockquote></details>

yes, `test-php` still works.  The E2E line needs to be changed, however, to `test-e2e`.  The build step is a make dependency so no longer explicit.  It only builds what is needed, not the whole gorilla.

**Pull request merged**
