### PR TITLE
Feature: sort and filter entries

### PR DESCRIPTION
**Pull request by megahirt**
This PR is not merge-ready (E2E tests are failing) but I'm posting it for code-review.  If someone is available to help with code-review and E2E tests, I am would be grateful.  More details about e2e test failures in the flow.

## Summary

This feature is in response to many users asking for a better way to sort and filter data.  With these new sort and filter capabilities, the user will be able to more easily find entries, and organize the entries in ways that are helpful to their workflow.

## UI Screenshot:
image

## Sort Features

- User can sort by common fields (those fields which are not "hideIfEmpty" in the field config)
- Reverse sort
- sorts on first writing system (multitext)
- For sense level fields, first sense is used
- Compact list display changes to show item being sorted

## Filter Features

- Filter for has data in any common field (user configurable), including all writing systems
- Filter for has comments
- Filter for has pictures
- Filter for has examples
- Filter for has audio
- For sense level fields, first sense is used

## Missing Info Task

These sort/filter features provide the user with a poor man's missing info task, which is what several users have been asking for.  In the future, a full missing info task view could be developed with this code as the base.

## Is it ready to ship?

The e2e tests are failing because of a few small changes I made to the compact list display.  The editor should behave nearly identically if the user does not exercise any sort/filter features.

I have done limited testing and have found it to be working.  I would appreciate you to also give it a try and see if you can break it.

I have not written any e2e tests for this new functionality.  Ideally these would be required for a PR to be accepted but I'm willing to get this merged in so users can use it immediately with the understanding that I will follow up with e2e tests as soon as is reasonable.

I would like to ship this by the end of the week, Aug 4.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/144)

### CODE REVIEW

**Comment by megahirt** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 157 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqDyVhq3w8WD1Mx4diE:-KqDyVhq3w8WD1Mx4diF:b-j06yw6) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L157)):*
> ```JavaScript
> 
>   var removeEntryFromLists = function removeEntryFromLists(id) {
>     angular.forEach([entries, filteredEntries, visibleEntries], function(list) {
> ```

TODO: I refactored this but didn't test deleting an entry to make sure it works as expected.  

---

*[src/angular-app/languageforge/lexicon/views/editor.js, line 75 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqE-5caFroQGPavKYrZ:-KqE-5caFroQGPavKYr_:brh8vib) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/languageforge/lexicon/views/editor.js#L75)):*
> ```JavaScript
>       });
> 
>       // Populate sort and filter option lists based upon dictionary config
> ```

stray comment

---

*[src/angular-app/languageforge/lexicon/views/editor.js, line 724 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqE-MJEawfI9-L2QQw6:-KqE-MJFdK830KUD8sx2:bev2eqs) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/languageforge/lexicon/views/editor.js#L724)):*
> ```JavaScript
>           var entryField = $scope.config.entry.fields[entryFieldKey];
> 
>           // note: do I need to check if user can see field (view settings).  Is this handled somewhere else? - cjh 2017-07-20
> ```

todo: I haven't actually tested these features in conjunction with the view settings... i.e. do the view settings permissions for the user *just work* or do I need to reduce the set of fields based upon the user's permission at this point?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144)*

**Comment by irahopkinson** [comment]
I haven't gone through everything but here is a start. Maybe I will try E2E tomorrow.

---

Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNJTH5o_XKJwZWv6CD:-KqNJTH5o_XKJwZWv6CE:b-yqu35i) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L13)):*
> ```JavaScript
>   var visibleEntries = [];
>   var filteredEntries = [];
>   var entryListModifiers = {sortBy: {label: "Word", value: "lexeme"}, sortOptions: [], filterBy: "", filterOptions: [], sortReverse: false, filterType: "isNotEmpty"};
> ```

**entryListModifiers** is a bit hard to see the structure with it all on one line. Layout as formatted json to clarify.

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 157 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqDyVhq3w8WD1Mx4diE:-KqNK67WjUfxx2oZ-VAI:bf1gtpa) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L157)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

TODO: I refactored this but didn't test deleting an entry to make sure it works as expected.  
</blockquote></details>

Yes, it would be good to have some Karma tests for such as this. I also think we could reduce some of our corner-case E2E testing if we had appropriate Karma tests.

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 304 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNKhtzwPLhzUZfX8gS:-KqNKhtzwPLhzUZfX8gT:bs3jbo7) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L304)):*
> ```JavaScript
>   }
> 
>   function _sortList(config, list) {
> ```

private functions and variables shouldn't use _ at the beginning (https://github.com/airbnb/javascript#naming--leading-underscore)

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 314 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNNudjrF8RLN2MbBy6:-KqNNudjrF8RLN2MbBy7:bv5dxw) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L314)):*
> ```JavaScript
>     mapped.sort(function(a, b) {
>       if (entryListModifiers.sortReverse == true) {
>         return collator.compare(a.value, b.value) * -1;
> ```

       return -collator.compare(a.value, b.value) ;
 would be more compact

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 337 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNOZtuziFE2blRaGoj:-KqNOZtv3syBFzUE4Tu5:b-jc35jf) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L337)):*
>      entries.length = 0;
>       Array.prototype.push.apply(entries, entries_sorted);
Refactor as suitably named function e.g. arrayCopyRetainingReferences(entries, entries_sorted);
The lengthy comment above can go in the new function.
Since this is also used in editor.js, put it in a util service.

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 386 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNZCs0x19drRGGeFdy:-KqNZCs0x19drRGGeFdz:bazbugp) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L386)):*
> ```JavaScript
>   }
> 
>   function entryMeetsFilterCriteria(config, entry) {
> ```

This function **entryMeetsFilterCriteria** is too long. The audio case could go in its own function so could the main else (which has a nice comment at the top indicating the name of the function; comments are often an indicator of possible extract method refactorings).

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 522 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqN_Xnd-fCehAQKSiLK:-KqN_Xnd-fCehAQKSiLL:b-8og6je) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L522)):*
> ```JavaScript
> 
>   function getSortableValue(config, entry) {
>     var field, dataNode, sortableValue = '', fieldKey = entryListModifiers.sortBy.value;
> ```

One line per variable (var), group initialized variables at the top (https://github.com/airbnb/javascript#variables--one-const).

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 535 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNaSnDXiu4R07IMgFj:-KqNaSnDXiu4R07IMgFk:be6x2pv) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L535)):*
> ```JavaScript
>       } else if (field.type == 'optionlist') {
>         if (config.optionlists && config.optionlists[field.listCode]) {
>           // something weird here with config.optionlists not being set consistently when this is called - cjh 2017-07
> ```

This might fix it
if (angular.isDefined(config.optionlists) && (field.listCode in config.optionlists) && angular.isDefined(config.optionlists[field.listCode])) {

---

*[src/angular-app/languageforge/lexicon/sass/_editor.scss, line 79 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNzWY-hiGrTBKgBAac:-KqNzWY-hiGrTBKgBAad:b-aod3nr) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/languageforge/lexicon/sass/_editor.scss#L79)):*
> ```SCSS
> 
> .sortfilter-form {
>   border: 1px solid lightgrey;
> ```

Use _variables.scss; change lightgrey to $lf-lines

---

*[src/angular-app/languageforge/lexicon/views/editor-entry.html, line 4 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqO-4p74a1ZzY5m_sU2:-KqO-4p74a1ZzY5m_sU3:b-43yyfm) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/languageforge/lexicon/views/editor-entry.html#L4)):*
> style="float:right;margin-bottom:5px;margin-top: 5px"
Define a class and use SCSS for margins. Use bootstrap class for pull right (class="pull-right"). Here and below.

---

*[test/app/languageforge/lexicon/pages/editorPage.js, line 140 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqO25CG9Tq1-XgC0_mr:-KqO25CG9Tq1-XgC0_ms:b-vl3kzb) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/test/app/languageforge/lexicon/pages/editorPage.js#L140)):*
> ```JavaScript
>     findEntryByLexeme: function (lexeme) {
>       var div = this.editDiv.element(by.id('compactEntryListContainer'));
>       return div.element(by.cssContainingText('listItemPrimary',
> ```

I don't expect this will work, maybe '.listItemPrimary' would (note the dot to signify class), but I don't remember the syntax without looking it up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-:-KqO44tZgDfG0LZIZlKP:b-p1mvvx)*

**Comment by irahopkinson** [comment]
After having a play I really liked being able to find all the entries with audio. I think this will be a great feature however here are a few things I found:

* The **Options** button is not yet responsive. Between *sm* and *lg* it sits above the typeahead rather than below it.
* I think the filter list should display the Input System **abbreviation** (rather than the full tag).
* I expect you will also add the filter to the list view.
* When sorting by something other than **Word**, display the **Word** in parenthesis (or some other way; sometimes the thing you sort by is empty and you can't tell what's what)
* If I test with *test-chris-02* it all works great. If I test with *test-LangProjIH-FLEx*, select **Filter Entries** has *Word [qaa-Zxxx-x-AUDIO]*. Now change **Sort Entries By** away from *Word* and get console errors (TypeError: Cannot use 'in' operator to search for 'definition' in undefined). **TestLangProj** gives different error (TypeError: Cannot read property '0' of undefined at getSortableValue).

I've also run E2E. Using '.listItemPrimary' helps but the tests just stop at **word with multiple meanings: edit page has correct general notes, sources**. I'll look into that more soon.

---

Review status: 8 of 9 files reviewed at latest revision, 13 unresolved discussions.

---

*[test/app/languageforge/lexicon/pages/editorPage.js, line 140 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqO25CG9Tq1-XgC0_mr:-KqSursa9gHPZLtwk0MU:b-zbk1tm) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/test/app/languageforge/lexicon/pages/editorPage.js#L140)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I don't expect this will work, maybe '.listItemPrimary' would (note the dot to signify class), but I don't remember the syntax without looking it up.
</blockquote></details>

I can confirm '.listItemPrimary' works (i.e. with the dot).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-:-KqSaz_WngnKZ670ggcK:bis8nhr)*

**Comment by irahopkinson** [comment]
Ok, found the next problem with the E2E. The browser is locking up when you hit the **New Word** button. I'd guess something recursive is getting lost in itself in editor.js newEntry().

---

Review status: 8 of 9 files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-:-KqTGqugILvCg2j2jwsB:b-6w5xfa)*

**Comment by megahirt** [comment]
Thank you Ira for all of these suggestions and finds.  I'm running out of time to be able to ship this before second half of August. :(

---

Review status: 4 of 9 files reviewed at latest revision, 14 unresolved discussions.

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNJTH5o_XKJwZWv6CD:-KqXrJnbRc44V77YT2fL:b-7rl0jd) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L13)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

**entryListModifiers** is a bit hard to see the structure with it all on one line. Layout as formatted json to clarify.
</blockquote></details>

done.

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 157 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqDyVhq3w8WD1Mx4diE:-KqXsN3iVM_3iHGOfKDo:bqzf1gp) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L157)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yes, it would be good to have some Karma tests for such as this. I also think we could reduce some of our corner-case E2E testing if we had appropriate Karma tests.
</blockquote></details>

tested this and it seems to be working as advertised

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 304 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNKhtzwPLhzUZfX8gS:-KqXtWJDAhIzLWTiav02:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L304)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

private functions and variables shouldn't use _ at the beginning (https://github.com/airbnb/javascript#naming--leading-underscore)
</blockquote></details>

Done.

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 314 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNNudjrF8RLN2MbBy6:-KqXtXA2xunBheNQTWa4:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L314)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

       return -collator.compare(a.value, b.value) ;
 would be more compact
</blockquote></details>

Done.

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 386 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNZCs0x19drRGGeFdy:-KqXuOEfwFKsfiIB6bfN:b68kuaq) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L386)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This function **entryMeetsFilterCriteria** is too long. The audio case could go in its own function so could the main else (which has a nice comment at the top indicating the name of the function; comments are often an indicator of possible extract method refactorings).
</blockquote></details>

So you are recommending shortening the function so that it reads better.  This is a nice candidate for a class (which is where I'd rather it be) but being JS I left it as a single function.  The logic is complex enough that extracting out functions for readability (not code re-use) makes sense.

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 522 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqN_Xnd-fCehAQKSiLK:-KqXvLNCm5Xs1fvgqFkh:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L522)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

One line per variable (var), group initialized variables at the top (https://github.com/airbnb/javascript#variables--one-const).
</blockquote></details>

Done.

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 535 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNaSnDXiu4R07IMgFj:-KqXvRjU6kAg583bqmGi:b-cwctoh) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L535)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This might fix it
if (angular.isDefined(config.optionlists) && (field.listCode in config.optionlists) && angular.isDefined(config.optionlists[field.listCode])) {

</blockquote></details>

config.optionlist will be undefined in certain initial cases, which the if statement handles currently.  I think the issue is that config.optionlist is set at a later time (is not part of config initially).

---

*[src/angular-app/languageforge/lexicon/sass/_editor.scss, line 79 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNzWY-hiGrTBKgBAac:-KqXwDkYBLCbNZbILO9-:b-tfrs7a) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/languageforge/lexicon/sass/_editor.scss#L79)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Use _variables.scss; change lightgrey to $lf-lines
</blockquote></details>

good call.  done.

---

*[src/angular-app/languageforge/lexicon/views/editor-entry.html, line 4 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqO-4p74a1ZzY5m_sU2:-KqXwLzxAidTJUCTJ4K9:b-ouihzu) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/languageforge/lexicon/views/editor-entry.html#L4)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> style="float:right;margin-bottom:5px;margin-top: 5px"
Define a class and use SCSS for margins. Use bootstrap class for pull right (class="pull-right"). Here and below.
</blockquote></details>

I made some changes but I'm still not happy with what I settled on.  The option button still bumps into the text on the right in the small viewport.  I couldn't figure out how to make it disappear in the small view port and stretch the search input all the way in the same view.  I don't understand responsive bootstrap enough to make it do that :)

---

*[src/angular-app/languageforge/lexicon/views/editor.js, line 75 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqE-5caFroQGPavKYrZ:-KqXx-qV5QAmnD03Iy48:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/languageforge/lexicon/views/editor.js#L75)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

stray comment
</blockquote></details>

Done.

---

*[test/app/languageforge/lexicon/pages/editorPage.js, line 140 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqO25CG9Tq1-XgC0_mr:-KqXxW5Ka6tnU4CZxntg:b-h8g3ty) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/test/app/languageforge/lexicon/pages/editorPage.js#L140)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I can confirm '.listItemPrimary' works (i.e. with the dot).
</blockquote></details>

Thank you Ira!  This is the help I was looking for!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-:-KqXqXNCPnFhz-PuhyCv:b-tpetyx)*

**Comment by megahirt** [comment]
This is now merge-ready.  All e2e tests passing!

---

Review status: 3 of 9 files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-:-KqaGFFt5YqfiVuFvKRL:bsllbqx)*

**Comment by megahirt** [comment]
Review status: 3 of 9 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/angular-app/bellows/js/bellows.services.editorData.js, line 337 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNOZtuziFE2blRaGoj:-KqaGKX9_BsOmLr5i-EA:b4h0ep2) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L337)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

>      entries.length = 0;
>       Array.prototype.push.apply(entries, entries_sorted);
Refactor as suitably named function e.g. arrayCopyRetainingReferences(entries, entries_sorted);
The lengthy comment above can go in the new function.
Since this is also used in editor.js, put it in a util service.
</blockquote></details>

This is a good idea.  I didn't get to it this time but would like to try and do this soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144)*

**Comment by irahopkinson** [comment]
*[src/angular-app/bellows/js/bellows.services.editorData.js, line 337 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNOZtuziFE2blRaGoj:-KqbFBEnR1lhlGir6ga2:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L337)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

This is a good idea.  I didn't get to it this time but would like to try and do this soon.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144)*

**Comment by irahopkinson** [comment]
*[src/angular-app/bellows/js/bellows.services.editorData.js, line 386 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqNZCs0x19drRGGeFdy:-KqbI_11j4tyrbA_rUeU:b-boy5qx) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L386)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

So you are recommending shortening the function so that it reads better.  This is a nice candidate for a class (which is where I'd rather it be) but being JS I left it as a single function.  The logic is complex enough that extracting out functions for readability (not code re-use) makes sense.
</blockquote></details>

Yes, for readability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144)*

**Comment by irahopkinson** [comment]
*[src/angular-app/bellows/js/bellows.services.editorData.js, line 522 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqN_Xnd-fCehAQKSiLK:-KqaPHXz6-m9zpOyq0Gk:bws8i5m) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/bellows/js/bellows.services.editorData.js#L522)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I forgot to mention that AirBNB style guide has moved on to ES6+.  I've replaced **const** with **var** to keep compatibility. (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const not so good on mobile)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144)*

**Comment by irahopkinson** [comment]
*[src/angular-app/languageforge/lexicon/views/editor-entry.html, line 4 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqO-4p74a1ZzY5m_sU2:-KqazYhneZA7oOYXxTIN:b-pqdiv4) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/languageforge/lexicon/views/editor-entry.html#L4)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

I made some changes but I'm still not happy with what I settled on.  The option button still bumps into the text on the right in the small viewport.  I couldn't figure out how to make it disappear in the small view port and stretch the search input all the way in the same view.  I don't understand responsive bootstrap enough to make it do that :)
</blockquote></details>

I've fixed this now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144)*

**Comment by irahopkinson** [comment]
*[src/angular-app/languageforge/lexicon/views/editor.js, line 724 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-KqE-MJEawfI9-L2QQw6:-KqazvR51CdfbKi2wdGx:b-32sou3) ([raw file](https://github.com/sillsdev/web-languageforge/blob/81e0750d5c9d99538349ac51d9435fee6cd1cea6/src/angular-app/languageforge/lexicon/views/editor.js#L724)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

todo: I haven't actually tested these features in conjunction with the view settings... i.e. do the view settings permissions for the user *just work* or do I need to reduce the set of fields based upon the user's permission at this point?
</blockquote></details>

I think this still needs checking. We already have some funkiness with view settings so it almost certainly needs some work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144)*

**Comment by irahopkinson** [comment]
I've done just about all the rest of the suggestions I made. I haven't added the filter to the list view nor displayed the **Word** when the sortable value is *[Empty]*. I haven't refactored **entryMeetsFilterCriteria** to make it more readable because that would be easier for you to do.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/144#-:-Kqb-Rmv9a5QIl0cLhAE:b-zaskp9)*

**Pull request merged**
