### PR TITLE
upgrade mongodb to 4.4

### LINKED ISSUE #1520: Upgrade mongo to 4.4
upgrading to 5+ is going to require some intermediate steps:  https://www.mongodb.com/docs/manual/release-notes/5.0-upgrade-standalone/#upgrade-version-path

I'd recommend we open another issue taking things to 4.4 next: https://www.mongodb.com/docs/manual/release-notes/4.4-upgrade-standalone/

_Originally posted by @longrunningprocess in https://github.com/sillsdev/web-languageforge/issues/1173#issuecomment-1272021769_

### PR DESCRIPTION
**Pull request by longrunningprocess**
Fixes #1520 

## Description

There is a desire to utilize aggregation pipelines and take advantage of possible perf improvements.

### Type of Change

- infrastructure upgrade

## Screenshots

N/A

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have reviewed the title/description of this PR which will be used as the squashed PR commit message
- [ ] Create an issue for the upgrade to 5.0 and reference https://www.mongodb.com/docs/v5.0/release-notes/4.4-upgrade-standalone/
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works

## How to test

Please describe how to test and/or verify your changes. Provide instructions so we can reproduce. Please also provide relevant test data as necessary. These instructions will be used for QA testing below.

- A general smoke test in addition to successful automated tests should be enough to move forward with this one.  [upgrade mongo to 4.2](https://github.com/sillsdev/web-languageforge/pull/1519#top) is a good reference as well.

## qa.languageforge.org testing

Testers: Check the box and put in a date/time to sign-off/attest the feature works as expected on qa.languageforge.org

- [ ] Tester1 (YYYY-MM-DD HH:MM)
- [ ] Tester2 (YYYY-MM-DD HH:MM)

### CODE REVIEW

**Comment by megahirt** [comment]
I read the documentation on upgrading to 4.4 from 4.2 and there doesn't seem to be anything actionable, so seeing how the tests pass, this looks good to go

**Review by megahirt — APPROVED** [review]
LGTM thanks!

**Comment by longrunningprocess** [comment]
> I read the documentation on upgrading to 4.4 from 4.2 and there doesn't seem to be anything actionable, so seeing how the tests pass, this looks good to go 

Agreed, it seemed the same to me

**Comment by longrunningprocess** [comment]
created #1568

**Comment by megahirt** [comment]
I tested this by verifying that QA is functioning normally (utilizing the mongodb database as expected)

**Pull request merged**
