### PR TITLE
establish new env var usage approach

### PR DESCRIPTION
**Pull request by longrunningprocess**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/902)

### CODE REVIEW

**Comment by longrunningprocess** [comment]
Now, when an ENV var is not provided, the app will do this:
image

**Comment by longrunningprocess** [comment]
within unit test:
image

**Comment by longrunningprocess** [comment]
going ahead an opening for review but I suspect I'll need tweak something in TC but I'm not 100% sure yet and once approved, I'll need to tweak k8s and bring the `build-n-publish-images` tag to the merged commit.

**Review by megahirt — CHANGES_REQUESTED** [review]
Looks good.

Per our conversation, request two changes:
- keep the line in Auth.php
- use ENVIRONMENT=development instead of testing

> Reviewed 3 of 3 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/902#-:-MXbdgNg7fRXRvWWqjhO:b-cy8sfi)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @longrunningprocess and @megahirt)

___
*[docker/docker-compose.yml, line 159 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/902#-MXbdWu31LAuSwNRKjyE:-MXbdWu31LAuSwNRKjyF:bt15edb) ([raw file](https://github.com/sillsdev/web-languageforge/blob/eb98773223c72998488d419859d1e72c37fdef4a/docker/docker-compose.yml#L159)):*
> ```YAML
>       - WAIT_HOSTS=db:27017, mail:25
>       - "LDAPI_BASE_URL=http://ld-api:3000/api/v2/"
>       - ENVIRONMENT=testing
> ```

I honestly don't know if our code has ever been run with ENVIRONMENT=testing

I think we should keep it as ENVIRONMENT=development
___
*[src/Site/Controller/Auth.php, line 21 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/902#-MXbbrub5gZ3QnIjAP9v:-MXbbrub5gZ3QnIjAP9w:b-xtockf) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5ce2775bcc781b2f9d167f28cd5918f6520cfdd4/src/Site/Controller/Auth.php#L21)):*
> ```PHP
> use Symfony\Component\Security\Core\Security;
> 
> defined('ENVIRONMENT') or exit('No direct script access allowed');
> ```

I think we should keep this around for security reasons.

**Review by megahirt — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/902)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @longrunningprocess)

___
*[docker/docker-compose.yml, line 159 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/902#-MXbdWu31LAuSwNRKjyE:-MXbfoX_9Fx3KPgDBF8j:b-47fafm) ([raw file](https://github.com/sillsdev/web-languageforge/blob/eb98773223c72998488d419859d1e72c37fdef4a/docker/docker-compose.yml#L159)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

I honestly don't know if our code has ever been run with ENVIRONMENT=testing

I think we should keep it as ENVIRONMENT=development
</blockquote></details>

looks good
___
*[src/Site/Controller/Auth.php, line 21 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/902#-MXbbrub5gZ3QnIjAP9v:-MXbftPdD8O7SFExWLfz:bd5l6n4) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5ce2775bcc781b2f9d167f28cd5918f6520cfdd4/src/Site/Controller/Auth.php#L21)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

I think we should keep this around for security reasons.
</blockquote></details>

thanks.

**Pull request merged**
