### PR TITLE
convert dcText and dcAudio to TypeScript

### PR DESCRIPTION
**Pull request by irahopkinson**
- simplify dcText (removed TextAngular customizations)
 - convert Show Overflow directive to TypeScript

I was going to do more in the `lexicon/editor/field/` folder but this looks like quite enough to review already.

LF E2E tests passing.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/216)

### CODE REVIEW

**Comment by ddaspit** [comment]
Looks good. I just had one suggestion about the signature for directives.

---

Reviewed 45 of 50 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/angular-app/bellows/apps/changepassword/change-password-app.module.ts, line 3 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/216#-L9PH5W7BdrO7LgX7sWZ:-L9PH5W7BdrO7LgX7sW_:b-cgg8ho) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4bd7f2880367561b8f085ac2d94364c191c4134d/src/angular-app/bellows/apps/changepassword/change-password-app.module.ts#L3)):*
> ```XML
> import * as angular from 'angular';
> 
> import {CoreModule} from '../../core/core.module';
> ```

I noticed that you are getting rid of the spaces in the curly braces. Is that a code style thing that PhpStorm is suggesting?

---

*[src/angular-app/bellows/shared/utils/pui-show-overflow.directive.ts, line 3 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/216#-L9PKVyl2M8k_PS20Yqf:-L9PKVyl2M8k_PS20Yqg:b-4mdw4j) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4bd7f2880367561b8f085ac2d94364c191c4134d/src/angular-app/bellows/shared/utils/pui-show-overflow.directive.ts#L3)):*
> ```XML
> import * as angular from 'angular';
> 
> export const PuiShowOverflow = () => ({
> ```

I know that the other directives were done like this, but I think that the directives would be more clear with a signature like
`export function PuiShowOverflow(): angular.IDirective {`
I think something like that would work.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/216#-:-L9PMcFU2PM98WKB8Ta8:b-m0lnr)*

**Comment by irahopkinson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/angular-app/bellows/apps/changepassword/change-password-app.module.ts, line 3 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/216#-L9PH5W7BdrO7LgX7sWZ:-L9SD3cu3eKvHWZKDNEd:bb8zctr) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4bd7f2880367561b8f085ac2d94364c191c4134d/src/angular-app/bellows/apps/changepassword/change-password-app.module.ts#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I noticed that you are getting rid of the spaces in the curly braces. Is that a code style thing that PhpStorm is suggesting?
</blockquote></details>

Yes, when it automatically adds an `import` statement when you are typing an exported item name or if you use the TSLint fix-it to reorder them in alphabetical order. I thought I would stop fighting PhpStorm. Does VSCode format with spaces? Can that style be specified in the TSLint config?

---

*[src/angular-app/bellows/shared/utils/pui-show-overflow.directive.ts, line 3 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/216#-L9PKVyl2M8k_PS20Yqf:-L9SE-Vf2zTzl_9hDDah:b-akh57g) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4bd7f2880367561b8f085ac2d94364c191c4134d/src/angular-app/bellows/shared/utils/pui-show-overflow.directive.ts#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I know that the other directives were done like this, but I think that the directives would be more clear with a signature like
`export function PuiShowOverflow(): angular.IDirective {`
I think something like that would work.
</blockquote></details>

I looked at various signatures last year and I settled on this one because it seemed to be the simplest style. I'm happy to change if you think it warrants it. What is the rational and advantage of changing? How about I experiment and add a commit with the change. If it works out I can squash the extra commit or discard it as appropriate before merging.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/216)*

**Comment by irahopkinson** [comment]
This new commit changes the directive signatures. If you're happy with that I'll squash before merge.

---

Review status: 36 of 40 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/216#-:-L9SQXAL9Uthng1CpDjK:b-exghmn)*

**Comment by megahirt** [comment]
:lgtm:

---

Reviewed 4 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/216#-:-L9V5J4XE7xy4ou5iEP5:bnfp4nl)*

**Comment by megahirt** [comment]
Looks like waiting on @ddaspit for final approval in reviewable

**Comment by ddaspit** [comment]
:lgtm:

---

Reviewed 4 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/angular-app/bellows/apps/changepassword/change-password-app.module.ts, line 3 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/216#-L9PH5W7BdrO7LgX7sWZ:-L9cUZ6p3mPuv46PSMi_:b-j8xq4u) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4bd7f2880367561b8f085ac2d94364c191c4134d/src/angular-app/bellows/apps/changepassword/change-password-app.module.ts#L3)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yes, when it automatically adds an `import` statement when you are typing an exported item name or if you use the TSLint fix-it to reorder them in alphabetical order. I thought I would stop fighting PhpStorm. Does VSCode format with spaces? Can that style be specified in the TSLint config?
</blockquote></details>

OK. I'm not sure if it can be configured in VSCode. I'll check.

---

*[src/angular-app/bellows/shared/utils/pui-show-overflow.directive.ts, line 3 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/216#-L9PKVyl2M8k_PS20Yqf:-L9cUrpB56HH0QuuxPGI:b-12oysx) ([raw file](https://github.com/sillsdev/web-languageforge/blob/4bd7f2880367561b8f085ac2d94364c191c4134d/src/angular-app/bellows/shared/utils/pui-show-overflow.directive.ts#L3)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I looked at various signatures last year and I settled on this one because it seemed to be the simplest style. I'm happy to change if you think it warrants it. What is the rational and advantage of changing? How about I experiment and add a commit with the change. If it works out I can squash the extra commit or discard it as appropriate before merging.
</blockquote></details>

Looks good. I like that it looks like a normal function instead of an arrow function and that the return type is more up front instead of being hidden at the bottom.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/216#-:-L9cVUJDCO-8HR-MJzkm:bnfp4nl)*

**Pull request merged**
