### PR TITLE
Filter retaining while refreshing the screen

### PR DESCRIPTION
**Pull request by Umasengoden**
Two tasks : Anchorscroll to focus on the searched word

** Filter data to be retained even after refreshing the screen.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/285)

### CODE REVIEW

**Comment by irahopkinson** [comment]
BTW your PR didn't state if E2E is still passing so I checked out your branch and you have failing E2E. All tests must be passing before submitting a PR.

On the whole, well done with getting this functionality working. There are probably some cases you didn't think of and the E2E are likely alerting you to that.

Do use TSLint.

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed, 10 unresolved discussions (waiting on @Umasengoden)

---

*[src/angular-app/languageforge/lexicon/editor/editor-entry.view.html, line 1 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LEluwiMCJ9MM8awHYSI:-LEluwiOCMf0psfb1Oxc:b-p8aq61) ([raw file](https://github.com/sillsdev/web-languageforge/blob/3665678382457e340745523b264cb4d54f6ba3e3/src/angular-app/languageforge/lexicon/editor/editor-entry.view.html#L1)):*
> ```
> ng-init="$ctrl.setUrlParams()"
> ```
Is there some reason this needs to be here rather than in `$onInit()`?

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 18 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LElyDGf6-AOADIpUTmT:-LElyDGf6-AOADIpUTmU:bu6jyzr) ([raw file](https://github.com/sillsdev/web-languageforge/blob/3665678382457e340745523b264cb4d54f6ba3e3/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L18)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> import { LexiconUtilityService } from '../core/lexicon-utility.service';
> import { LexEntry } from '../shared/model/lex-entry.model';
> import { LexPicture } from '../shared/model/lex-picture.model';
>  
> import {
> ```
</details>

Style: please remove this added whitespace including the extra blank line.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 93 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LElydrfBb3m5L2zKzmU:-LElydrfBb3m5L2zKzmV:btctv8o) ([raw file](https://github.com/sillsdev/web-languageforge/blob/3665678382457e340745523b264cb4d54f6ba3e3/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L93)):*
> ```
> '$anchorScroll', '$filter'
> ```
Style: external dependencies go first and should be alphabetical in order.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 101 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LElzDVr4RSK8lO9-lxr:-LElzDVr4RSK8lO9-lxs:b-ti171k) ([raw file](https://github.com/sillsdev/web-languageforge/blob/3665678382457e340745523b264cb4d54f6ba3e3/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L101)):*
> ```
> ,
> ```
Style: no trailing commas. Are you using the linter? Setup your IDE to use TSLint; the config file is in the repo `\tslint.json` If you can't do that at least run the linter manually.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 103 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LElyR5_DdpfcsV5wT3H:-LElyR5_DdpfcsV5wT3I:bhoefco) ([raw file](https://github.com/sillsdev/web-languageforge/blob/3665678382457e340745523b264cb4d54f6ba3e3/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L103)):*
> ```XML
>     'lexSendReceive',
>   ];
> ```

Style:  `$inject` and `constructor` are intimately linked. Remove the blank line between them.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 118 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LElzmoY6sPJXl_kPvpt:-LElzmoY6sPJXl_kPvpu:b-3ol0pz) ([raw file](https://github.com/sillsdev/web-languageforge/blob/3665678382457e340745523b264cb4d54f6ba3e3/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L118)):*
> ```
> ··············
> ```
Style: this should be a blank line without spaces. Use TSLint.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 137 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LEm-8x6AJWS7Mu9tdC1:-LEm-8x6AJWS7Mu9tdC2:b2rv2tg) ([raw file](https://github.com/sillsdev/web-languageforge/blob/3665678382457e340745523b264cb4d54f6ba3e3/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L137)):*
> ```
>  setUrlParams(): void {
> ```
There are a number of style issues in this function. Use TSLint.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 400 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LEm4JpzElMd-V3VuAxH:-LEm4Jq-1K3EPm-DOOuw:bdh13m0) ([raw file](https://github.com/sillsdev/web-languageforge/blob/3665678382457e340745523b264cb4d54f6ba3e3/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L400)):*
> ```
> $anchorScroll('entryId_' + id);
> ```
Is this code important to this PR? You shouldn't be slipping in code from another PR especially when that other PR is needing E2E tests.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 917 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LEm7Ko33wEfsHTKRGhR:-LEm7Ko33wEfsHTKRGhS:bp04ge8) ([raw file](https://github.com/sillsdev/web-languageforge/blob/0b7f0d2cbcfc9f9f9bd4fcb08ca7da37a8f2cf80/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L917)):*
> ```
>       if (entryField.hideIfEmpty) {
>         return;
>       }
> ```
Why is this being removed? At the very least the comment above should have been removed with it.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 925 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LEm7Vpo8wCdfazkYhVq:-LEm7Vpo8wCdfazkYhVr:bxgay2g) ([raw file](https://github.com/sillsdev/web-languageforge/blob/0b7f0d2cbcfc9f9f9bd4fcb08ca7da37a8f2cf80/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L925)):*
> ```
>           if (senseField.hideIfEmpty || senseField.type === 'fields') {
>             return;
>           }
> ```
Why is this being removed?

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-:-LEm7zbcC8-ljpGiSZjL:b-ndwclo)*

**Comment by jasonleenaylor** [comment]
*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 917 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LEm7Ko33wEfsHTKRGhR:-LEntWyq1mH2zpICShQv:b-qbul0h) ([raw file](https://github.com/sillsdev/web-languageforge/blob/0b7f0d2cbcfc9f9f9bd4fcb08ca7da37a8f2cf80/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L917)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>       if (entryField.hideIfEmpty) {
>         return;
>       }
> ```
Why is this being removed? At the very least the comment above should have been removed with it.
</blockquote></details>

Yes, the comment should be removed. As for removing the code hideIfEmpty refers to how data for a specific entry is shown, this code is dealing with listing fields to sort by. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/285)*

**Comment by jasonleenaylor** [comment]
*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 925 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LEm7Vpo8wCdfazkYhVq:-LEntI0t0TRFyM4k8py8:bei0zbo) ([raw file](https://github.com/sillsdev/web-languageforge/blob/0b7f0d2cbcfc9f9f9bd4fcb08ca7da37a8f2cf80/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L925)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>           if (senseField.hideIfEmpty || senseField.type === 'fields') {
>             return;
>           }
> ```
Why is this being removed?
</blockquote></details>

Uma, I think the senseField.type ==='fields' should stay.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/285)*

**Comment by Umasengoden** [comment]
senseField.hideIfEmpty is true and so it got return.

**Comment by Umasengoden** [comment]
As per Jason suggestion, we are trying to run test cases and share you feedback.

**Comment by Umasengoden** [comment]
**  ng-init="$ctrl.setUrlParams()"  --- OnInit could not be used since initial parameters are populated on URL and so we used ng-init.
**  '$anchorScroll', '$filter'   --- WE have remove anchorscroll code changes since it is different task.
**  remove unnecessary commas and empty spaces.
**   if (entryField.hideIfEmpty) {
        return;
      }  These lines to be removed since jideIfEmpty returns true.
**    if (senseField.hideIfEmpty || senseField.type === 'fields') {
            return;
          }  -- Again these lines to be removed for the above reason given

**Comment by irahopkinson** [comment]
BTW use the **Reviewable** link in Github for interacting with Pull Requests (PR). You must respond to all questions in context of how they are asked otherwise the PR review is held up.

LF E2E tests are still failing.

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed, 5 unresolved discussions (waiting on @Umasengoden and @irahopkinson)

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 917 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LEm7Ko33wEfsHTKRGhR:-LF0ECS25OL3dbSbpQdu:b80ogop) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5159e208a4680cc9352dc8deffcbaf25b1e130f3/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L917)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Yes, the comment should be removed. As for removing the code hideIfEmpty refers to how data for a specific entry is shown, this code is dealing with listing fields to sort by. 
</blockquote></details>

Yes, I think the intention of the code is that if a field is hidden we don't want to sort on it.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 106 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LF02rxM2641DUlzlRr0:-LF02rxN5yhnz4qwDXzV:b7mxl8v) ([raw file](https://github.com/sillsdev/web-languageforge/blob/db6a907f978c4d545e8b943c7b942d5846080a89/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L106)):*
> ```
> private readonly $filter: angular.IFilterService,
> ```
You have moved `$filter` to the front of `$inject` but you haven't moved it here in the constructor. They must be in the same order.

The way it is at the moment causes a number of console errors so E2E tests will definitely fail because of this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-:-LF0A8AY2tx4kfZ_dTOR:b-29efec)*

**Comment by irahopkinson** [comment]
FYI I've just pushed to your branch because I wanted to check what was really failing on the **LF E2E tests** so I had to tidy up a few things and merge in a fix from **master**. Please pull from Github **before** making further changes to this branch.

There are 3 failing LF E2E tests which I think are to do with your changed URL:
```
1) Lexicon E2E Editor List and Entry first entry is selected if entryId unknown
  - Failed: Wait timed out after 3010ms

2) Lexicon E2E Editor List and Entry URL entry id changes with entry
  - Expected '' to match /[0-9a-z_]{6,24}/.
  - Failed: No element found using locator: By(css selector, *[id="lexAppEditView"])

3) Lexicon E2E Editor List and Entry new word is visible in browse page
  - Failed: element not visible
    (Session info: chrome=66.0.3359.181)
    (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.4.0-21-generic x86_64)
```
With E2E its always best to deal with the first failure then re-run the tests as often the first one causes the others to fail. You don't need to run all the tests since the rest are passing. Just run `./rune2e.sh lf --specs editor-entry`. Make sure the selenium server is running first (see `/README.md`) for how to run E2E tests.

---

Review status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @irahopkinson, @Umasengoden, and @jasonleenaylor)

---

*[src/angular-app/languageforge/lexicon/editor/editor-entry.view.html, line 1 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LEluwiMCJ9MM8awHYSI:-LF0YMN29W6oxyQcPpHU:b-2348a) ([raw file](https://github.com/sillsdev/web-languageforge/blob/ed3f9f27e594767793e726edd69fddb4668bded9/src/angular-app/languageforge/lexicon/editor/editor-entry.view.html#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> ng-init="$ctrl.setUrlParams()"
> ```
Is there some reason this needs to be here rather than in `$onInit()`?
</blockquote></details>

Alright, this works, but you will need to add it to the `editor-list.view.hmtl` file as well since that also has the same filter.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 106 at r3](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LF02rxM2641DUlzlRr0:-LF0_OGV4rssiZBGnFtU:bb6un1j) ([raw file](https://github.com/sillsdev/web-languageforge/blob/db6a907f978c4d545e8b943c7b942d5846080a89/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L106)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> private readonly $filter: angular.IFilterService,
> ```
You have moved `$filter` to the front of `$inject` but you haven't moved it here in the constructor. They must be in the same order.

The way it is at the moment causes a number of console errors so E2E tests will definitely fail because of this.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-:-LF0YvE8ACxZuEq7nOJ8:b-s7f01x)*

**Comment by irahopkinson** [comment]
Reviewed 1 of 1 files at r5.
Review status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @irahopkinson, @Umasengoden, and @jasonleenaylor)

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/285)*

**Comment by irahopkinson** [comment]
FYI E2E passing again. This is really close to being ready.

One thing I find annoying is on refresh it opens the filter options. I'd prefer it to stay as I left it (closed in my case).

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed, 3 unresolved discussions (waiting on @Umasengoden, @jasonleenaylor, and @irahopkinson)

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-:-LFUsC6uCqCTM_WX53u7:bgnfhcw)*

**Comment by irahopkinson** [comment]
Reviewed 2 of 4 files at r7, 1 of 1 files at r8.
Review status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @jasonleenaylor)

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/285)*

**Comment by jasonleenaylor** [comment]
*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 917 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LEm7Ko33wEfsHTKRGhR:-LFbPdNbEkfaOfRBXQQH:bvo858i) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5159e208a4680cc9352dc8deffcbaf25b1e130f3/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L917)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

And if you can sort on it but its hidden you won't see what you expect.
</blockquote></details>

Right, if LanguageForge has a way of hiding fields from the view that should be used here. As it is this code functions properly with these changes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/285)*

**Comment by irahopkinson** [comment]
Reviewed 1 of 4 files at r7.
Review status: all files reviewed, 5 unresolved discussions (waiting on @Umasengoden)

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 917 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LEm7Ko33wEfsHTKRGhR:-LFp3WS911PG4fXGdQpW:b86me1f) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5159e208a4680cc9352dc8deffcbaf25b1e130f3/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L917)):*
`this.lecConfig` and the `hideIfEmpty` fields within it **are** the way LF hides fields from view!
> As it is this code functions properly with these changes.
But there are more fields than there should be in the options.

Now I see the problem. The `for` loop used to loop calling a function so calling `return` used to work. Put the `if` back in and change the `return;` to `break;` to restore functionality.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 925 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LEm7Vpo8wCdfazkYhVq:-LFp9il6BQIU84ADsHJY:b-c77i3q) ([raw file](https://github.com/sillsdev/web-languageforge/blob/5159e208a4680cc9352dc8deffcbaf25b1e130f3/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L925)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Uma, I think the senseField.type ==='fields' should stay.
</blockquote></details>

The `for` loop used to loop calling a function so calling `return` used to work. Put the `if` back in and change the `return;` to `break;` to restore functionality.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 150 at r8](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LFp2y_y8BBA48QTRaTJ:-LFp2y_y8BBA48QTRaTK:b-dies1z) ([raw file](https://github.com/sillsdev/web-languageforge/blob/544884f81d79a5c160fce1508b4f95d89b724fe6/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L150)):*
> ```
> hasFilter()
> ```
This function needs a better name and the indenting needs fixing.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 242 at r8](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LFp2_iUAfZOEWkfNYw-:-LFp2_iUAfZOEWkfNYw0:b8k5rde) ([raw file](https://github.com/sillsdev/web-languageforge/blob/544884f81d79a5c160fce1508b4f95d89b724fe6/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L242)):*
> ```XML
>   }
> 
>   setUrlParams(): void {
> ```

The style changes between methods `setUrlParams()` and `resetEntryListFilter()` are quite unhelpful. Revert them.

---

*[src/angular-app/languageforge/lexicon/editor/editor.component.ts, line 1292 at r8](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-LFp1d-E5UEB4n10aLy3:-LFp1d-E5UEB4n10aLy4:b1jqxy9) ([raw file](https://github.com/sillsdev/web-languageforge/blob/544884f81d79a5c160fce1508b4f95d89b724fe6/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L1292)):*
> ```
> private readonly $state: angular.ui.IStateService
> ```
This injected service that has been added is unused. Remove it again.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/285)*

**Comment by irahopkinson** [comment]
:lgtm: LF E2E tests all passing now.
Thanks for persisting with this and for all those who contributed.

---

Reviewed 3 of 3 files at r9.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/285#-:-LFpMlyG4C-JmT2w_R6b:b-s16743)*

**Pull request merged**
