### PR TITLE
remove navbar AngularJS own app (now single AngularJS app)

### PR DESCRIPTION
**Pull request by irahopkinson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/212)

### CODE REVIEW

**Comment by megahirt** [comment]
Ira, this is really great.  I've been wanting to remove this cruft (that I added a year ago) for a while now.  My one suggestion for this PR is to remove the help folders and md files that are checked-in to the folder structure.  That should remove the last trace of the "help" feature.

A second question, not really about this PR, is do you have a a preferred strategy for bootstrapping the angular app on the body element so that the entire page can be angularJS-ified?  This would be required for Nigel's finishing of the new LF theme.  I wonder if it's really that simple to move the id="app-container" attribute to the body tag?

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/angular-app/bellows/core/core.module.ts, line 16 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/212#-L9Jev_i5ru0MPyYMEZ3:-L9Jev_i5ru0MPyYMEZ4:bmswh4v) ([raw file](https://github.com/sillsdev/web-languageforge/blob/ce2e5a220619cb24de3a59f3c519ecd5f42d2fc2/src/angular-app/bellows/core/core.module.ts#L16)):*
> ```XML
> import { SessionService } from './session.service';
> import { UtilityService } from './utility.service';
> import { NoticeService } from './notice/notice.service';
> ```

Is this unused?  I can't remember where exactly, but the E2E typescript PR that I did added the NoticeService to something so that the Activity Feed could have a notification.  This could be unrelated.

---

*[src/Site/views/languageforge/container/languageforge.html.twig, line 11 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/212#-L9Ji73Q3fgCvc2jYhKR:-L9Ji73Q3fgCvc2jYhKS:b-m2yg96) ([raw file](https://github.com/sillsdev/web-languageforge/blob/16a22790fb82084d2b90a4c9d08f665bba06e06a/src/Site/views/languageforge/container/languageforge.html.twig#L11)):*
> ```Twig
>     {% if isLoggedIn %}
> 
>         <nav class="fixed-nav-bar navbar navbar-expand navbar-dark align-items-stretch" style="background-color: #104060" data-ng-controller="navbarController as $ctrl">
> ```

How does this even work?  I thought that the "app-container" is bootstrapped in a div that is farther down from here... I assume you've tested that this change works.  I just don't understand *how* it works 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/212#-:-L9JgxrPAN3DmiUocBv2:b-unyxi)*

**Comment by irahopkinson** [comment]
Removed `helps/**/*.md` files. Done.

It is bootstrapping from the body. See my response to your question below. The `id="app-container"` needs to stay where it is; that's why it was renamed.

---

Review status: 21 of 42 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/angular-app/bellows/core/core.module.ts, line 16 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/212#-L9Jev_i5ru0MPyYMEZ3:-L9KIUuj6HLkmQdD7iA-:b787dsd) ([raw file](https://github.com/sillsdev/web-languageforge/blob/ce2e5a220619cb24de3a59f3c519ecd5f42d2fc2/src/angular-app/bellows/core/core.module.ts#L16)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

Is this unused?  I can't remember where exactly, but the E2E typescript PR that I did added the NoticeService to something so that the Activity Feed could have a notification.  This could be unrelated.
</blockquote></details>

Kristopher added the `NoticeService` to the `CoreModule` on this commit 55de73476ca8e9f49486845ccf3f0aee9696673f. I did question that change at the time. I don't think its necessary or appropriate. Really the `NoticeService` could be moved to the `shared` folder rather than the `core` folder.

---

*[src/Site/views/languageforge/container/languageforge.html.twig, line 11 at r1](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/212#-L9Ji73Q3fgCvc2jYhKR:-L9KF1PoAOph7pnOjPOI:b-mkb8ie) ([raw file](https://github.com/sillsdev/web-languageforge/blob/16a22790fb82084d2b90a4c9d08f665bba06e06a/src/Site/views/languageforge/container/languageforge.html.twig#L11)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

How does this even work?  I thought that the "app-container" is bootstrapped in a div that is farther down from here... I assume you've tested that this change works.  I just don't understand *how* it works 
</blockquote></details>

Yep all tested (I think you should know that I always test - well almost always). Look in `src/Site/views/shared/page/angular-app.html.twig`. I renamed `app-container` from `app-container-for-bootstrap` because its no longer bootstrapped there but from the body (ready for Nigel).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/212#-:-L9KLhyQBOEUpSYEFDTl:b-cqofb1)*

**Comment by irahopkinson** [comment]
Review status: 21 of 42 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Site/views/shared/page/angular-app.html.twig, line 10 at r2](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/212#-L9OGH6_8ebchvCiMXnI:-L9OGH6_8ebchvCiMXnJ:b-7rjpve) ([raw file](https://github.com/sillsdev/web-languageforge/blob/616833844f83c9c878e0e3b0663aab37689a0b7b/src/Site/views/shared/page/angular-app.html.twig#L10)):*
> ```Twig
>     <script>
>       'use strict';
>        angular.bootstrap(document.body, ['{{ appName }}'], { strictDi: true });
> ```

Here is where it bootstraps off the body element.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/212)*

**Comment by irahopkinson** [comment]
Review status: 21 of 42 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Site/views/shared/page/angular-app.html.twig, line 10 at r2](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/212#-L9OK_sy3anYeBqNlqL1:-L9OK_sy3anYeBqNlqL2:b-fowruw) ([raw file](https://github.com/sillsdev/web-languageforge/blob/3cc883b7f2c49bfbe7dab21410f3857ab6838400/src/Site/views/shared/page/angular-app.html.twig#L10)):*
> ```Twig
>     <script>
>       'use strict';
>        angular.bootstrap(document.body, ['{{ appName }}'], { strictDi: true });
> ```

This is where the body element is bootstrapped.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/212)*

**Comment by megahirt** [comment]
:lgtm:

---

Reviewed 21 of 21 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/web-languageforge/212#-:-L9UYT2P-iWf2yHeASxV:bnfp4nl)*

**Pull request merged**
