### PR TITLE
upgrade to mongodb 4.4

### LINKED ISSUE #1587: bug: upgrade to mongodb 4.4
**Describe the bug**

While we made all the necessary config updates in #1520  , I failed to deploy those config changes properly.  As a result, our app had continued running on 4.0 until #1585  .

**To Reproduce**

`grep`-ing the db container logs for 'db version v4.' will reveal the running version.

**Expected behavior**

The running db version should match the db version in `docker/deployment/db-deployment.yaml`

**Screenshots**

N/A

**Desktop (please complete the following information):**

N/A

**Mobile (please complete the following information):**

N/A

**Android App in Google Play**

N/A

**Additional context**

This deployment was never built into the automated deployments since it changes so rarely and requires scaling down the app first to get a good db shutdown.  See https://github.com/sillsdev/web-languageforge/blob/develop/docs/RELEASE.md#database-upgrades for further details

### PR DESCRIPTION
**Pull request by longrunningprocess**
Fixes #1587 

## Description

This PR seeks to upgrade mongo from 4.2 to 4.4

### References

https://www.mongodb.com/docs/manual/release-notes/4.4-upgrade-standalone
https://github.com/sillsdev/web-languageforge/blob/develop/docs/RELEASE.md#database-upgrades

### Type of Change

- database upgrade

## Screenshots

N/A

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have reviewed the title & description of this PR which I will use as the squashed PR commit message
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have enabled auto-merge (optional)

## How to test

- General smoke test of application
- see https://github.com/sillsdev/web-languageforge/blob/develop/docs/RELEASE.md#database-upgrades for further instructions

## qa.languageforge.org testing

Testers should add his/her findings to end of the PR in a comment and include screenshots, files, etc that are beneficial.

### CODE REVIEW

**Comment by longrunningprocess** [comment]
# driver

https://www.mongodb.com/docs/drivers/php/#compatibility-table-legend

```
# pecl search mongo
Retrieving data...0%
.Matched packages, channel pecl.php.net:
=======================================
Package Stable/(Latest) Local
mongo   1.6.16 (stable)        MongoDB database driver
mongodb 1.14.2 (stable) 1.14.1 MongoDB driver for PHP
```

**Review by megahirt — APPROVED** [review]
LGTM

**Comment by megahirt** [comment]
**MongoDB Library version = 1.4.3**
```
# composer show mongodb/mongodb
name     : mongodb/mongodb
descrip. : MongoDB driver library
keywords : database, driver, mongodb, persistence
versions : * 1.4.3
type     : library
```

**MongoDB PECL Extension version = 1.14.1**
```
# pecl list
Installed packages, channel pecl.php.net:
=========================================
Package Version State
mongodb 1.14.1  stable
xdebug  3.1.6   stable
```

image

Screenshot 2022-11-21 at 11 04 04 AM

My interpretation of the table is that we are stuck on an older version of the MongoDB driver library that does not support the new features in Mongo 4.2, 4.4, 5.0 and 6.0 because we are using a deprecated version of PHP (version 7.3).

The nice thing is that the documentation says that the driver still works with the older version of PHP and the library, but that newer features are not supported.  So I am still comfortable moving forward with the upgrade to 6.0 assuming the site continues to work as normal.  Upgrading to a later version of PHP may not be possible without significant refactoring because we are using obsolete libraries that might depend on the older version of PHP.

**Comment by megahirt** [comment]
@longrunningprocess wrote:
>  `# pecl search mongo`

`pecl search` is intended to query the internet database, not local packages.  It looks like it does tell you what you have installed locally, but the output could be mis-interpreted.  I recommend using `pecl list` instead to see locally installed packages.

**Comment by longrunningprocess** [comment]
upgraded container in staging

image

**Comment by megahirt** [comment]
Based on our discussions, I don't have concerns with upgrading the composer library to the latest, assuming we are allowed to do that based upon our PHP 7.3 version.  It sounds like you've already done this locally and it's working, so go ahead and move forward with that!

**Comment by longrunningprocess** [comment]
manually upgraded running prod container 4.4 via [b943cca](https://github.com/sillsdev/web-languageforge/commit/b943ccab985234c12a5731f7eb0e448a8698ed37)

**Comment by longrunningprocess** [comment]
clean shutdown of prod db

clean db start up but kept oomkilled, so increased max RAM to 1.2 GB


upgraded compat

image


reduced RAM back to 400 MB

clean startup and good smoke test of app in prod.

**Pull request merged**
