### PR TITLE
AngularJS UI for managing Language Depot projects in Language Forge admin interface

### PR DESCRIPTION
**Pull request by rmunn**
Also contains UI for LF users (non-admin) who manage a Language Depot project to be able to manage that project's membership (add/remove users, promote to manager, demote managers to regular contributors as long as they weren't the last manager on the project).

There are probably some places where this is missing polish, but it's time to get this reviewed and then merged into master. Any missing bits can go in a new PR that won't be a long-lived branch.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/803)

### CODE REVIEW

**Comment by megahirt** [comment]
Looking forward to reviewing this when it is ready.  What is the ETA on this being ready for review?

**Comment by rmunn** [comment]
Ready for review now. I've already found one missing bit: I have code to pop up notifications on success ("Added user X to project Y" and so on), but it looks like I missed one or two locations, which are still using console.log instead of popping up a notification. But as I said in the updated description, it's time to merge this long-lived branch and do the polishing work on a much shorter-lived branch.

**Review by megahirt — COMMENTED** [review]
> Reviewed 1 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/803)* status: 1 of 34 files reviewed, all discussions resolved

**Review by megahirt — CHANGES_REQUESTED** [review]
Overall this looks good.  I have a few minor questions.  I assume the .Net Core API is already in master and working?

> Reviewed 22 of 34 files at r1, 11 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-:-MRID0TH2jd3N60HGnEb:b-46k8dt)* status: all files reviewed, 7 unresolved discussions (waiting on @rmunn)

___
*[src/Api/Model/Shared/Dto/RightsHelper.php, line 415 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRI8Uf33c_mycJIYdDQ:-MRI8Uf42KMfE7MsgU8E:blhgk9c) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/Api/Model/Shared/Dto/RightsHelper.php#L415)):*
> ```PHP
>     }
> 
>     public function userIsManagerOfProject($username, $projectCode) {
> ```

I don't see a need for this public function that only calls LdapiCommands::isUserManagerOfProject()  Do you?
___
*[src/angular-app/bellows/apps/projects/projects-app.component.html, line 55 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRI9tO85c0vAdKJto8S:-MRI9tO85c0vAdKJto8T:b-4i6us5) ([raw file](https://github.com/sillsdev/web-languageforge/blob/96bf606050bce8aad238f6bf6f79cb4c4da4bfa9/src/angular-app/bellows/apps/projects/projects-app.component.html#L55)):*
> ```
>  data-ng-show="$ctrl.rights.canEditProjects"
> ```

I am curious to understand why this was deleted?
___
*[src/angular-app/bellows/apps/projects/projects-app.component.ts, line 107 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIAOJI9GT8CBZcdS-f:-MRIAOJI9GT8CBZcdS-g:bleycsn) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/apps/projects/projects-app.component.ts#L107)):*
> ```XML
>                 };
>                 if (this.isManager(project)) {
>                   this.projects.push(project);
> ```

OK so just to be clear, the projects page now shows both LF projects and LD projects in the projects list, based upon username match.  Is this correct?
___
*[src/angular-app/bellows/apps/siteadmin/ldapi-projects-view.ts, line 7 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIAjJn1-g5giSPwGzt:-MRIAjJn1-g5giSPwGzu:b-8n3t84) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/apps/siteadmin/ldapi-projects-view.ts#L7)):*
> ```XML
> import {LdapiProjectDto} from '../../../languageforge/ldproject/ldproject-app.component';
> 
> // TODO: move this and LdapiProjectInfo to an ldapi-models.ts file
> ```

go ahead and move to a new file
___
*[src/angular-app/bellows/apps/siteadmin/site-admin-users.component.html, line 141 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIB5-PCtk9En6NwKlf:-MRIB5-PCtk9En6NwKlg:b-xwtvug) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/apps/siteadmin/site-admin-users.component.html#L141)):*
> ```HTML
>                            data-idle-validate-keypress="$ctrl.resetValidateUserForm()" data-idle-validate-msec="500"
>                            data-ng-model="$ctrl.record.password" data-pui-auto-focus="$ctrl.vars.inputfocus">
>                     <a data-ng-click="$ctrl.verifyPassword($ctrl.record)">Verify</a> 
> ```

this shouldn't make it into master - would you agree?
___
*[src/angular-app/bellows/apps/siteadmin/site-admin-users.component.ts, line 257 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIBFE18K5Y0C6ViE9s:-MRIBFE18K5Y0C6ViE9t:biputr1) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/apps/siteadmin/site-admin-users.component.ts#L257)):*
> ```XML
>   }
> 
>   verifyPassword(record: UserWithPassword): void {
> ```

I'm not clear if you wrote this just for debugging/testing the API or if this is an user-facing feature.
___
*[src/angular-app/bellows/core/api/project.service.ts, line 55 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIBYzO2UDE3ePomOF1:-MRIBYzO2UDE3ePomOF2:b-cepjij) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/core/api/project.service.ts#L55)):*
> ```XML
>         languageforge: ['lexicon'],
>         scriptureforge: ['sfchecks'],
>         languagedepot: ['ldproject']
> ```

I would have written it
`languageforge: ['lexicon', 'ldproject']`
as the key `languageforge` refers to the base site.  In this application conceptually we are still in the Language Forge site but accessing data from Language Depot.d

Having a third base site of `languagedepot` could cause other issues, I'm not sure.

**Review by rmunn — COMMENTED** [review]
Yes, the API is in master (of the web-languagedepot-api project, not of this one). Right now it's failing to deploy the latest bugfixes I checked in last week, because the build agent is timing out when trying to download NuGet packages. I'm investigating that now, but once I figure out why the build agent isn't connecting to nuget.org, the API's latest bugfixes will be deployed to QA and then this will be possible to deploy to QA as well.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-:-MRJH2vN4htscPsMAoNc:bpxi76b)* status: all files reviewed, 7 unresolved discussions (waiting on @megahirt and @rmunn)

___
*[src/Api/Model/Shared/Dto/RightsHelper.php, line 415 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRI8Uf33c_mycJIYdDQ:-MRJLw9J0bf8Gz_KrYky:bb606lq) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/Api/Model/Shared/Dto/RightsHelper.php#L415)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

I don't see a need for this public function that only calls LdapiCommands::isUserManagerOfProject()  Do you?
</blockquote></details>

I think I wanted to be able to write `$this->userIsManagerOfProject()` in the code below rather than `LdapiCommands::isUserManagerOfProject()`. And if I ever refactor the LdapiCommands method, this way I only have to change it once in RightsHelper instead of in multiple places.
___
*[src/angular-app/bellows/apps/projects/projects-app.component.html, line 55 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRI9tO85c0vAdKJto8S:-MRJKYLF1rex3s4pSKaX:b-keghlv) ([raw file](https://github.com/sillsdev/web-languageforge/blob/96bf606050bce8aad238f6bf6f79cb4c4da4bfa9/src/angular-app/bellows/apps/projects/projects-app.component.html#L55)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

> ```
>  data-ng-show="$ctrl.rights.canEditProjects"
> ```

I am curious to understand why this was deleted?
</blockquote></details>

The idea, IIRC, was that I wanted everyone to see the distinction between a Language Forge project and a Language Depot project, so they wouldn't wonder why some projects take them to the entries list view and some take them to the member-management view. (Of course, they may still wonder why, because I'm not at all certain that just saying "Language Depot project" in this list is enough to explain the distinction to non-technical people. But that was the idea behind showing this to everyone.)
___
*[src/angular-app/bellows/apps/projects/projects-app.component.ts, line 107 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIAOJI9GT8CBZcdS-f:-MRJJdzU1BEUsEMBkQGI:b-487jhm) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/apps/projects/projects-app.component.ts#L107)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

OK so just to be clear, the projects page now shows both LF projects and LD projects in the projects list, based upon username match.  Is this correct?
</blockquote></details>

That's correct, though I'm certainly open to discussing whether that's the best UI choice and changing it if someone comes up with a better idea.
___
*[src/angular-app/bellows/apps/siteadmin/ldapi-projects-view.ts, line 7 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIAjJn1-g5giSPwGzt:-MRJLHBm50wwshWLkR-9:bdwltsu) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/apps/siteadmin/ldapi-projects-view.ts#L7)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

go ahead and move to a new file
</blockquote></details>

Will do. After the PR is merged into master? Or before we merge it?
___
*[src/angular-app/bellows/apps/siteadmin/site-admin-users.component.html, line 141 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIB5-PCtk9En6NwKlf:-MRJLMLSCPzto71yxagZ:bb77ufg) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/apps/siteadmin/site-admin-users.component.html#L141)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

this shouldn't make it into master - would you agree?
</blockquote></details>

Yes.
___
*[src/angular-app/bellows/apps/siteadmin/site-admin-users.component.ts, line 257 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIBFE18K5Y0C6ViE9s:-MRJLOS-EV9Ohd6AHQhe:b-wrej1y) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/apps/siteadmin/site-admin-users.component.ts#L257)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

I'm not clear if you wrote this just for debugging/testing the API or if this is an user-facing feature.
</blockquote></details>

This was for testing the API. It should be removed before we merge into master. This part of the plan for the API's future, where we start to merge user accounts from Language Forge's MongoDB database and Redmine's MySQL database, is still pretty far away so I probably should remove all references to it from the UI.
___
*[src/angular-app/bellows/core/api/project.service.ts, line 55 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIBYzO2UDE3ePomOF1:-MRJLmAOBWSVqxSlj-a1:b-q1i0xk) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/core/api/project.service.ts#L55)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

I would have written it
`languageforge: ['lexicon', 'ldproject']`
as the key `languageforge` refers to the base site.  In this application conceptually we are still in the Language Forge site but accessing data from Language Depot.d

Having a third base site of `languagedepot` could cause other issues, I'm not sure.
</blockquote></details>

I'll double-check on what this would do.

**Review by rmunn — COMMENTED** [review]
> Dismissed @megahirt from 6 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/803)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/Api/Model/Shared/Dto/RightsHelper.php, line 415 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRI8Uf33c_mycJIYdDQ:-MTs9YPgEBhFR2aFGlXC:b-6a6gsj) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/Api/Model/Shared/Dto/RightsHelper.php#L415)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

I think I wanted to be able to write `$this->userIsManagerOfProject()` in the code below rather than `LdapiCommands::isUserManagerOfProject()`. And if I ever refactor the LdapiCommands method, this way I only have to change it once in RightsHelper instead of in multiple places.
</blockquote></details>

Done: with the changes to the API authentication where authorization happens on the LD API server side, this function is no longer needed so I've removed it.
___
*[src/angular-app/bellows/apps/projects/projects-app.component.html, line 55 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRI9tO85c0vAdKJto8S:-MTsM1fS0FHyCY3uAp0C:b-l51pnp) ([raw file](https://github.com/sillsdev/web-languageforge/blob/96bf606050bce8aad238f6bf6f79cb4c4da4bfa9/src/angular-app/bellows/apps/projects/projects-app.component.html#L55)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

The idea, IIRC, was that I wanted everyone to see the distinction between a Language Forge project and a Language Depot project, so they wouldn't wonder why some projects take them to the entries list view and some take them to the member-management view. (Of course, they may still wonder why, because I'm not at all certain that just saying "Language Depot project" in this list is enough to explain the distinction to non-technical people. But that was the idea behind showing this to everyone.)
</blockquote></details>

Decided to revert this change in the end, so that users who don't have any Language Depot projects won't wonder why the word "Dictionary" is appearing in front of all their projects in the projects view. After this is deployed to QA and being tested, we can discuss the best way to help people distinguish between "a Language Forge project that I can edit dictionary entries in" and "a project that's on Language Depot which I haven't yet created a Language Forge project for".
___
*[src/angular-app/bellows/apps/siteadmin/ldapi-projects-view.ts, line 7 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIAjJn1-g5giSPwGzt:-MTsADyh94WPOaz4-K_-:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/apps/siteadmin/ldapi-projects-view.ts#L7)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

Will do. After the PR is merged into master? Or before we merge it?
</blockquote></details>

Done.
___
*[src/angular-app/bellows/apps/siteadmin/site-admin-users.component.html, line 141 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIB5-PCtk9En6NwKlf:-MTsClbQ2WKQIas0uhc2:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/apps/siteadmin/site-admin-users.component.html#L141)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Done.
___
*[src/angular-app/bellows/apps/siteadmin/site-admin-users.component.ts, line 257 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIBFE18K5Y0C6ViE9s:-MTsNJy99e0eFFJ4BvSh:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/apps/siteadmin/site-admin-users.component.ts#L257)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

This was for testing the API. It should be removed before we merge into master. This part of the plan for the API's future, where we start to merge user accounts from Language Forge's MongoDB database and Redmine's MySQL database, is still pretty far away so I probably should remove all references to it from the UI.
</blockquote></details>

Done.
___
*[src/angular-app/bellows/core/api/project.service.ts, line 55 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIBYzO2UDE3ePomOF1:-MTsNw389rk5Pc3n7Xd4:bl6mrmt) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/core/api/project.service.ts#L55)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

I'll double-check on what this would do.
</blockquote></details>

Can't do this. If we make 'ldproject' part of the available project types in the 'languageforge' site, then the "Start or Join a New Project" button becomes a dropdown that asks you to create a "Dictionary" project or a "Language Depot" project, and that would be too confusing to users. Having a base site of "languagedepot" here is actually causing the minimal number of side effects, at least with the way our other code is currently written. If we refactor things like the new projects button, then I could move the 'ldproject' project type under the 'languageforge' key here, but I don't want to do that refactor now as it would be an unnecessarily large change.

**Review by megahirt — APPROVED** [review]
> Reviewed 21 of 21 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/803)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by megahirt — APPROVED** [review]
:lgtm: Looks ready to merge!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-:-MTuXYs76XWsLmWATSdd:b-rlxaju)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by megahirt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/803)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/angular-app/bellows/core/api/project.service.ts, line 55 at r2](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MRIBYzO2UDE3ePomOF1:-MTuXoKV1QpWJY5h2wCE:bdw7ttb) ([raw file](https://github.com/sillsdev/web-languageforge/blob/111e58ce042e8f5170b82c2e3bad66eec8cddf63/src/angular-app/bellows/core/api/project.service.ts#L55)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

Can't do this. If we make 'ldproject' part of the available project types in the 'languageforge' site, then the "Start or Join a New Project" button becomes a dropdown that asks you to create a "Dictionary" project or a "Language Depot" project, and that would be too confusing to users. Having a base site of "languagedepot" here is actually causing the minimal number of side effects, at least with the way our other code is currently written. If we refactor things like the new projects button, then I could move the 'ldproject' project type under the 'languageforge' key here, but I don't want to do that refactor now as it would be an unnecessarily large change.
</blockquote></details>

ok thanks for looking into it.

**Comment by rmunn** [comment]
Added one more feature: silently swallowing "connection refused" errors when Ldapi.php tries to talk to the Language Depot API server if (and **only** if) it's being run in the dev environment. That way when I merge this into master, the other developers working on Language Forge won't be hit with several unsightly exception notifications from the LD API calls that this PR adds into Angular.

Also changed the docker-compose config version number in docker/docker-compose.yml from "3.9" to "3.5". According to https://docs.docker.com/compose/compose-file/ there's no docker-compose release that uses version number 3.9, and 3.5 is the latest version used by a docker-compose that I could get to run on my dev laptop (Bionic). I've seen version 3.9 used in some docker-compose examples in the docs, but 3.5 works fine for us.

**Review by megahirt — CHANGES_REQUESTED** [review]
@rmunn thanks for the try/catch with regard to the api environment.  A future task would be to actually publish a docker image that contains the API which we could declare as a dependency of languageforge, similar to what we need for our lfmerge docker container (unimplemented currently)

:lgtm: 

> Reviewed 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-:-MUCUTdoEOitBe2Z_MzC:by493hs)* status: all files reviewed, 1 unresolved discussion (waiting on @rmunn)

___
*[docker/docker-compose.yml, line 2 at r4](https://reviewable.io/reviews/sillsdev/web-languageforge/803#-MUCU6Pg43xkRrI8wjRP:-MUCU6Pg43xkRrI8wjRQ:bc6wd90) ([raw file](https://github.com/sillsdev/web-languageforge/blob/cb71e50b2eadf3e12a87c234a5ee448e7fae25ba/docker/docker-compose.yml#L2)):*
> ```YAML
> # https://docs.docker.com/compose/compose-file
> version: '3.5'
> ```

ok thanks for this.  We can have a separate conversation if we need something later than v3.5  As it stands, the shm_size directive introduced in 3.5 is needed for my selenium container.  Glad that still works with this change.

**Review by megahirt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/803)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by rmunn** [comment]
> @rmunn thanks for the try/catch with regard to the api environment. A future task would be to actually publish a docker image that contains the API which we could declare as a dependency of languageforge, similar to what we need for our lfmerge docker container (unimplemented currently)

I intend to do that. In fact, I already have published a docker image to the private docker.dallas.languagetechnology.org repository, so the only question is whether we want to publish a public Docker image, or set up the necessary auth config to pull from that private repo.

I'll go ahead and merge this, and do any new work on a new branch off of `master`.

**Pull request merged**
