### PR TITLE
Lexicon editor and more

### PR DESCRIPTION
**Pull request by Nateowami**
Commit messages are mostly self-explanatory.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/86)

### CODE REVIEW

**Comment by darcywong00** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/angular-app/bellows/apps/usermanagement/bootstrap4/usermanagement.html, line 24 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/86#-KdiQ3Ab-GL7WE4Xym_H:-KdiQ3Ach2Iv52aihEXH:bupkvkf) ([raw file](https://github.com/sillsdev/web-languageforge/blob/8824317c92dd0a4129084becc87f2d36549338cf/src/angular-app/bellows/apps/usermanagement/bootstrap4/usermanagement.html#L24)):*
> ```HTML
>                 <div ng-if="isActive('/members')" ui-view></div>
>             </uib-tab>
>

**Comment by Nateowami** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/angular-app/bellows/apps/usermanagement/bootstrap4/usermanagement.html, line 24 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/86#-KdiQ3Ab-GL7WE4Xym_H:-Kdxm5orIqMSfPI-PeZd:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/8824317c92dd0a4129084becc87f2d36549338cf/src/angular-app/bellows/apps/usermanagement/bootstrap4/usermanagement.html#L24)):*
<details><summary><i>Previously, darcywong00 (Darcy Wong) wrote…</i></summary><blockquote>

Rather than commenting the block out, can you set `data-ng-show="false"` like the Archive tab in settings.html?
</blockquote></details>

Done.

---

*[src/angular-app/languageforge/lexicon/views/editor-abstract.html, line 31 at r1](https://reviewable.io:443/reviews/sillsdev/web-languageforge/86#-KdiSaXLZHnJy8JG0KAX:-KdxmAyJLsWj3bA32_B1:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/8824317c92dd0a4129084becc87f2d36549338cf/src/angular-app/languageforge/lexicon/views/editor-abstract.html#L31)):*
<details><summary><i>Previously, darcywong00 (Darcy Wong) wrote…</i></summary><blockquote>

Re: discussion with @Chris, maybe `Hide Extra...` and `Show Extra...`?  
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/86)*

**Comment by darcywong00** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/86#-:-Ke1JAFQaoc_ppYUQv7q:bnfp4nl)*

**Comment by megahirt** [comment]
:lgtm:

---

Reviewed 11 of 14 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languageforge/86#-:-KeXo2rVmzwP2D3Gcv6f:bnfp4nl)*

**Pull request merged**
