### PR TITLE
Only send bugsnag errors on live and qa

### PR DESCRIPTION
**Pull request by ermshiperete**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/249)

### CODE REVIEW

**Comment by irahopkinson** [comment]
Really good job with this and remembering to change the 2 other `config.php` copies. :lgtm: with some minor comments.

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.gitignore, line 66 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/249#-LC3WD-M4JXOZQ6jxXoC:-LC3WD-M4JXOZQ6jxXoD:bhkguyi) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b8a752084c62f17ea95f390e486ed3dccd166917/.gitignore#L66)):*
> ```
> # Generated files
> src/Api/Library/Shared/WebsiteInstances.php
> src/angular-app/bellows/website-instances.ts
> ```

Ideally this file would have a type in its name like `website-instances.data.ts` and be moved to `src/angular-app/bellows/shared/`.

---

*[src/angular-app/bellows/core/exception-handling.service.ts, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/249#-LC3TCAMEXU5FRudkaXJ:-LC3TCAMEXU5FRudkaXK:b-qlp05e) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b8a752084c62f17ea95f390e486ed3dccd166917/src/angular-app/bellows/core/exception-handling.service.ts#L4)):*
> ```XML
> import Bugsnag from 'bugsnag-js';
> import { Client } from 'bugsnag-js/types/client';
> import {websiteInstances} from '../website-instances';
> ```

Style: place a blank line between vendor/external and internal imports.

---

*[src/angular-app/bellows/core/exception-handling.service.ts, line 27 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/249#-LC3TuUIBjkMnRs4E96-:-LC3TuUIBjkMnRs4E960:beuaeaw) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b8a752084c62f17ea95f390e486ed3dccd166917/src/angular-app/bellows/core/exception-handling.service.ts#L27)):*
> ```
> this.metadata = null
> ```
Style: this initialisation can go on the declaration. And initialised properties are listed before uninitialised ones.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/249#-:-LC3XTbi5LsWKQlOU1I5:b-ytfvdc)*

**Comment by irahopkinson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.gitignore, line 66 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/249#-LC3WD-M4JXOZQ6jxXoC:-LC3dbj07Fk8dW4uZVvz:bymndo5) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b8a752084c62f17ea95f390e486ed3dccd166917/.gitignore#L66)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Ideally this file would have a type in its name like `website-instances.data.ts` and be moved to `src/angular-app/bellows/shared/`.
</blockquote></details>

Actually this is really `core` rather than `shared` so move to `src/angular-app/bellows/core/`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/249)*

**Comment by irahopkinson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.gitignore, line 66 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/249#-LC3WD-M4JXOZQ6jxXoC:-LC5OpvN3_M7kvtzxYF4:b-p2bjim) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b8a752084c62f17ea95f390e486ed3dccd166917/.gitignore#L66)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Actually this is really `core` rather than `shared` so move to `src/angular-app/bellows/core/`.
</blockquote></details>

Maybe something like `website-instances.generated-data.ts` would be better.

Also in the past we have not ignored these generated files but checked them in so that they are already present when the repo is cloned (means there isn't another step after developer Ansible deploy). Other scenarios we have checked them in and ignored them. I don't know what's best here and am happy to leave as is here (if so ideally we would add the build step to the end of Ansible deploy).

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/249)*

**Comment by ermshiperete** [comment]
Review status: 14 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[.gitignore, line 66 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/249#-LC3WD-M4JXOZQ6jxXoC:-LCT4Xqa9jtsYZbEOPOl:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b8a752084c62f17ea95f390e486ed3dccd166917/.gitignore#L66)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Maybe something like `website-instances.generated-data.ts` would be better.

Also in the past we have not ignored these generated files but checked them in so that they are already present when the repo is cloned (means there isn't another step after developer Ansible deploy). Other scenarios we have checked them in and ignored them. I don't know what's best here and am happy to leave as is here (if so ideally we would add the build step to the end of Ansible deploy).
</blockquote></details>

Done.

---

*[src/angular-app/bellows/core/exception-handling.service.ts, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/249#-LC3TCAMEXU5FRudkaXJ:-LCStw_qCpSr4dVCVvqm:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b8a752084c62f17ea95f390e486ed3dccd166917/src/angular-app/bellows/core/exception-handling.service.ts#L4)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Style: place a blank line between vendor/external and internal imports.
</blockquote></details>

Done.

---

*[src/angular-app/bellows/core/exception-handling.service.ts, line 27 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/249#-LC3TuUIBjkMnRs4E96-:-LCSuTBX0V-As_KBGmes:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/b8a752084c62f17ea95f390e486ed3dccd166917/src/angular-app/bellows/core/exception-handling.service.ts#L27)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> this.metadata = null
> ```
Style: this initialisation can go on the declaration. And initialised properties are listed before uninitialised ones.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/249)*

**Comment by megahirt** [comment]
Reviewed 12 of 19 files at r1, 9 of 10 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/249)*

**Comment by megahirt** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/249#-:-LCVTuIx5g2EhhLK3G27:bnfp4nl)*

**Comment by megahirt** [comment]
@irahopkinson  merge this one when you're satisfied

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/249#-:-LCVTz736VTDzxu3CSTB:b-k654hf)*

**Comment by irahopkinson** [comment]
:lgtm:

---

Reviewed 9 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/249#-:-LCWkuJMEmYks6va1Hhy:bnfp4nl)*

**Pull request merged**
